Paparazzi UAS: sw/airborne/boards/ardrone/actuators_ardrone2_raw.h File Reference
actuators_ardrone2_raw.h File Reference
Actuator driver for ardrone2-raw version.
#include <stdint.h>
Macros
#define ACTUATORS_ARDRONE_NB 4
#define SERVOS_TICS_OF_USEC(_v) (_v)
#define ActuatorArdroneSet(_i, _v) { actuators_pwm_values[_i] = _v; }
#define ActuatorsArdroneCommit() actuators_ardrone_commit();
#define ActuatorsArdroneInit() actuators_ardrone_init();
#define MOT_LEDOFF 0
#define MOT_LEDRED 1
#define MOT_LEDGREEN 2
#define MOT_LEDORANGE 3
Functions
void actuators_ardrone_commit (void)
void actuators_ardrone_init (void)
int actuators_ardrone_cmd (uint8_t cmd, uint8_t *reply, int replylen)
void actuators_ardrone_set_pwm (uint16_t pwm0, uint16_t pwm1, uint16_t pwm2, uint16_t pwm3)
Write motor speed command cmd = 001aaaaa aaaabbbb bbbbbccc ccccccdd ddddddd0.
void actuators_ardrone_set_leds (uint8_t led0, uint8_t led1, uint8_t led2, uint8_t led3)
Write LED command cmd = 011rrrr0 000gggg0 (this is ardrone1 format, we need ardrone2 format)
void actuators_ardrone_close (void)
Variables
uint16_t actuators_pwm_values [ACTUATORS_ARDRONE_NB]
Detailed Description
Actuator driver for ardrone2-raw version.
Definition in file actuators_ardrone2_raw.h.
Macro Definition Documentation
#define ActuatorArdroneSet (_i, _v) { actuators_pwm_values[_i] = _v; }
Definition at line 42 of file actuators_ardrone2_raw.h.
#define ACTUATORS_ARDRONE_NB 4
Definition at line 37 of file actuators_ardrone2_raw.h.
#define ActuatorsArdroneCommit () actuators_ardrone_commit();
Definition at line 43 of file actuators_ardrone2_raw.h.
#define ActuatorsArdroneInit () actuators_ardrone_init();
Definition at line 44 of file actuators_ardrone2_raw.h.
#define MOT_LEDGREEN 2
Definition at line 48 of file actuators_ardrone2_raw.h.
Referenced by actuators_ardrone_init().
#define MOT_LEDOFF 0
Definition at line 46 of file actuators_ardrone2_raw.h.
#define MOT_LEDORANGE 3
Definition at line 49 of file actuators_ardrone2_raw.h.
#define MOT_LEDRED 1
Definition at line 47 of file actuators_ardrone2_raw.h.
Referenced by actuators_ardrone_init().
#define SERVOS_TICS_OF_USEC (_v) (_v)
Definition at line 40 of file actuators_ardrone2_raw.h.
Function Documentation
void actuators_ardrone_close (void)
Definition at line 281 of file actuators_ardrone2_raw.c.
References actuator_ardrone2_raw_fd.
int actuators_ardrone_cmd (uint8_t cmd, uint8_t * reply, int replylen)
Definition at line 160 of file actuators_ardrone2_raw.c.
References actuator_ardrone2_raw_fd, full_read(), and full_write().
Referenced by actuators_ardrone_init().
void actuators_ardrone_commit (void)
Definition at line 231 of file actuators_ardrone2_raw.c.
References actuators_ardrone_motor_status(), actuators_ardrone_set_pwm(), and actuators_pwm_values.
void actuators_ardrone_init (void)
Definition at line 81 of file actuators_ardrone2_raw.c.
References actuator_ardrone2_raw_fd, actuators_ardrone_cmd(), actuators_ardrone_reset_flipflop(), actuators_ardrone_set_leds(), ARDRONE_GPIO_PIN_IRQ_FLIPFLOP, ARDRONE_GPIO_PIN_IRQ_INPUT, ARDRONE_GPIO_PIN_MOTOR1, ARDRONE_GPIO_PIN_MOTOR2, ARDRONE_GPIO_PIN_MOTOR3, ARDRONE_GPIO_PIN_MOTOR4, ARDRONE_GPIO_PORT, B115200, gpio_clear(), gpio_set(), gpio_setup_input(), gpio_setup_output(), led_hw_values, MOT_LEDGREEN, and MOT_LEDRED.
void actuators_ardrone_set_leds (uint8_t led0, uint8_t led1, uint8_t led2, uint8_t led3)
Write LED command cmd = 011rrrr0 000gggg0 (this is ardrone1 format, we need ardrone2 format)
led0 = RearLeft led1 = RearRight led2 = FrontRight led3 = FrontLeft
Definition at line 264 of file actuators_ardrone2_raw.c.
References actuator_ardrone2_raw_fd, and full_write().
Referenced by actuators_ardrone_init(), and actuators_ardrone_led_run().
void actuators_ardrone_set_pwm (uint16_t pwm0, uint16_t pwm1, uint16_t pwm2, uint16_t pwm3)
Write motor speed command cmd = 001aaaaa aaaabbbb bbbbbccc ccccccdd ddddddd0.
Definition at line 241 of file actuators_ardrone2_raw.c.
References actuator_ardrone2_raw_fd, actuators_ardrone_led_run(), and full_write().
Referenced by actuators_ardrone_commit().
Variable Documentation
uint16_t actuators_pwm_values[ACTUATORS_ARDRONE_NB]
Definition at line 51 of file actuators_ardrone2_raw.h.