Paparazzi UAS: sw/airborne/modules/ins/ahrs_chimu_spi.c File Reference
ahrs_chimu_spi.c File Reference
#include <stdbool.h>
#include "mcu_periph/spi.h"
#include "mcu_periph/spi_slave_hs_arch.h"
#include "state.h"
#include "subsystems/gps.h"
#include "subsystems/ahrs.h"
#include "generated/airframe.h"
#include "ins_module.h"
#include "imu_chimu.h"
#include "led.h"
Functions
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void parse_ins_msg (void)
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Variables
CHIMU_PARSER_DATA CHIMU_DATA
INS_FORMAT ins_roll_neutral
INS_FORMAT ins_pitch_neutral
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 71 of file ahrs_chimu_spi.c.
Referenced by imu_impl_init(), on_gyro_accel_event(), and on_gyro_event().
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 37 of file ahrs_chimu_spi.c.
Referenced by init_ap(), and main_init().
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 134 of file ahrs_chimu_spi.c.
Referenced by on_gyro_accel_event(), on_gyro_event(), and sensors_task().
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 137 of file ahrs_chimu_spi.c.
Referenced by on_accel_event(), on_gyro_accel_event(), and on_gyro_event().
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 112 of file ahrs_chimu_spi.c.
Referenced by on_gps_event(), and on_gps_solution().
static void parse_ins_msg (void) inline
Definition at line 76 of file ahrs_chimu_spi.c.
Referenced by vn100_event_task().
Variable Documentation
CHIMU_PARSER_DATA CHIMU_DATA
Definition at line 32 of file ahrs_chimu_spi.c.
INS_FORMAT ins_pitch_neutral
Definition at line 35 of file ahrs_chimu_spi.c.
INS_FORMAT ins_roll_neutral
Todo:
harmonize infrared neutrals with ins_neutrals or get rid of ins neutrals this ins only needed for sim right now
Definition at line 34 of file ahrs_chimu_spi.c.