Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_gx3.h File Reference
ahrs_gx3.h File Reference
Driver for Microstrain GX3 IMU/AHRS subsystem.
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "subsystems/ahrs.h"
#include "subsystems/ins.h"
#include "subsystems/gps.h"
#include "mcu_periph/uart.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "state.h"
#include "led.h"
Data Structures
struct GX3Packet
struct AhrsFloatQuat
Macros
#define ImuScaleGyro(_imu) {}
#define ImuScaleAccel(_imu) {}
#define ImuScaleMag(_imu) {}
#define GX3_MAX_PAYLOAD 128
#define GX3_MSG_LEN 67
#define GX3_HEADER 0xC8
#define GX3_MIN_FREQ 300
#define IMU_GX3_LONG_DELAY 4000000
Enumerations
enum GX3PacketStatus { GX3PacketWaiting, GX3PacketReading }
enum GX3Status { GX3Uninit, GX3Running }
Functions
void gx3_packet_read_message (void)
void gx3_packet_parse (uint8_t c)
static void ReadGX3Buffer (void)
static void ImuEvent (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct AhrsFloatQuat ahrs_impl
Detailed Description
Driver for Microstrain GX3 IMU/AHRS subsystem.
Takes care of configuration of the IMU, communication and parsing the received packets. See GX3 datasheet for configuration options.
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file ahrs_gx3.h.
Macro Definition Documentation
#define GX3_HEADER 0xC8
Definition at line 63 of file ahrs_gx3.h.
Referenced by gx3_packet_parse().
#define GX3_MAX_PAYLOAD 128
Definition at line 61 of file ahrs_gx3.h.
#define GX3_MIN_FREQ 300
Definition at line 64 of file ahrs_gx3.h.
#define GX3_MSG_LEN 67
Definition at line 62 of file ahrs_gx3.h.
Referenced by gx3_packet_parse(), and gx3_verify_chk().
#define IMU_GX3_LONG_DELAY 4000000
Definition at line 66 of file ahrs_gx3.h.
Referenced by imu_impl_init().
#define ImuScaleAccel (_imu) {}
Definition at line 54 of file ahrs_gx3.h.
Referenced by on_accel_event(), on_gyro_accel_event(), and on_gyro_event().
#define ImuScaleGyro (_imu) {}
Definition at line 49 of file ahrs_gx3.h.
Referenced by on_gyro_accel_event(), and on_gyro_event().
#define ImuScaleMag (_imu) {}
Definition at line 59 of file ahrs_gx3.h.
Referenced by on_mag_event().
Enumeration Type Documentation
enum GX3PacketStatus
Enumerator:
GX3PacketWaiting
GX3PacketReading
Definition at line 80 of file ahrs_gx3.h.
enum GX3Status
Enumerator:
GX3Uninit
GX3Running
Definition at line 85 of file ahrs_gx3.h.
Function Documentation
void gx3_packet_parse (uint8_t c)
Definition at line 295 of file ahrs_gx3.c.
References ahrs_impl, c, FALSE, GX3_HEADER, GX3_MSG_LEN, gx3_verify_chk(), GX3PacketReading, GX3PacketWaiting, and TRUE.
Referenced by ReadGX3Buffer().
void gx3_packet_read_message (void)
Definition at line 229 of file ahrs_gx3.c.
References Imu::accel, ImuFloat::accel, ACCELS_BFP_OF_REAL, ahrs_impl, bef(), ImuFloat::body_to_imu_rmat, GpsState::course, FLOAT_EULERS_OF_RMAT, FLOAT_RMAT_COMP, FLOAT_RMAT_TRANSP_RATEMULT, gps, GX3_CHKSM, ImuFloat::gyro, imu, imuf, ins_pitch_neutral, ins_roll_neutral, FloatEulers::phi, FloatEulers::psi, stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), stateSetNedToBodyRMat_f(), FloatEulers::theta, and VECT3_SMUL.
Referenced by ImuEvent().
static void ImuEvent (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 113 of file ahrs_gx3.h.
References ahrs_impl, FALSE, gx3_packet_read_message(), ReadGX3Buffer(), and uart_char_available().
static void ReadGX3Buffer (void) inline static
Definition at line 108 of file ahrs_gx3.h.
References ahrs_impl, gx3_packet_parse(), uart_char_available(), and uart_getch().
Referenced by ImuEvent().
Variable Documentation
struct AhrsFloatQuat ahrs_impl
Definition at line 45 of file ahrs_ardrone2.c.