Paparazzi UAS: sw/airborne/subsystems/air_data.c File Reference
air_data.c File Reference
Air Data interface.
#include "subsystems/air_data.h"
#include "subsystems/abi.h"
Macros
#define AIR_DATA_BARO_ABS_ID ABI_BROADCAST
ABI bindings.
Functions
static void pressure_abs_cb (uint8_t sender_id, const float *pressure)
void air_data_init (void)
AirData initialization.
Variables
struct AirData air_data
global AirData state
static abi_event pressure_abs_ev
Detailed Description
Air Data interface.
pressures
airspeed
angle of attack and sideslip
wind
Definition in file air_data.c.
Macro Definition Documentation
#define AIR_DATA_BARO_ABS_ID ABI_BROADCAST
ABI bindings.
Definition at line 41 of file air_data.c.
Referenced by air_data_init().
Function Documentation
void air_data_init (void)
AirData initialization.
Called at startup. Bind ABI messages
Definition at line 61 of file air_data.c.
References AIR_DATA_BARO_ABS_ID, pressure_abs_cb(), and register_periodic_telemetry().
Referenced by init_ap(), and main_init().
static void pressure_abs_cb (uint8_t sender_id, const float * pressure) static
Definition at line 45 of file air_data.c.
References air_data, and AirData::pressure.
Referenced by air_data_init().
Variable Documentation
struct AirData air_data
global AirData state
Definition at line 36 of file air_data.c.
Referenced by main_on_baro_abs(), and pressure_abs_cb().
abi_event pressure_abs_ev static
Definition at line 43 of file air_data.c.