Paparazzi UAS: sw/airborne/subsystems/air_data.h File Reference
air_data.h File Reference
Air Data interface.
#include "std.h"
Data Structures
struct AirData
Air Data strucute.
Functions
void air_data_init (void)
AirData initialization.
Variables
struct AirData air_data
global AirData state
Detailed Description
Air Data interface.
pressures
airspeed
angle of attack and sideslip
wind
Definition in file air_data.h.
Function Documentation
void air_data_init (void)
AirData initialization.
Called at startup.
Called at startup. Bind ABI messages
Definition at line 61 of file air_data.c.
References AIR_DATA_BARO_ABS_ID, pressure_abs_cb(), and register_periodic_telemetry().
Referenced by init_ap(), and main_init().
Variable Documentation
struct AirData air_data
global AirData state
Definition at line 36 of file air_data.c.
Referenced by main_on_baro_abs(), and pressure_abs_cb().