Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/debug_led.h File Reference
debug_led.h File Reference
Functions
static void LED1_ON (void)
static void LED1_OFF (void)
static void LED2_ON (void)
static void LED2_OFF (void)
static void LED_INIT (void)
static void LED_ERROR (uint8_t base, uint8_t nr)
static void LED_SHOW_ACTIVE_BITS (I2C_TypeDef *regs)
Function Documentation
static void LED1_OFF (void) inline static
Definition at line 8 of file debug_led.h.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_INIT(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), and PPRZ_I2C_SEND_STOP().
static void LED1_ON (void) inline static
Definition at line 3 of file debug_led.h.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), LED_ERROR(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), and PPRZ_I2C_SEND_STOP().
static void LED2_OFF (void) inline static
Definition at line 18 of file debug_led.h.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), i2c_submit(), LED_ERROR(), LED_INIT(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), and PPRZ_I2C_SEND_STOP().
static void LED2_ON (void) inline static
Definition at line 13 of file debug_led.h.
Referenced by i2c_event(), i2c_irq(), i2c_setbitrate(), i2c_submit(), LED_ERROR(), LED_SHOW_ACTIVE_BITS(), PPRZ_I2C_SEND_START(), and PPRZ_I2C_SEND_STOP().
static void LED_ERROR (uint8_t base, uint8_t nr) inline static
Definition at line 37 of file debug_led.h.
References LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_error().
static void LED_INIT (void) inline static
Definition at line 23 of file debug_led.h.
References LED1_OFF(), and LED2_OFF().
static void LED_SHOW_ACTIVE_BITS (I2C_TypeDef * regs) inline static
Definition at line 48 of file debug_led.h.
References BIT_X_IS_SET_IN_REG, LED1_OFF(), LED1_ON(), LED2_OFF(), and LED2_ON().
Referenced by i2c_irq(), and PPRZ_I2C_SEND_START().