Paparazzi UAS: sw/airborne/subsystems/electrical.h File Reference
electrical.h File Reference
Interface for electrical status: supply voltage, current, battery status, etc.
#include "std.h"
#include "generated/airframe.h"
Data Structures
struct Electrical
Macros
#define LOW_BAT_LEVEL 10.5
low battery level in Volts (for 3S LiPo)
#define CRITIC_BAT_LEVEL 9.8
critical battery level in Volts (for 3S LiPo)
Functions
void electrical_init (void)
void electrical_periodic (void)
Variables
struct Electrical electrical
Detailed Description
Interface for electrical status: supply voltage, current, battery status, etc.
Definition in file electrical.h.
Macro Definition Documentation
#define CRITIC_BAT_LEVEL 9.8
critical battery level in Volts (for 3S LiPo)
Definition at line 42 of file electrical.h.
Referenced by electrical_periodic().
#define LOW_BAT_LEVEL 10.5
low battery level in Volts (for 3S LiPo)
Definition at line 36 of file electrical.h.
Referenced by electrical_periodic(), and max7456_periodic().
Function Documentation
void electrical_init (void)
Definition at line 35 of file electrical_dummy.c.
References adc_buf_channel(), ADC_CHANNEL_VSUPPLY, Electrical::bat_critical, Electrical::bat_low, Electrical::current, CURRENT_ESTIMATION_NONLINEARITY, DEFAULT_AV_NB_SAMPLE, electrical_setup(), FALSE, fd, I2C_SLAVE_FORCE, PRINT_CONFIG_VAR(), and Electrical::vsupply.
Referenced by init_fbw(), and main_init().
void electrical_periodic (void)
Definition at line 37 of file electrical_dummy.c.
References BAT_CHECKER_DELAY, Electrical::bat_critical, Electrical::bat_low, commands, CRITIC_BAT_LEVEL, Electrical::current, electrical, ELECTRICAL_PERIODIC_FREQ, electrical_setup(), FALSE, fd, i2c_smbus_read_byte_data(), LOW_BAT_LEVEL, MAX_PPRZ, MilliAmpereOfAdc, TRUE, VoltageOfAdc, and Electrical::vsupply.
Referenced by handle_periodic_tasks(), handle_periodic_tasks_fbw(), and sim_periodic_task().
Variable Documentation
struct Electrical electrical
Definition at line 33 of file electrical_dummy.c.
Referenced by ahrs_propagate(), bat_checker_periodic(), electrical_periodic(), ezcurrent_init(), ezcurrent_read_event(), failsafe_check(), generic_com_periodic(), max7456_periodic(), send_imu_mag_current(), send_status(), and update_bat().