Paparazzi UAS: sw/airborne/boards/ardrone/electrical_raw.c File Reference
electrical_raw.c File Reference
arch specific electrical status readings
#include "electrical_raw.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/time.h>
#include <unistd.h>
#include <math.h>
#include "i2c-dev.h"
#include "subsystems/commands.h"
#include "generated/airframe.h"
Macros
#define CURRENT_ESTIMATION_NONLINEARITY 1.2
Functions
void electrical_init (void)
void electrical_setup (void)
void electrical_periodic (void)
Variables
struct Electrical electrical
int fd
Detailed Description
arch specific electrical status readings
Definition in file electrical_raw.c.
Macro Definition Documentation
#define CURRENT_ESTIMATION_NONLINEARITY 1.2
Definition at line 65 of file electrical_raw.c.
Referenced by electrical_init().
Function Documentation
void electrical_init (void)
Definition at line 70 of file electrical_raw.c.
References CURRENT_ESTIMATION_NONLINEARITY, electrical_setup(), fd, and I2C_SLAVE_FORCE.
void electrical_periodic (void)
Definition at line 108 of file electrical_raw.c.
References commands, Electrical::current, electrical, electrical_setup(), fd, i2c_smbus_read_byte_data(), MAX_PPRZ, and Electrical::vsupply.
void electrical_setup (void)
Definition at line 85 of file electrical_raw.c.
References fd, and i2c_smbus_write_byte_data().
Referenced by electrical_init(), and electrical_periodic().
Variable Documentation
struct Electrical electrical
Definition at line 42 of file electrical_raw.c.
int fd
Definition at line 68 of file electrical_raw.c.
Referenced by electrical_init(), electrical_periodic(), electrical_setup(), and uart_handler().