Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_v_adapt.h File Reference
guidance_v_adapt.h File Reference
Adaptation block of the vertical guidance.
#include "std.h"
Macros
#define GV_ADAPT_X_FRAC 24
#define GV_ADAPT_P_FRAC 18
Functions
void gv_adapt_init (void)
void gv_adapt_run (int32_t zdd_meas, int32_t thrust_applied, int32_t zd_ref)
Adaptation function.
Variables
int32_t gv_adapt_X
State of the estimator.
int32_t gv_adapt_P
Covariance.
int32_t gv_adapt_Xmeas
Measurement.
Detailed Description
Adaptation block of the vertical guidance.
This is a dimension one kalman filter estimating the ratio of vertical acceleration over thrust command (~ inverse of the mass) needed by the invert dynamic model to produce a nominal command.
Definition in file guidance_v_adapt.h.
Macro Definition Documentation
#define GV_ADAPT_P_FRAC 18
Definition at line 47 of file guidance_v_adapt.h.
Referenced by gv_adapt_run().
#define GV_ADAPT_X_FRAC 24
Definition at line 40 of file guidance_v_adapt.h.
Referenced by gv_adapt_run(), and run_hover_loop().
Function Documentation
void gv_adapt_init (void)
Definition at line 115 of file guidance_v_adapt.c.
References gv_adapt_P0, and gv_adapt_X0.
Referenced by guidance_v_init(), guidance_v_notify_in_flight(), and guidance_v_run().
void gv_adapt_run (int32_t zdd_meas, int32_t thrust_applied, int32_t zd_ref)
Adaptation function.
Parameters
zdd_meas vert accel measurement in m/s^2 with INT32_ACCEL_FRAC
thrust_applied controller input [0 : MAX_PPRZ]
zd_ref vertical speed reference in m/s with INT32_SPEED_FRAC
Definition at line 127 of file guidance_v_adapt.c.
References ACCEL_BFP_OF_REAL, BFP_OF_REAL, E, GUIDANCE_V_ADAPT_MAX_ACCEL, GUIDANCE_V_ADAPT_MAX_CMD, GUIDANCE_V_ADAPT_MAX_HOVER_THROTTLE, GUIDANCE_V_ADAPT_MIN_CMD, GUIDANCE_V_ADAPT_MIN_HOVER_THROTTLE, GV_ADAPT_MEAS_NOISE_HOVER, GV_ADAPT_MEAS_NOISE_OF_ZD, gv_adapt_P, gv_adapt_P0, GV_ADAPT_P_FRAC, GV_ADAPT_SYS_NOISE, gv_adapt_X, GV_ADAPT_X_FRAC, INT32_ACCEL_FRAC, INT32_SPEED_FRAC, K_FRAC, MAX_PPRZ, and ref.
Referenced by guidance_v_run().
Variable Documentation
int32_t gv_adapt_P
Covariance.
fixed point representation with GV_ADAPT_P_FRAC Q13.18
Definition at line 95 of file guidance_v_adapt.c.
Referenced by gv_adapt_run().
int32_t gv_adapt_X
State of the estimator.
fixed point representation with GV_ADAPT_X_FRAC Q13.18
Definition at line 94 of file guidance_v_adapt.c.
Referenced by gv_adapt_run(), and run_hover_loop().
int32_t gv_adapt_Xmeas
Measurement.
Definition at line 96 of file guidance_v_adapt.c.