Paparazzi UAS: sw/airborne/subsystems/imu/imu_gl1.h File Reference
imu_gl1.h File Reference
Interface for I2c IMU using using L3G4200, ADXL345, HMC5883 and BMP085.
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "subsystems/imu/imu_gl1_defaults.h"
#include "peripherals/l3g4200.h"
#include "peripherals/hmc58xx.h"
#include "peripherals/adxl345_i2c.h"
Data Structures
struct ImuGL1I2c
Functions
void imu_gl1_i2c_event (void)
static void ImuEvent (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct ImuGL1I2c imu_gl1
Detailed Description
Interface for I2c IMU using using L3G4200, ADXL345, HMC5883 and BMP085.
Definition in file imu_gl1.h.
Function Documentation
void imu_gl1_i2c_event (void)
Definition at line 121 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, Imu::accel_unscaled, ImuGL1I2c::accel_valid, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, L3g4200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, L3g4200::data_available, FALSE, ImuGL1I2c::gyro_l3g, Imu::gyro_unscaled, ImuGL1I2c::gyro_valid, hmc58xx_event(), imu, imu_gl1, l3g4200_event(), ImuGL1I2c::mag_hmc, Imu::mag_unscaled, ImuGL1I2c::mag_valid, Int32Rates::p, Int32Rates::q, Int32Rates::r, L3g4200::rates, RATES_COPY, TRUE, Adxl345_I2c::vect, Hmc58xx::vect, VECT3_COPY, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
static void ImuEvent (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 56 of file imu_gl1.h.
References ImuGL1I2c::accel_valid, FALSE, ImuGL1I2c::gyro_valid, imu_gl1, imu_gl1_i2c_event(), and ImuGL1I2c::mag_valid.
Variable Documentation
struct ImuGL1I2c imu_gl1
Definition at line 77 of file imu_gl1.c.
Referenced by imu_gl1_i2c_event(), imu_periodic(), and ImuEvent().