Paparazzi UAS: sw/airborne/subsystems/imu/imu_drotek_10dof_v2.h File Reference
imu_drotek_10dof_v2.h File Reference
Driver for the Drotek 10DOF V2 IMU.
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_i2c.h"
#include "peripherals/hmc58xx.h"
Data Structures
struct ImuDrotek2
Macros
#define IMU_MAG_X_SIGN 1
#define IMU_MAG_Y_SIGN 1
#define IMU_MAG_Z_SIGN 1
#define IMU_GYRO_P_SIGN 1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define IMU_GYRO_P_SENS 2.17953
default gyro sensitivy and neutral from the datasheet MPU with 1000 deg/s has 32.8 LSB/(deg/s) sens = 1/32.8 * pi/180 * 2^INT32_RATE_FRAC sens = 1/32.8 * pi/180 * 4096 = 2.17953 I
#define IMU_GYRO_P_SENS_NUM 18271
#define IMU_GYRO_P_SENS_DEN 8383
#define IMU_GYRO_Q_SENS 2.17953
#define IMU_GYRO_Q_SENS_NUM 18271
#define IMU_GYRO_Q_SENS_DEN 8383
#define IMU_GYRO_R_SENS 2.17953
#define IMU_GYRO_R_SENS_NUM 18271
#define IMU_GYRO_R_SENS_DEN 8383
#define IMU_GYRO_P_NEUTRAL 0
#define IMU_GYRO_Q_NEUTRAL 0
#define IMU_GYRO_R_NEUTRAL 0
#define IMU_ACCEL_X_SENS 2.4525
default accel sensitivy from the datasheet MPU with 8g has 4096 LSB/g sens = 9.81 [m/s^2] / 4096 [LSB/g] * 2^INT32_ACCEL_FRAC = 2.4525
#define IMU_ACCEL_X_SENS_NUM 981
#define IMU_ACCEL_X_SENS_DEN 400
#define IMU_ACCEL_Y_SENS 2.4525
#define IMU_ACCEL_Y_SENS_NUM 981
#define IMU_ACCEL_Y_SENS_DEN 400
#define IMU_ACCEL_Z_SENS 2.4525
#define IMU_ACCEL_Z_SENS_NUM 981
#define IMU_ACCEL_Z_SENS_DEN 400
#define IMU_ACCEL_X_NEUTRAL 0
#define IMU_ACCEL_Y_NEUTRAL 0
#define IMU_ACCEL_Z_NEUTRAL 0
Functions
void imu_drotek2_event (void)
bool_t imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void *mpu)
callback function to configure hmc5883 mag
static void ImuEvent (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct ImuDrotek2 imu_drotek2
Detailed Description
Driver for the Drotek 10DOF V2 IMU.
MPU6050 + HMC5883 + MS5611
Definition in file imu_drotek_10dof_v2.h.
Macro Definition Documentation
#define IMU_ACCEL_X_NEUTRAL 0
Definition at line 97 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_X_SENS 2.4525
default accel sensitivy from the datasheet MPU with 8g has 4096 LSB/g sens = 9.81 [m/s^2] / 4096 [LSB/g] * 2^INT32_ACCEL_FRAC = 2.4525
Definition at line 86 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_X_SENS_DEN 400
Definition at line 88 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_X_SENS_NUM 981
Definition at line 87 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_X_SIGN 1
Definition at line 51 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Y_NEUTRAL 0
Definition at line 98 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Y_SENS 2.4525
Definition at line 89 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Y_SENS_DEN 400
Definition at line 91 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Y_SENS_NUM 981
Definition at line 90 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Y_SIGN 1
Definition at line 52 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Z_NEUTRAL 0
Definition at line 99 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Z_SENS 2.4525
Definition at line 92 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Z_SENS_DEN 400
Definition at line 94 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Z_SENS_NUM 981
Definition at line 93 of file imu_drotek_10dof_v2.h.
#define IMU_ACCEL_Z_SIGN 1
Definition at line 53 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_P_NEUTRAL 0
Definition at line 75 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_P_SENS 2.17953
default gyro sensitivy and neutral from the datasheet MPU with 1000 deg/s has 32.8 LSB/(deg/s) sens = 1/32.8 * pi/180 * 2^INT32_RATE_FRAC sens = 1/32.8 * pi/180 * 4096 = 2.17953 I
Definition at line 64 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_P_SENS_DEN 8383
Definition at line 66 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_P_SENS_NUM 18271
Definition at line 65 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_P_SIGN 1
Definition at line 46 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_Q_NEUTRAL 0
Definition at line 76 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_Q_SENS 2.17953
Definition at line 67 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_Q_SENS_DEN 8383
Definition at line 69 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_Q_SENS_NUM 18271
Definition at line 68 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_Q_SIGN 1
Definition at line 47 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_R_NEUTRAL 0
Definition at line 77 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_R_SENS 2.17953
Definition at line 70 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_R_SENS_DEN 8383
Definition at line 72 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_R_SENS_NUM 18271
Definition at line 71 of file imu_drotek_10dof_v2.h.
#define IMU_GYRO_R_SIGN 1
Definition at line 48 of file imu_drotek_10dof_v2.h.
#define IMU_MAG_X_SIGN 1
Definition at line 41 of file imu_drotek_10dof_v2.h.
#define IMU_MAG_Y_SIGN 1
Definition at line 42 of file imu_drotek_10dof_v2.h.
#define IMU_MAG_Z_SIGN 1
Definition at line 43 of file imu_drotek_10dof_v2.h.
Function Documentation
bool_t imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void * mpu)
callback function to configure hmc5883 mag
Returns
TRUE if mag configuration finished
Definition at line 152 of file imu_drotek_10dof_v2.c.
References FALSE, ImuDrotek2::hmc, hmc58xx_start_configure(), imu_drotek2, Hmc58xx::initialized, and TRUE.
Referenced by imu_impl_init().
void imu_drotek2_event (void)
Definition at line 109 of file imu_drotek_10dof_v2.c.
References Imu::accel_unscaled, ImuDrotek2::accel_valid, Hmc58xx::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Hmc58xx::data_available, Mpu60x0_I2c::data_rates, FALSE, Imu::gyro_unscaled, ImuDrotek2::gyro_valid, ImuDrotek2::hmc, hmc58xx_event(), imu, imu_drotek2, Imu::mag_unscaled, ImuDrotek2::mag_valid, ImuDrotek2::mpu, mpu60x0_i2c_event(), Int16Rates::p, Int32Rates::p, Int16Rates::q, Int32Rates::q, Int16Rates::r, Int32Rates::r, Mpu60x0_I2c::rates, RATES_COPY, TRUE, Mpu60x0_I2c::vect, Hmc58xx::vect, VECT3_COPY, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
static void ImuEvent (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 117 of file imu_drotek_10dof_v2.h.
References ImuDrotek2::accel_valid, FALSE, ImuDrotek2::gyro_valid, imu_drotek2, imu_drotek2_event(), and ImuDrotek2::mag_valid.
Variable Documentation
struct ImuDrotek2 imu_drotek2
Definition at line 68 of file imu_drotek_10dof_v2.c.
Referenced by imu_drotek2_configure_mag_slave(), imu_drotek2_event(), imu_periodic(), and ImuEvent().