Paparazzi UAS: sw/airborne/subsystems/imu/imu_px4fmu.h File Reference
imu_px4fmu.h File Reference
Driver for the PX4FMU SPI1 for the MPU6000 and I2C2 for the HMC5883.
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "subsystems/imu/imu_mpu60x0_defaults.h"
#include "peripherals/mpu60x0_spi.h"
#include "peripherals/hmc58xx.h"
Data Structures
struct ImuPx4fmu
Macros
#define IMU_GYRO_P_SIGN 1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define IMU_MAG_X_SIGN 1
#define IMU_MAG_Y_SIGN 1
#define IMU_MAG_Z_SIGN 1
Functions
void imu_px4fmu_event (void)
static void ImuEvent (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Variables
struct ImuPx4fmu imu_px4fmu
Detailed Description
Driver for the PX4FMU SPI1 for the MPU6000 and I2C2 for the HMC5883.
Definition in file imu_px4fmu.h.
Macro Definition Documentation
#define IMU_ACCEL_X_SIGN 1
Definition at line 44 of file imu_px4fmu.h.
#define IMU_ACCEL_Y_SIGN 1
Definition at line 45 of file imu_px4fmu.h.
#define IMU_ACCEL_Z_SIGN 1
Definition at line 46 of file imu_px4fmu.h.
#define IMU_GYRO_P_SIGN 1
Definition at line 39 of file imu_px4fmu.h.
#define IMU_GYRO_Q_SIGN 1
Definition at line 40 of file imu_px4fmu.h.
#define IMU_GYRO_R_SIGN 1
Definition at line 41 of file imu_px4fmu.h.
#define IMU_MAG_X_SIGN 1
Definition at line 49 of file imu_px4fmu.h.
#define IMU_MAG_Y_SIGN 1
Definition at line 50 of file imu_px4fmu.h.
#define IMU_MAG_Z_SIGN 1
Definition at line 51 of file imu_px4fmu.h.
Function Documentation
void imu_px4fmu_event (void)
Definition at line 95 of file imu_px4fmu.c.
References Imu::accel_unscaled, ImuPx4fmu::accel_valid, Hmc58xx::data, Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Hmc58xx::data_available, Mpu60x0_Spi::data_rates, FALSE, Imu::gyro_unscaled, ImuPx4fmu::gyro_valid, ImuPx4fmu::hmc, hmc58xx_event(), imu, imu_px4fmu, Imu::mag_unscaled, ImuPx4fmu::mag_valid, ImuPx4fmu::mpu, mpu60x0_spi_event(), Int16Rates::p, Int16Rates::q, Int16Rates::r, Mpu60x0_Spi::rates, RATES_ASSIGN, TRUE, Mpu60x0_Spi::vect, Hmc58xx::vect, VECT3_ASSIGN, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
static void ImuEvent (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 67 of file imu_px4fmu.h.
References ImuPx4fmu::accel_valid, FALSE, ImuPx4fmu::gyro_valid, imu_px4fmu, imu_px4fmu_event(), and ImuPx4fmu::mag_valid.
Variable Documentation
struct ImuPx4fmu imu_px4fmu
Definition at line 66 of file imu_px4fmu.c.
Referenced by imu_periodic(), imu_px4fmu_event(), and ImuEvent().