Paparazzi UAS: sw/airborne/subsystems/imu/imu_gl1.c File Reference
imu_gl1.c File Reference
Driver for I2C IMU using L3G4200, ADXL345, HMC5883 and BMP085.
#include "subsystems/imu.h"
#include "mcu_periph/i2c.h"
Macros
#define GL1_ACCEL_RATE ADXL345_RATE_50HZ
adxl345 accelerometer output rate, lowpass is set to half of rate
#define GL1_GYRO_LOWPASS L3G4200_DLPF_1
gyro internal lowpass frequency
#define GL1_GYRO_SMPLRT L3G4200_DR_100Hz
gyro sample rate divider
#define L3G4200_SCALE L3G4200_SCALE_2000
Functions
void imu_impl_init (void)
void imu_periodic (void)
void imu_gl1_i2c_event (void)
Variables
struct ImuGL1I2c imu_gl1
Detailed Description
Driver for I2C IMU using L3G4200, ADXL345, HMC5883 and BMP085.
Definition in file imu_gl1.c.
Macro Definition Documentation
#define GL1_ACCEL_RATE ADXL345_RATE_50HZ
adxl345 accelerometer output rate, lowpass is set to half of rate
Definition at line 37 of file imu_gl1.c.
Referenced by imu_impl_init().
#define GL1_GYRO_LOWPASS L3G4200_DLPF_1
gyro internal lowpass frequency
Definition at line 49 of file imu_gl1.c.
Referenced by imu_impl_init().
#define GL1_GYRO_SMPLRT L3G4200_DR_100Hz
gyro sample rate divider
Definition at line 61 of file imu_gl1.c.
Referenced by imu_impl_init().
#define L3G4200_SCALE L3G4200_SCALE_2000
Definition at line 73 of file imu_gl1.c.
Referenced by imu_impl_init().
Function Documentation
void imu_gl1_i2c_event (void)
Definition at line 121 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, Imu::accel_unscaled, ImuGL1I2c::accel_valid, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, L3g4200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, L3g4200::data_available, FALSE, ImuGL1I2c::gyro_l3g, Imu::gyro_unscaled, ImuGL1I2c::gyro_valid, hmc58xx_event(), imu, imu_gl1, l3g4200_event(), ImuGL1I2c::mag_hmc, Imu::mag_unscaled, ImuGL1I2c::mag_valid, Int32Rates::p, Int32Rates::q, Int32Rates::r, L3g4200::rates, RATES_COPY, TRUE, Adxl345_I2c::vect, Hmc58xx::vect, VECT3_COPY, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
void imu_impl_init (void)
Todo:
drdy int handling for adxl345
Definition at line 79 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, ImuGL1I2c::accel_valid, ADXL345_ADDR, adxl345_i2c_init(), Adxl345_I2c::config, L3g4200::config, L3g4200Config::ctrl_reg1, L3g4200Config::ctrl_reg4, L3g4200Config::ctrl_reg5, FALSE, GL1_ACCEL_RATE, GL1_GYRO_LOWPASS, GL1_GYRO_SMPLRT, ImuGL1I2c::gyro_l3g, ImuGL1I2c::gyro_valid, HMC58XX_ADDR, hmc58xx_init(), HMC_TYPE_5883, L3G4200_ADDR_ALT, l3g4200_init(), L3G4200_SCALE, ImuGL1I2c::mag_hmc, ImuGL1I2c::mag_valid, Adxl345Config::rate, and Hmc58xx::type.
void imu_periodic (void)
Definition at line 110 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, adxl345_i2c_periodic(), ImuGL1I2c::gyro_l3g, hmc58xx_periodic(), imu_gl1, l3g4200_periodic(), and ImuGL1I2c::mag_hmc.
Variable Documentation
struct ImuGL1I2c imu_gl1
Definition at line 77 of file imu_gl1.c.
Referenced by imu_gl1_i2c_event(), imu_periodic(), and ImuEvent().