Paparazzi UAS: sw/airborne/subsystems/imu/imu_px4fmu.c File Reference
imu_px4fmu.c File Reference
Driver for the PX4FMU SPI1 for the MPU6000 and I2C2 for the HMC5883.
#include "subsystems/imu.h"
#include "mcu_periph/spi.h"
#include "peripherals/hmc58xx_regs.h"
Macros
#define PX4FMU_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
#define PX4FMU_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
Functions
void imu_impl_init (void)
void imu_periodic (void)
void imu_px4fmu_event (void)
Variables
struct ImuPx4fmu imu_px4fmu
Detailed Description
Driver for the PX4FMU SPI1 for the MPU6000 and I2C2 for the HMC5883.
Definition in file imu_px4fmu.c.
Macro Definition Documentation
#define PX4FMU_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
Definition at line 62 of file imu_px4fmu.c.
Referenced by imu_impl_init().
#define PX4FMU_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
Definition at line 57 of file imu_px4fmu.c.
Referenced by imu_impl_init().
Function Documentation
void imu_impl_init (void)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Todo:
drdy int handling for adxl345
Definition at line 68 of file imu_px4fmu.c.
References Mpu60x0Config::accel_range, ImuPx4fmu::accel_valid, Mpu60x0_Spi::config, Mpu60x0Config::dlpf_cfg, FALSE, Mpu60x0Config::gyro_range, ImuPx4fmu::gyro_valid, ImuPx4fmu::hmc, HMC58XX_ADDR, hmc58xx_init(), ImuPx4fmu::mag_valid, ImuPx4fmu::mpu, mpu60x0_spi_init(), PX4FMU_ACCEL_RANGE, PX4FMU_GYRO_RANGE, Mpu60x0Config::smplrt_div, spi1, and SPI_SLAVE2.
void imu_periodic (void)
Definition at line 87 of file imu_px4fmu.c.
References ImuPx4fmu::hmc, hmc58xx_periodic(), imu_px4fmu, ImuPx4fmu::mpu, and mpu60x0_spi_periodic().
void imu_px4fmu_event (void)
Definition at line 95 of file imu_px4fmu.c.
References Imu::accel_unscaled, ImuPx4fmu::accel_valid, Hmc58xx::data, Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Hmc58xx::data_available, Mpu60x0_Spi::data_rates, FALSE, Imu::gyro_unscaled, ImuPx4fmu::gyro_valid, ImuPx4fmu::hmc, hmc58xx_event(), imu, imu_px4fmu, Imu::mag_unscaled, ImuPx4fmu::mag_valid, ImuPx4fmu::mpu, mpu60x0_spi_event(), Int16Rates::p, Int16Rates::q, Int16Rates::r, Mpu60x0_Spi::rates, RATES_ASSIGN, TRUE, Mpu60x0_Spi::vect, Hmc58xx::vect, VECT3_ASSIGN, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
Variable Documentation
struct ImuPx4fmu imu_px4fmu
Definition at line 66 of file imu_px4fmu.c.
Referenced by imu_periodic(), imu_px4fmu_event(), and ImuEvent().