Paparazzi UAS: sw/airborne/subsystems/imu/imu_ardrone2_raw.h File Reference
imu_ardrone2_raw.h File Reference
IMU implementation for ardrone2-raw.
#include "subsystems/imu.h"
#include "generated/airframe.h"
#include "navdata.h"
Macros
#define IMU_MAG_X_SIGN 1
#define IMU_MAG_Y_SIGN 1
#define IMU_MAG_Z_SIGN 1
#define IMU_GYRO_P_SIGN 1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define IMU_GYRO_P_SENS 4.359
default gyro sensitivy and neutral from the datasheet MPU with 2000 deg/s
#define IMU_GYRO_P_SENS_NUM 4359
#define IMU_GYRO_P_SENS_DEN 1000
#define IMU_GYRO_Q_SENS 4.359
#define IMU_GYRO_Q_SENS_NUM 4359
#define IMU_GYRO_Q_SENS_DEN 1000
#define IMU_GYRO_R_SENS 4.359
#define IMU_GYRO_R_SENS_NUM 4359
#define IMU_GYRO_R_SENS_DEN 1000
#define IMU_GYRO_P_NEUTRAL 0
#define IMU_GYRO_Q_NEUTRAL 0
#define IMU_GYRO_R_NEUTRAL 0
#define IMU_ACCEL_X_SENS 19.5
default accel sensitivy from the datasheet 512 LSB/g
#define IMU_ACCEL_X_SENS_NUM 195
#define IMU_ACCEL_X_SENS_DEN 10
#define IMU_ACCEL_Y_SENS 19.5
#define IMU_ACCEL_Y_SENS_NUM 195
#define IMU_ACCEL_Y_SENS_DEN 10
#define IMU_ACCEL_Z_SENS 19.5
#define IMU_ACCEL_Z_SENS_NUM 195
#define IMU_ACCEL_Z_SENS_DEN 10
#define IMU_ACCEL_X_NEUTRAL 2048
#define IMU_ACCEL_Y_NEUTRAL 2048
#define IMU_ACCEL_Z_NEUTRAL 2048
#define IMU_MAG_X_SENS 16.0
#define IMU_MAG_X_SENS_NUM 16
#define IMU_MAG_X_SENS_DEN 1
#define IMU_MAG_Y_SENS 16.0
#define IMU_MAG_Y_SENS_NUM 16
#define IMU_MAG_Y_SENS_DEN 1
#define IMU_MAG_Z_SENS 16.0
#define IMU_MAG_Z_SENS_NUM 16
#define IMU_MAG_Z_SENS_DEN 1
#define IMU_MAG_X_NEUTRAL 0
#define IMU_MAG_Y_NEUTRAL 0
#define IMU_MAG_Z_NEUTRAL 0
#define ImuEvent(_gyro_handler, _accel_handler, _mag_handler)
Functions
void navdata_event (void)
static void imu_ardrone2_event (void(*_gyro_handler)(void), void(*_accel_handler)(void), void(*_mag_handler)(void))
Detailed Description
IMU implementation for ardrone2-raw.
Definition in file imu_ardrone2_raw.h.
Macro Definition Documentation
#define IMU_ACCEL_X_NEUTRAL 2048
Definition at line 86 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_X_SENS 19.5
default accel sensitivy from the datasheet 512 LSB/g
Definition at line 74 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_X_SENS_DEN 10
Definition at line 76 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_X_SENS_NUM 195
Definition at line 75 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_X_SIGN 1
Definition at line 45 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Y_NEUTRAL 2048
Definition at line 87 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Y_SENS 19.5
Definition at line 77 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Y_SENS_DEN 10
Definition at line 79 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Y_SENS_NUM 195
Definition at line 78 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Y_SIGN 1
Definition at line 46 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Z_NEUTRAL 2048
Definition at line 88 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Z_SENS 19.5
Definition at line 80 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Z_SENS_DEN 10
Definition at line 82 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Z_SENS_NUM 195
Definition at line 81 of file imu_ardrone2_raw.h.
#define IMU_ACCEL_Z_SIGN 1
Definition at line 47 of file imu_ardrone2_raw.h.
#define IMU_GYRO_P_NEUTRAL 0
Definition at line 65 of file imu_ardrone2_raw.h.
#define IMU_GYRO_P_SENS 4.359
default gyro sensitivy and neutral from the datasheet MPU with 2000 deg/s
Definition at line 54 of file imu_ardrone2_raw.h.
#define IMU_GYRO_P_SENS_DEN 1000
Definition at line 56 of file imu_ardrone2_raw.h.
#define IMU_GYRO_P_SENS_NUM 4359
Definition at line 55 of file imu_ardrone2_raw.h.
#define IMU_GYRO_P_SIGN 1
Definition at line 40 of file imu_ardrone2_raw.h.
#define IMU_GYRO_Q_NEUTRAL 0
Definition at line 66 of file imu_ardrone2_raw.h.
#define IMU_GYRO_Q_SENS 4.359
Definition at line 57 of file imu_ardrone2_raw.h.
#define IMU_GYRO_Q_SENS_DEN 1000
Definition at line 59 of file imu_ardrone2_raw.h.
#define IMU_GYRO_Q_SENS_NUM 4359
Definition at line 58 of file imu_ardrone2_raw.h.
#define IMU_GYRO_Q_SIGN 1
Definition at line 41 of file imu_ardrone2_raw.h.
#define IMU_GYRO_R_NEUTRAL 0
Definition at line 67 of file imu_ardrone2_raw.h.
#define IMU_GYRO_R_SENS 4.359
Definition at line 60 of file imu_ardrone2_raw.h.
#define IMU_GYRO_R_SENS_DEN 1000
Definition at line 62 of file imu_ardrone2_raw.h.
#define IMU_GYRO_R_SENS_NUM 4359
Definition at line 61 of file imu_ardrone2_raw.h.
#define IMU_GYRO_R_SIGN 1
Definition at line 42 of file imu_ardrone2_raw.h.
#define IMU_MAG_X_NEUTRAL 0
Definition at line 104 of file imu_ardrone2_raw.h.
Referenced by imu_init().
#define IMU_MAG_X_SENS 16.0
Definition at line 92 of file imu_ardrone2_raw.h.
#define IMU_MAG_X_SENS_DEN 1
Definition at line 94 of file imu_ardrone2_raw.h.
#define IMU_MAG_X_SENS_NUM 16
Definition at line 93 of file imu_ardrone2_raw.h.
#define IMU_MAG_X_SIGN 1
Definition at line 35 of file imu_ardrone2_raw.h.
#define IMU_MAG_Y_NEUTRAL 0
Definition at line 105 of file imu_ardrone2_raw.h.
Referenced by imu_init().
#define IMU_MAG_Y_SENS 16.0
Definition at line 95 of file imu_ardrone2_raw.h.
#define IMU_MAG_Y_SENS_DEN 1
Definition at line 97 of file imu_ardrone2_raw.h.
#define IMU_MAG_Y_SENS_NUM 16
Definition at line 96 of file imu_ardrone2_raw.h.
#define IMU_MAG_Y_SIGN 1
Definition at line 36 of file imu_ardrone2_raw.h.
#define IMU_MAG_Z_NEUTRAL 0
Definition at line 106 of file imu_ardrone2_raw.h.
Referenced by imu_init().
#define IMU_MAG_Z_SENS 16.0
Definition at line 98 of file imu_ardrone2_raw.h.
#define IMU_MAG_Z_SENS_DEN 1
Definition at line 100 of file imu_ardrone2_raw.h.
#define IMU_MAG_Z_SENS_NUM 16
Definition at line 99 of file imu_ardrone2_raw.h.
#define IMU_MAG_Z_SIGN 1
Definition at line 37 of file imu_ardrone2_raw.h.
#define ImuEvent (_gyro_handler, _accel_handler, _mag_handler)
Value:
{  \
    imu_ardrone2_event(_gyro_handler, _accel_handler, _mag_handler); \
}
Definition at line 130 of file imu_ardrone2_raw.h.
Function Documentation
static void imu_ardrone2_event (void(*)(void) _gyro_handler, void(*)(void) _accel_handler, void(*)(void) _mag_handler) inline static
Definition at line 113 of file imu_ardrone2_raw.h.
References Imu::accel_unscaled, measures_t::ax, measures_t::ay, measures_t::az, FALSE, Imu::gyro_unscaled, imu, Imu::mag_unscaled, measures_t::mx, measures_t::my, measures_t::mz, navdata, navdata_event(), navdata_imu_available, navdata_update(), RATES_ASSIGN, TRUE, VECT3_ASSIGN, measures_t::vx, measures_t::vy, and measures_t::vz.
void navdata_event (void)
Definition at line 39 of file imu_ardrone2_raw.c.
Referenced by imu_ardrone2_event().