Paparazzi UAS: sw/airborne/boards/navgo/imu_navgo.c File Reference
imu_navgo.c File Reference
Driver for the IMU on the NavGo board.
#include <math.h>
#include "imu_navgo.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define NAVGO_ACCEL_RATE ADXL345_RATE_25HZ
#define NAVGO_GYRO_LOWPASS ITG3200_DLPF_10HZ
#define NAVGO_GYRO_SMPLRT_DIV 1
Functions
void imu_impl_init (void)
void imu_periodic (void)
void imu_navgo_downlink_raw (void)
void imu_navgo_event (void)
Variables
struct ImuNavgo imu_navgo
Detailed Description
Driver for the IMU on the NavGo board.
Gyroscope: Invensense ITG-3200
Accelerometer: Analog Devices ADXL345
Magnetometer: Honeywell HMC5883L
Definition in file imu_navgo.c.
Macro Definition Documentation
#define NAVGO_ACCEL_RATE ADXL345_RATE_25HZ
Definition at line 45 of file imu_navgo.c.
Referenced by imu_impl_init(), and imu_periodic().
#define NAVGO_GYRO_LOWPASS ITG3200_DLPF_10HZ
Definition at line 51 of file imu_navgo.c.
Referenced by imu_impl_init().
#define NAVGO_GYRO_SMPLRT_DIV 1
Definition at line 52 of file imu_navgo.c.
Referenced by imu_impl_init().
Function Documentation
void imu_impl_init (void)
Definition at line 65 of file imu_navgo.c.
References ImuNavgo::acc_valid, ImuNavgo::adxl, ADXL345_ADDR_ALT, adxl345_i2c_init(), Adxl345_I2c::config, Itg3200::config, Itg3200Config::dlpf_cfg, FALSE, ImuNavgo::gyr_valid, ImuNavgo::hmc, HMC58XX_ADDR, hmc58xx_init(), imu_navgo, InitMedianFilterRatesInt, InitMedianFilterVect3Int, ImuNavgo::itg, ITG3200_ADDR_ALT, itg3200_init(), ImuNavgo::mag_valid, median_mag, NAVGO_ACCEL_RATE, NAVGO_GYRO_LOWPASS, NAVGO_GYRO_SMPLRT_DIV, Adxl345Config::rate, and Itg3200Config::smplrt_div.
void imu_navgo_downlink_raw (void)
Definition at line 114 of file imu_navgo.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Imu::mag_unscaled, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_navgo_event (void)
Definition at line 121 of file imu_navgo.c.
References ImuNavgo::acc_valid, Imu::accel_unscaled, ImuNavgo::adxl, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, Itg3200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, Itg3200::data_available, FALSE, ImuNavgo::gyr_valid, Imu::gyro_unscaled, ImuNavgo::hmc, hmc58xx_event(), imu, imu_navgo, ImuNavgo::itg, itg3200_event(), Imu::mag_unscaled, ImuNavgo::mag_valid, median_mag, Int32Rates::p, Int32Rates::q, Int32Rates::r, Itg3200::rates, RATES_ASSIGN, TRUE, UpdateMedianFilterRatesInt, UpdateMedianFilterVect3Int, Adxl345_I2c::vect, Hmc58xx::vect, VECT3_ASSIGN, VECT3_COPY, Int16Vect3::x, Int16Vect3::y, and Int16Vect3::z.
Referenced by ImuEvent().
void imu_periodic (void)
Definition at line 96 of file imu_navgo.c.
References ImuNavgo::adxl, adxl345_i2c_periodic(), ImuNavgo::hmc, hmc58xx_periodic(), imu_navgo, ImuNavgo::itg, itg3200_periodic(), NAVGO_ACCEL_RATE, and PERIODIC_FREQUENCY.
Variable Documentation
struct ImuNavgo imu_navgo
Definition at line 63 of file imu_navgo.c.
Referenced by imu_impl_init(), imu_navgo_event(), imu_periodic(), and ImuEvent().