Paparazzi UAS: sw/airborne/subsystems/ins/ins_alt_float.c File Reference
ins_alt_float.c File Reference
Filters altitude and climb rate for fixedwings.
#include "subsystems/ins/ins_alt_float.h"
#include "subsystems/abi.h"
#include <inttypes.h>
#include <math.h>
#include "state.h"
#include "subsystems/gps.h"
#include "subsystems/nav.h"
#include "generated/airframe.h"
#include "subsystems/sensors/baro.h"
#include "math/pprz_isa.h"
Macros
#define INS_BARO_ID BARO_BOARD_SENDER_ID
#define ALT_KALMAN_ENABLED FALSE
#define GPS_DT 0.25
#define GPS_SIGMA2 1.
#define GPS_R 2.
#define BARO_DT 0.1
Functions
static void baro_cb (uint8_t sender_id, const float *pressure)
void ins_init ()
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
void ins_propagate ()
Propagation.
void ins_update_baro ()
Update INS state with barometer measurements.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_update_sonar ()
Update INS state with sonar measurements.
void alt_kalman_reset (void)
void alt_kalman_init (void)
void alt_kalman (float z_meas)
Variables
float ins_alt
estimated altitude above MSL in meters
float ins_alt_dot
estimated vertical speed in m/s (positive-up)
float ins_qfe
bool_t ins_baro_initialized
float ins_baro_alt
abi_event baro_ev
bool_t alt_kalman_enabled
static float p [2][2]
Detailed Description
Filters altitude and climb rate for fixedwings.
Definition in file ins_alt_float.c.
Macro Definition Documentation
#define ALT_KALMAN_ENABLED FALSE
Definition at line 169 of file ins_alt_float.c.
Referenced by alt_kalman_init().
#define BARO_DT 0.1
Definition at line 178 of file ins_alt_float.c.
Referenced by alt_kalman().
#define GPS_DT 0.25
Definition at line 173 of file ins_alt_float.c.
Referenced by alt_kalman().
#define GPS_R 2.
Definition at line 176 of file ins_alt_float.c.
Referenced by alt_kalman().
#define GPS_SIGMA2 1.
Definition at line 175 of file ins_alt_float.c.
Referenced by alt_kalman().
#define INS_BARO_ID BARO_BOARD_SENDER_ID
Definition at line 59 of file ins_alt_float.c.
Referenced by ins_init().
Function Documentation
void alt_kalman (float z_meas)
Definition at line 194 of file ins_alt_float.c.
References alt_baro_enabled, BARO_AMSYS_DT, baro_amsys_enabled, baro_amsys_r, baro_amsys_sigma2, BARO_BMP_DT, baro_bmp_enabled, baro_bmp_r, baro_bmp_sigma2, BARO_DT, BARO_ETS_DT, baro_ets_enabled, baro_ets_r, baro_ets_sigma2, baro_MS5534A_r, baro_MS5534A_sigma2, BARO_MS5611_DT, baro_ms5611_enabled, baro_ms5611_r, baro_ms5611_sigma2, BARO_SIM_DT, DefaultChannel, DefaultDevice, GPS_DT, GPS_R, GPS_SIGMA2, ins_alt, ins_alt_dot, and R.
void alt_kalman_init (void)
Definition at line 189 of file ins_alt_float.c.
References ALT_KALMAN_ENABLED, and alt_kalman_reset().
Referenced by ins_init().
void alt_kalman_reset (void)
Definition at line 182 of file ins_alt_float.c.
Referenced by alt_kalman_init(), and baro_cb().
static void baro_cb (uint8_t sender_id, const float * pressure) static
Definition at line 104 of file ins_alt_float.c.
References UtmCoor_f::alt, alt_kalman_reset(), EstimatorSetAlt, FALSE, ground_alt, ins, ins_alt, ins_alt_dot, pprz_isa_height_of_pressure(), stateGetPositionUtm_f(), stateGetSpeedNed_f(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), TRUE, UTM_COPY, Ins::vf_realign, and NedCoor_f::z.
Referenced by ins_init().
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 66 of file ins_alt_float.c.
References alt_kalman_init(), baro_cb(), EstimatorSetAlt, FALSE, ground_alt, ins, INS_BARO_ID, INS_RUNNING, nav_utm_east0, nav_utm_north0, nav_utm_zone0, stateSetLocalUtmOrigin_f(), stateSetPositionUtm_f(), Ins::status, and Ins::vf_realign.
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 89 of file ins_alt_float.c.
Referenced by sensors_task().
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 98 of file ins_alt_float.c.
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 92 of file ins_alt_float.c.
Referenced by track_event().
void ins_realign_v (float z)
INS vertical realign.
Parameters
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 95 of file ins_alt_float.c.
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global #baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 101 of file ins_alt_float.c.
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Definition at line 134 of file ins_alt_float.c.
Referenced by on_gps_event(), and on_gps_solution().
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 163 of file ins_alt_float.c.
Referenced by navdata_update().
Variable Documentation
bool_t alt_kalman_enabled
Definition at line 166 of file ins_alt_float.c.
Referenced by ins_update_gps().
abi_event baro_ev
Definition at line 61 of file ins_alt_float.c.
float ins_alt
estimated altitude above MSL in meters
Definition at line 46 of file ins_alt_float.c.
Referenced by alt_kalman(), baro_cb(), and ins_update_gps().
float ins_alt_dot
estimated vertical speed in m/s (positive-up)
Definition at line 47 of file ins_alt_float.c.
Referenced by alt_kalman(), baro_cb(), and ins_update_gps().
float ins_baro_alt
Definition at line 55 of file ins_alt_float.c.
bool_t ins_baro_initialized
Definition at line 54 of file ins_alt_float.c.
float ins_qfe
Definition at line 53 of file ins_alt_float.c.
float p[2][2] static
Definition at line 180 of file ins_alt_float.c.
Referenced by baro_apply_calibration(), bef(), bmp085_compensated_pressure(), mag_calc(), navdata_update(), provide_attitude_and_rates(), sirf_parse_2(), sirf_parse_41(), and stabilization_attitude_init().