Paparazzi UAS: sw/airborne/subsystems/ins/ins_int.c File Reference
ins_int.c File Reference
INS for rotorcrafts combining vertical and horizontal filters.
#include "subsystems/ins/ins_int.h"
#include "subsystems/abi.h"
#include "subsystems/imu.h"
#include "subsystems/gps.h"
#include "generated/airframe.h"
#include "subsystems/ins/vf_float.h"
#include "math/pprz_geodetic_int.h"
#include "math/pprz_isa.h"
#include "generated/flight_plan.h"
Macros
#define USE_INS_NAV_INIT TRUE
#define INS_BARO_ID BARO_BOARD_SENDER_ID
default barometer to use in INS
Functions
static void baro_cb (uint8_t sender_id, const float *pressure)
static void ins_init_origin_from_flightplan (void)
initialize the local origin (ltp_def) from flight plan position
static void ins_ned_to_state (void)
copy position and speed to state interface
void ins_init (void)
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
void ins_propagate ()
Propagation.
void ins_update_baro ()
Update INS state with barometer measurements.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_update_sonar ()
Update INS state with sonar measurements.
Variables
abi_event baro_ev
struct InsInt ins_impl
global INS state
Detailed Description
INS for rotorcrafts combining vertical and horizontal filters.
Definition in file ins_int.c.
Macro Definition Documentation
#define INS_BARO_ID BARO_BOARD_SENDER_ID
default barometer to use in INS
Definition at line 86 of file ins_int.c.
Referenced by ins_init().
#define USE_INS_NAV_INIT TRUE
Definition at line 79 of file ins_int.c.
Function Documentation
static void baro_cb (uint8_t sender_id, const float * pressure) static
Definition at line 220 of file ins_int.c.
References ACCEL_BFP_OF_REAL, FALSE, ins, ins_impl, ins_ned_to_state(), InsArdrone2::ltp_accel, InsArdrone2::ltp_pos, InsArdrone2::ltp_speed, POS_BFP_OF_REAL, pprz_isa_height_of_pressure(), InsArdrone2::qfe, SPEED_BFP_OF_REAL, TRUE, Ins::vf_realign, vff_realign(), vff_update(), vff_update_baro(), vff_z, vff_zdot, vff_zdotdot, and NedCoor_i::z.
Referenced by ins_init().
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 125 of file ins_int.c.
References b2_hff_init(), baro_cb(), FALSE, gps, Ins::hf_realign, init_median_filter(), ins, INS_BARO_ID, ins_impl, ins_init_origin_from_flightplan(), ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, INT32_VECT3_ZERO, InsArdrone2::ltp_accel, InsArdrone2::ltp_initialized, InsArdrone2::ltp_pos, InsArdrone2::ltp_speed, GpsState::nb_channels, register_periodic_telemetry(), TRUE, UNINIT, Ins::vf_realign, vff_init(), xsens_configured, xsens_msg_statusword, xsens_status, and xsens_time_stamp.
static void ins_init_origin_from_flightplan (void) static
initialize the local origin (ltp_def) from flight plan position
Definition at line 368 of file ins_int.c.
References LlaCoor_i::alt, ecef_of_lla_i(), LtpDef_i::hmsl, ins_impl, INT32_RAD_OF_DEG, LlaCoor_i::lat, LlaCoor_i::lon, InsArdrone2::ltp_def, ltp_def_from_ecef_i(), and stateSetLocalOrigin_i().
Referenced by ins_init().
static void ins_ned_to_state (void) static
copy position and speed to state interface
Definition at line 386 of file ins_int.c.
References ins_impl, InsArdrone2::ltp_accel, InsArdrone2::ltp_pos, InsArdrone2::ltp_speed, stateSetAccelNed_i(), stateSetPositionNed_i(), and stateSetSpeedNed_i().
Referenced by baro_cb(), ins_propagate(), and ins_update_gps().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 168 of file ins_int.c.
References ins, ins_impl, INS_RUNNING, InsArdrone2::ltp_initialized, and Ins::status.
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 187 of file ins_int.c.
References Imu::accel, ACCEL_BFP_OF_REAL, ACCEL_FLOAT_OF_BFP, b2_hff_propagate(), Imu::body_to_imu_rmat, imu, ins_impl, ins_ned_to_state(), INT32_RMAT_TRANSP_VMULT, InsArdrone2::ltp_accel, InsArdrone2::ltp_pos, InsArdrone2::ltp_speed, POS_BFP_OF_REAL, SPEED_BFP_OF_REAL, stateGetNedToBodyRMat_i(), vff_propagate(), vff_z, vff_zdot, vff_zdotdot, NedCoor_i::x, Int32Vect3::x, NedCoor_i::y, Int32Vect3::y, NedCoor_i::z, and Int32Vect3::z.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 178 of file ins_int.c.
void ins_realign_v (float z)
INS vertical realign.
Parameters
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 183 of file ins_int.c.
References vff_realign().
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global #baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 245 of file ins_int.c.
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Todo:
maybe use gps.ned_vel directly??
Definition at line 249 of file ins_int.c.
References LlaCoor_i::alt, UtmCoor_f::alt, alt_kalman_enabled, b2_hff_realign(), b2_hff_update_gps(), UtmCoor_f::east, UtmCoor_i::east, GpsState::ecef_pos, GpsState::ecef_vel, EstimatorSetAlt, FALSE, GpsState::fix, gps, GPS_FIX_3D, Ins::hf_realign, GpsState::hmsl, LtpDef_i::hmsl, ins, ins_alt, ins_alt_dot, ins_impl, ins_ned_to_state(), INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_SPEED_OF_CM_S_DEN, INT32_SPEED_OF_CM_S_NUM, INT32_VECT2_SCALE_2, LtpDef_i::lla, GpsState::lla_pos, InsArdrone2::ltp_def, ltp_def_from_ecef_i(), InsArdrone2::ltp_initialized, InsArdrone2::ltp_pos, InsArdrone2::ltp_speed, nav_utm_zone0, ned_of_ecef_point_i(), ned_of_ecef_vect_i(), GpsState::ned_vel, UtmCoor_f::north, UtmCoor_i::north, stateSetLocalOrigin_i(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), TRUE, GpsState::utm_pos, VECT2_ASSIGN, VECT2_SDIV, NedCoor_i::x, NedCoor_i::y, NedCoor_i::z, and UtmCoor_f::zone.
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 315 of file ins_int.c.
References DefaultChannel, DefaultDevice, ins_impl, sonar_meas, stabilization_cmd, update_median_filter(), variance_float(), vff_offset, vff_update_alt_conf(), and vff_update_offset().
Variable Documentation
abi_event baro_ev
Definition at line 88 of file ins_int.c.
struct InsInt ins_impl
global INS state
Definition at line 91 of file ins_int.c.