Paparazzi UAS: sw/airborne/boards/lisa_m/baro_board.c File Reference
baro_board.c File Reference
Baro board interface for Bosch BMP085 on LisaM I2C2 with EOC check.
#include "std.h"
#include "subsystems/sensors/baro.h"
#include "peripherals/bmp085.h"
#include "peripherals/bmp085_regs.h"
#include <libopencm3/stm32/gpio.h>
#include "subsystems/abi.h"
#include "led.h"
Functions
static bool_t baro_eoc (void)
void baro_init (void)
void baro_periodic (void)
void baro_event (void)
Variables
struct Bmp085 baro_bmp085
Detailed Description
Baro board interface for Bosch BMP085 on LisaM I2C2 with EOC check.
Definition in file baro_board.c.
Function Documentation
static bool_t baro_eoc (void) static
Definition at line 39 of file baro_board.c.
References gpio_get().
Referenced by baro_init().
void baro_event (void)
Definition at line 71 of file baro_board.c.
References baro_bmp085, BARO_BOARD_SENDER_ID, bb_ms5611, bmp085_event(), Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_I2c::data_available, Bmp085::data_available, DefaultChannel, DefaultDevice, FALSE, fbaroms, ftempms, LED_TOGGLE, ms5611_i2c_event(), sys_time::nb_sec, Ms5611Data::pressure, Bmp085::pressure, and Ms5611Data::temperature.
void baro_init (void)
Definition at line 44 of file baro_board.c.
References baro_bmp085, baro_eoc(), bmp085_init(), BMP085_SLAVE_ADDR, Bmp085::eoc, gpio_clear(), and LED_OFF.
void baro_periodic (void)
Definition at line 60 of file baro_board.c.
References baro_bmp085, bmp085_periodic(), bmp085_read_eeprom_calib(), and Bmp085::initialized.
Variable Documentation
struct Bmp085 baro_bmp085
Definition at line 37 of file baro_board.c.
Referenced by baro_event(), baro_init(), and baro_periodic().