Paparazzi UAS: sw/airborne/modules/mission/mission.h File Reference
mission.h File Reference
mission planner library
#include "std.h"
#include "math/pprz_geodetic_float.h"
Data Structures
struct _mission_wp
struct _mission_circle
struct _mission_segment
struct _mission_path
struct _mission_element
struct _mission
Macros
#define MISSION_PATH_NB 5
#define MISSION_ELEMENT_NB 20
Enumerations
enum MissionType {
MissionWP, MissionCircle, MissionSegment, MissionPath,
MissionSurvey, MissionEight, MissionOval
}
enum MissionInsertMode { Append, Prepend, ReplaceCurrent, ReplaceAll }
Functions
void mission_init (void)
Init mission structure.
bool_t mission_insert (enum MissionInsertMode insert, struct _mission_element *element)
Insert a mission element according to the insertion mode.
struct _mission_element * mission_get (void)
Get current mission element.
int mission_run ()
Run mission.
int mission_parse_GOTO_WP (void)
Parsing functions called when a mission message is received.
int mission_parse_GOTO_WP_LLA (void)
int mission_parse_CIRCLE (void)
int mission_parse_CIRCLE_LLA (void)
int mission_parse_SEGMENT (void)
int mission_parse_SEGMENT_LLA (void)
int mission_parse_PATH (void)
int mission_parse_PATH_LLA (void)
int mission_parse_SURVEY (void)
int mission_parse_SURVEY_LLA (void)
int mission_parse_GOTO_MISSION (void)
int mission_parse_NEXT_MISSION (void)
int mission_parse_END_MISSION (void)
Variables
struct _mission mission
Detailed Description
mission planner library
Provide the generic interface for the mission control Handle the parsing of datalink messages
Definition in file mission.h.
Macro Definition Documentation
#define MISSION_ELEMENT_NB 20
Definition at line 85 of file mission.h.
Referenced by mission_insert(), mission_parse_GOTO_MISSION(), and mission_parse_NEXT_MISSION().
#define MISSION_PATH_NB 5
Definition at line 67 of file mission.h.
Referenced by mission_parse_PATH(), and mission_parse_PATH_LLA().
Enumeration Type Documentation
enum MissionInsertMode
Enumerator:
Append
add at the last position
Prepend
add before the current element
ReplaceCurrent
replace current element
ReplaceAll
remove all elements and add the new one
Definition at line 46 of file mission.h.
enum MissionType
Enumerator:
MissionWP
MissionCircle
MissionSegment
MissionPath
MissionSurvey
MissionEight
MissionOval
Definition at line 36 of file mission.h.
Function Documentation
struct _mission_element* mission_get (void) read
Get current mission element.
Returns
return a pointer to the next mission element or NULL if no more elements
Definition at line 79 of file mission.c.
References _mission::current_idx, _mission::elements, _mission::insert_idx, and mission.
Referenced by mission_run().
void mission_init (void)
Init mission structure.
Definition at line 38 of file mission.c.
References _mission::current_idx, _mission::element_time, _mission::insert_idx, and mission.
bool_t mission_insert (enum MissionInsertMode insert, struct _mission_element * element)
Insert a mission element according to the insertion mode.
Parameters
insert insertion mode
element mission element structure
Returns
return TRUE if insertion is succesful, FALSE otherwise
Definition at line 44 of file mission.c.
References Append, _mission::current_idx, _mission::elements, FALSE, _mission::insert_idx, mission, MISSION_ELEMENT_NB, Prepend, ReplaceAll, ReplaceCurrent, and TRUE.
Referenced by mission_parse_CIRCLE(), mission_parse_CIRCLE_LLA(), mission_parse_GOTO_WP(), mission_parse_GOTO_WP_LLA(), mission_parse_PATH(), mission_parse_PATH_LLA(), mission_parse_SEGMENT(), and mission_parse_SEGMENT_LLA().
int mission_parse_CIRCLE (void)
Definition at line 118 of file mission.c.
References _mission_circle::center, dl_buffer, _mission_element::duration, _mission_element::element, FALSE, _mission_element::mission_circle, mission_insert(), MissionCircle, _mission_circle::radius, _mission_element::type, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
int mission_parse_CIRCLE_LLA (void)
Definition at line 134 of file mission.c.
References dl_buffer, _mission_element::duration, _mission_element::element, FALSE, _mission_element::mission_circle, mission_insert(), MissionCircle, _mission_circle::radius, and _mission_element::type.
int mission_parse_END_MISSION (void)
Definition at line 244 of file mission.c.
References _mission::current_idx, dl_buffer, FALSE, _mission::insert_idx, mission, and TRUE.
int mission_parse_GOTO_MISSION (void)
Definition at line 222 of file mission.c.
References _mission::current_idx, dl_buffer, FALSE, mission, MISSION_ELEMENT_NB, and TRUE.
int mission_parse_GOTO_WP (void)
Parsing functions called when a mission message is received.
Definition at line 92 of file mission.c.
References dl_buffer, _mission_element::duration, _mission_element::element, FALSE, mission_insert(), _mission_element::mission_wp, MissionWP, _mission_element::type, _mission_wp::wp, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
int mission_parse_GOTO_WP_LLA (void)
Definition at line 107 of file mission.c.
References dl_buffer, FALSE, mission_insert(), MissionWP, and _mission_element::type.
int mission_parse_NEXT_MISSION (void)
Definition at line 234 of file mission.c.
References _mission::current_idx, dl_buffer, FALSE, _mission::insert_idx, mission, MISSION_ELEMENT_NB, and TRUE.
int mission_parse_PATH (void)
Definition at line 177 of file mission.c.
References dl_buffer, _mission_element::duration, _mission_element::element, FALSE, mission_insert(), _mission_element::mission_path, MISSION_PATH_NB, MissionPath, _mission_path::nb, _mission_path::path, _mission_path::path_idx, _mission_element::type, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
int mission_parse_PATH_LLA (void)
Definition at line 207 of file mission.c.
References dl_buffer, _mission_element::duration, _mission_element::element, FALSE, mission_insert(), _mission_element::mission_path, MISSION_PATH_NB, MissionPath, _mission_path::nb, _mission_path::path_idx, and _mission_element::type.
int mission_parse_SEGMENT (void)
Definition at line 147 of file mission.c.
References dl_buffer, _mission_element::duration, _mission_element::element, FALSE, _mission_segment::from, mission_insert(), _mission_element::mission_segment, MissionSegment, _mission_segment::to, _mission_element::type, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
int mission_parse_SEGMENT_LLA (void)
Definition at line 165 of file mission.c.
References dl_buffer, _mission_element::duration, FALSE, mission_insert(), MissionSegment, and _mission_element::type.
int mission_parse_SURVEY (void)
int mission_parse_SURVEY_LLA (void)
int mission_run ()
Run mission.
This function should be implemented into a dedicated file since navigation functions are different for different firmwares
Currently, this function should be called from the flight plan
Returns
return TRUE when the mission is running, FALSE when it is finished
Definition at line 105 of file mission_fw_nav.c.
References _mission::current_idx, dt_navigation, _mission_element::duration, _mission_element::element, _mission::element_time, FALSE, mission, _mission_element::mission_circle, mission_get(), mission_nav_circle(), mission_nav_path(), mission_nav_segment(), mission_nav_wp(), _mission_element::mission_path, _mission_element::mission_segment, _mission_element::mission_wp, MissionCircle, MissionPath, MissionSegment, MissionWP, TRUE, and _mission_element::type.
Variable Documentation
struct _mission mission
Definition at line 35 of file mission.c.
Referenced by mission_get(), mission_init(), mission_insert(), mission_parse_END_MISSION(), mission_parse_GOTO_MISSION(), mission_parse_NEXT_MISSION(), and mission_run().