Paparazzi UAS: sw/airborne/modules/mission/mission_fw_nav.c File Reference
mission_fw_nav.c File Reference
mission navigation for fixedwing aircraft
#include <stdio.h>
#include "modules/mission/mission.h"
#include "firmwares/fixedwing/autopilot.h"
#include "subsystems/nav.h"
Functions
static bool_t mission_nav_wp (struct _mission_wp *wp)
Navigation function to a single waypoint.
static bool_t mission_nav_circle (struct _mission_circle *circle)
Navigation function on a circle.
static bool_t mission_nav_segment (struct _mission_segment *segment)
Navigation function along a segment.
static bool_t mission_nav_path (struct _mission_path *path)
Navigation function along a path.
int mission_run ()
Run mission.
Variables
const float dt_navigation = 1.0 / ((float)NAVIGATION_FREQUENCY)
struct EnuCoor_f last_wp = { 0., 0., 0. }
Detailed Description
mission navigation for fixedwing aircraft
Implement specific navigation routines for the mission control of a fixedwing aircraft
Definition in file mission_fw_nav.c.
Function Documentation
static bool_t mission_nav_circle (struct _mission_circle * circle) inline static
Navigation function on a circle.
Definition at line 57 of file mission_fw_nav.c.
References _mission_circle::center, nav_circle_XY(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, _mission_circle::radius, TRUE, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by mission_run().
static bool_t mission_nav_path (struct _mission_path * path) inline static
Navigation function along a path.
Definition at line 79 of file mission_fw_nav.c.
References FALSE, mission_nav_wp(), nav_approaching_xy(), nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, _mission_path::nb, _mission_path::path, _mission_path::path_idx, TRUE, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by mission_run().
static bool_t mission_nav_segment (struct _mission_segment * segment) inline static
Navigation function along a segment.
Definition at line 66 of file mission_fw_nav.c.
References FALSE, _mission_segment::from, nav_approaching_xy(), nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, _mission_segment::to, TRUE, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by mission_run().
static bool_t mission_nav_wp (struct _mission_wp * wp) inline static
Navigation function to a single waypoint.
Definition at line 43 of file mission_fw_nav.c.
References FALSE, fly_to_xy(), nav_approaching_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, TRUE, _mission_wp::wp, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by mission_nav_path(), and mission_run().
int mission_run ()
Run mission.
This function should be implemented into a dedicated file since navigation functions are different for different firmwares
Currently, this function should be called from the flight plan
Returns
return TRUE when the mission is running, FALSE when it is finished
Definition at line 105 of file mission_fw_nav.c.
References _mission::current_idx, dt_navigation, _mission_element::duration, _mission_element::element, _mission::element_time, FALSE, mission, _mission_element::mission_circle, mission_get(), mission_nav_circle(), mission_nav_path(), mission_nav_segment(), mission_nav_wp(), _mission_element::mission_path, _mission_element::mission_segment, _mission_element::mission_wp, MissionCircle, MissionPath, MissionSegment, MissionWP, TRUE, and _mission_element::type.
Variable Documentation
const float dt_navigation = 1.0 / ((float)NAVIGATION_FREQUENCY)
Definition at line 36 of file mission_fw_nav.c.
struct EnuCoor_f last_wp = { 0., 0., 0. }
Definition at line 39 of file mission_fw_nav.c.