Paparazzi UAS: sw/airborne/peripherals/mpu60x0_i2c.h File Reference
mpu60x0_i2c.h File Reference
Driver for the MPU-60X0 using I2C.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "mcu_periph/i2c.h"
#include "peripherals/mpu60x0.h"
Data Structures
struct Mpu60x0_I2c
Macros
#define MPU60X0_BUFFER_EXT_LEN 16
Enumerations
enum Mpu60x0I2cSlaveInitStatus {
MPU60X0_I2C_CONF_UNINIT, MPU60X0_I2C_CONF_I2C_MST_DIS, MPU60X0_I2C_CONF_I2C_BYPASS_EN, MPU60X0_I2C_CONF_SLAVES_CONFIGURE,
MPU60X0_I2C_CONF_I2C_BYPASS_DIS, MPU60X0_I2C_CONF_I2C_MST_CLK, MPU60X0_I2C_CONF_I2C_MST_DELAY, MPU60X0_I2C_CONF_I2C_SMPLRT,
MPU60X0_I2C_CONF_I2C_MST_EN, MPU60X0_I2C_CONF_DONE
}
Functions
void mpu60x0_i2c_init (struct Mpu60x0_I2c *mpu, struct i2c_periph *i2c_p, uint8_t addr)
void mpu60x0_i2c_start_configure (struct Mpu60x0_I2c *mpu)
void mpu60x0_i2c_read (struct Mpu60x0_I2c *mpu)
void mpu60x0_i2c_event (struct Mpu60x0_I2c *mpu)
static void mpu60x0_i2c_periodic (struct Mpu60x0_I2c *mpu)
convenience function: read or start configuration if not already initialized
Detailed Description
Driver for the MPU-60X0 using I2C.
Definition in file mpu60x0_i2c.h.
Macro Definition Documentation
#define MPU60X0_BUFFER_EXT_LEN 16
Definition at line 39 of file mpu60x0_i2c.h.
Enumeration Type Documentation
enum Mpu60x0I2cSlaveInitStatus
Enumerator:
MPU60X0_I2C_CONF_UNINIT
MPU60X0_I2C_CONF_I2C_MST_DIS
MPU60X0_I2C_CONF_I2C_BYPASS_EN
MPU60X0_I2C_CONF_SLAVES_CONFIGURE
MPU60X0_I2C_CONF_I2C_BYPASS_DIS
MPU60X0_I2C_CONF_I2C_MST_CLK
MPU60X0_I2C_CONF_I2C_MST_DELAY
MPU60X0_I2C_CONF_I2C_SMPLRT
MPU60X0_I2C_CONF_I2C_MST_EN
MPU60X0_I2C_CONF_DONE
Definition at line 41 of file mpu60x0_i2c.h.
Function Documentation
void mpu60x0_i2c_event (struct Mpu60x0_I2c * mpu)
Definition at line 81 of file mpu60x0_i2c.c.
References i2c_transaction::buf, Mpu60x0_I2c::config, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_ext, Mpu60x0_I2c::data_rates, FALSE, Mpu60x0Config::i2c_bypass, Mpu60x0_I2c::i2c_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, Mpu60x0Config::init_status, Mpu60x0Config::initialized, Int16FromBuf, MPU60X0_CONF_UNINIT, mpu60x0_i2c_write_to_reg(), mpu60x0_send_config(), Mpu60x0Config::nb_bytes, Mpu60x0Config::nb_slaves, Int16Rates::p, Int16Rates::q, Int16Rates::r, Mpu60x0_I2c::rates, i2c_transaction::status, TRUE, Mpu60x0_I2c::vect, Int16Vect3::x, Int16Vect3::y, and Int16Vect3::z.
Referenced by imu_apogee_event(), imu_drotek2_event(), and imu_krooz_event().
void mpu60x0_i2c_init (struct Mpu60x0_I2c * mpu, struct i2c_periph * i2c_p, uint8_t addr)
Definition at line 31 of file mpu60x0_i2c.c.
References Mpu60x0_I2c::config, Mpu60x0_I2c::data_available, FALSE, Mpu60x0_I2c::i2c_p, Mpu60x0_I2c::i2c_trans, I2CTransDone, Mpu60x0Config::init_status, Mpu60x0Config::initialized, MPU60X0_CONF_UNINIT, MPU60X0_I2C_CONF_UNINIT, mpu60x0_set_default_config(), i2c_transaction::slave_addr, Mpu60x0_I2c::slave_init_status, and i2c_transaction::status.
Referenced by imu_impl_init().
static void mpu60x0_i2c_periodic (struct Mpu60x0_I2c * mpu) inline static
convenience function: read or start configuration if not already initialized
Definition at line 78 of file mpu60x0_i2c.h.
References Mpu60x0_I2c::config, Mpu60x0Config::initialized, mpu60x0_i2c_read(), and mpu60x0_i2c_start_configure().
Referenced by imu_periodic().
void mpu60x0_i2c_read (struct Mpu60x0_I2c * mpu)
Definition at line 70 of file mpu60x0_i2c.c.
References i2c_transaction::buf, Mpu60x0_I2c::config, Mpu60x0_I2c::i2c_p, Mpu60x0_I2c::i2c_trans, i2c_transceive(), I2CTransDone, Mpu60x0Config::initialized, MPU60X0_REG_INT_STATUS, Mpu60x0Config::nb_bytes, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by imu_krooz_event(), and mpu60x0_i2c_periodic().
void mpu60x0_i2c_start_configure (struct Mpu60x0_I2c * mpu)
Definition at line 60 of file mpu60x0_i2c.c.
References Mpu60x0_I2c::config, Mpu60x0_I2c::i2c_trans, I2CTransDone, I2CTransSuccess, Mpu60x0Config::init_status, MPU60X0_CONF_UNINIT, mpu60x0_i2c_write_to_reg(), mpu60x0_send_config(), and i2c_transaction::status.
Referenced by imu_periodic(), and mpu60x0_i2c_periodic().