Paparazzi UAS: sw/airborne/peripherals/ms5611.h File Reference
ms5611.h File Reference
MS5611 barometer driver common interface (I2C and SPI).
#include "std.h"
#include "peripherals/ms5611_regs.h"
Data Structures
struct Ms5611Data
Enumerations
enum Ms5611Status {
MS5611_STATUS_UNINIT, MS5611_STATUS_RESET, MS5611_STATUS_RESET_OK, MS5611_STATUS_PROM,
MS5611_STATUS_IDLE, MS5611_STATUS_CONV_D1, MS5611_STATUS_CONV_D1_OK, MS5611_STATUS_ADC_D1,
MS5611_STATUS_CONV_D2, MS5611_STATUS_CONV_D2_OK, MS5611_STATUS_ADC_D2
}
Functions
bool_t ms5611_prom_crc_ok (uint16_t *prom)
Check if CRC of PROM data is OK.
void ms5611_calc (struct Ms5611Data *ms)
Calculate temperature and compensated pressure.
Detailed Description
MS5611 barometer driver common interface (I2C and SPI).
Definition in file ms5611.h.
Enumeration Type Documentation
enum Ms5611Status
Enumerator:
MS5611_STATUS_UNINIT
MS5611_STATUS_RESET
MS5611_STATUS_RESET_OK
MS5611_STATUS_PROM
MS5611_STATUS_IDLE
MS5611_STATUS_CONV_D1
MS5611_STATUS_CONV_D1_OK
MS5611_STATUS_ADC_D1
MS5611_STATUS_CONV_D2
MS5611_STATUS_CONV_D2_OK
MS5611_STATUS_ADC_D2
Definition at line 37 of file ms5611.h.
Function Documentation
void ms5611_calc (struct Ms5611Data * ms)
Calculate temperature and compensated pressure.
Definition at line 62 of file ms5611.c.
References Ms5611Data::c, Ms5611Data::d1, Ms5611Data::d2, Ms5611Data::pressure, t2, and Ms5611Data::temperature.
Referenced by ms5611_i2c_event(), and ms5611_spi_event().
bool_t ms5611_prom_crc_ok (uint16_t * prom)
Check if CRC of PROM data is OK.
Returns
TRUE if OK, FALSE otherwise
Definition at line 36 of file ms5611.c.
References crc, FALSE, and TRUE.
Referenced by ms5611_i2c_event(), and ms5611_spi_event().