Paparazzi UAS: sw/airborne/boards/ardrone/navdata.c File Reference
navdata.c File Reference
ardrone2 navdata aquisition driver.
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include <assert.h>
#include "std.h"
#include "navdata.h"
#include "subsystems/ins.h"
#include "subsystems/sonar.h"
Macros
#define NAVDATA_PACKET_SIZE 60
#define NAVDATA_START_BYTE 0x3a
Functions
static bool_t acquire_baro_calibration (void)
static void navdata_cropbuffer (int cropsize)
ssize_t full_write (int fd, const uint8_t *buf, size_t count)
ssize_t full_read (int fd, uint8_t *buf, size_t count)
static void navdata_write (const uint8_t *buf, size_t count)
bool_t navdata_init ()
void navdata_read ()
static void baro_update_logic (void)
void navdata_update ()
int16_t navdata_height (void)
Variables
navdata_port nav_port
static int nav_fd = 0
static int16_t previousUltrasoundHeight
measures_t navdata
uint16_t sonar_meas = 0
Raw ADC value.
Detailed Description
ardrone2 navdata aquisition driver.
The ardrone2 provides a navdata stream of packets containing info about all sensors at a rate of 200Hz.
Definition in file navdata.c.
Macro Definition Documentation
#define NAVDATA_PACKET_SIZE 60
Definition at line 44 of file navdata.c.
Referenced by navdata_update().
#define NAVDATA_START_BYTE 0x3a
Definition at line 45 of file navdata.c.
Referenced by navdata_update().
Function Documentation
static bool_t acquire_baro_calibration (void) inline static
Definition at line 208 of file navdata.c.
References bmp180_baro_calibration::ac1, bmp180_baro_calibration::ac2, bmp180_baro_calibration::ac3, bmp180_baro_calibration::ac4, bmp180_baro_calibration::ac5, bmp180_baro_calibration::ac6, bmp180_baro_calibration::b1, bmp180_baro_calibration::b2, baro_calibrated, baro_calibration, FALSE, full_read(), bmp180_baro_calibration::mb, bmp180_baro_calibration::mc, bmp180_baro_calibration::md, nav_fd, navdata_write(), and TRUE.
Referenced by navdata_init().
static void baro_update_logic (void) static
Definition at line 264 of file navdata.c.
References FALSE, navdata_baro_available, measures_t::pressure, measures_t::temperature_pressure, and TRUE.
Referenced by navdata_update().
ssize_t full_read (int fd, uint8_t * buf, size_t count)
Definition at line 78 of file navdata.c.
Referenced by acquire_baro_calibration(), actuators_ardrone_cmd(), and ahrs_propagate().
ssize_t full_write (int fd, const uint8_t * buf, size_t count)
Definition at line 60 of file navdata.c.
Referenced by actuators_ardrone_cmd(), actuators_ardrone_set_leds(), actuators_ardrone_set_pwm(), and navdata_write().
static void navdata_cropbuffer (int cropsize) static
Definition at line 406 of file navdata.c.
References navdata_port::buffer, navdata_port::bytesRead, and NAVDATA_BUFFER_SIZE.
Referenced by navdata_update().
int16_t navdata_height (void)
Definition at line 395 of file navdata.c.
References previousUltrasoundHeight, and measures_t::ultrasound.
bool_t navdata_init (void)
Definition at line 140 of file navdata.c.
References acquire_baro_calibration(), baro_calibrated, navdata_port::bytesRead, navdata_port::checksum_errors, FALSE, navdata_port::isInitialized, nav_fd, navdata_baro_available, navdata_imu_available, navdata_write(), navdata_port::packetsRead, previousUltrasoundHeight, register_periodic_telemetry(), navdata_port::totalBytesRead, and TRUE.
Referenced by imu_impl_init(), and navdata_update().
void navdata_read (void)
Definition at line 252 of file navdata.c.
References navdata_port::buffer, navdata_port::bytesRead, nav_fd, NAVDATA_BUFFER_SIZE, and navdata_port::totalBytesRead.
Referenced by navdata_update().
void navdata_update (void)
Definition at line 314 of file navdata.c.
References baro_update_logic(), navdata_port::buffer, navdata_port::bytesRead, navdata_port::checksum_errors, measures_t::chksum, FALSE, ins_update_sonar(), navdata_port::isInitialized, navdata_cropbuffer(), navdata_imu_available, navdata_init(), NAVDATA_PACKET_SIZE, navdata_read(), NAVDATA_START_BYTE, p, navdata_port::packetsRead, measures_t::pressure, sonar_meas, measures_t::temperature_pressure, TRUE, and measures_t::ultrasound.
Referenced by imu_ardrone2_event().
static void navdata_write (const uint8_t * buf, size_t count) static
Definition at line 97 of file navdata.c.
References full_write(), and nav_fd.
Referenced by acquire_baro_calibration(), and navdata_init().
Variable Documentation
int nav_fd = 0 static
Definition at line 51 of file navdata.c.
Referenced by acquire_baro_calibration(), navdata_init(), navdata_read(), and navdata_write().
navdata_port nav_port
Definition at line 50 of file navdata.c.
measures_t navdata
Definition at line 53 of file navdata.c.
Referenced by ardrone_baro_event(), and imu_ardrone2_event().
int16_t previousUltrasoundHeight static
Definition at line 52 of file navdata.c.
Referenced by navdata_height(), and navdata_init().
uint16_t sonar_meas = 0
Raw ADC value.
Definition at line 56 of file navdata.c.
Referenced by ins_update_sonar(), navdata_update(), sonar_adc_init(), and sonar_adc_read().