Paparazzi UAS: sw/airborne/boards/ardrone/navdata.h File Reference
navdata.h File Reference
ardrone2 navdata aquisition driver.
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct measures_t
struct bmp180_baro_calibration
struct navdata_port
Macros
#define NAVDATA_BUFFER_SIZE 80
Functions
bool_t navdata_init (void)
void navdata_read (void)
void navdata_update (void)
int16_t navdata_height (void)
ssize_t full_write (int fd, const uint8_t *buf, size_t count)
ssize_t full_read (int fd, uint8_t *buf, size_t count)
Variables
measures_t navdata
navdata_port nav_port
struct bmp180_baro_calibration baro_calibration
navdata_port * port
uint16_t navdata_cks
uint8_t navdata_imu_available
uint8_t navdata_baro_available
uint8_t baro_calibrated
Detailed Description
ardrone2 navdata aquisition driver.
The ardrone2 provides a navdata stream of packets containing info about all sensors at a rate of 200Hz.
Definition in file navdata.h.
Macro Definition Documentation
#define NAVDATA_BUFFER_SIZE 80
Definition at line 98 of file navdata.h.
Referenced by navdata_cropbuffer(), and navdata_read().
Function Documentation
ssize_t full_read (int fd, uint8_t * buf, size_t count)
Definition at line 78 of file navdata.c.
Referenced by acquire_baro_calibration(), actuators_ardrone_cmd(), and ahrs_propagate().
ssize_t full_write (int fd, const uint8_t * buf, size_t count)
Definition at line 60 of file navdata.c.
Referenced by actuators_ardrone_cmd(), actuators_ardrone_set_leds(), actuators_ardrone_set_pwm(), and navdata_write().
int16_t navdata_height (void)
Definition at line 395 of file navdata.c.
References previousUltrasoundHeight, and measures_t::ultrasound.
bool_t navdata_init (void)
Definition at line 140 of file navdata.c.
References acquire_baro_calibration(), baro_calibrated, navdata_port::bytesRead, navdata_port::checksum_errors, FALSE, navdata_port::isInitialized, nav_fd, navdata_baro_available, navdata_imu_available, navdata_write(), navdata_port::packetsRead, previousUltrasoundHeight, register_periodic_telemetry(), navdata_port::totalBytesRead, and TRUE.
Referenced by imu_impl_init(), and navdata_update().
void navdata_read (void)
Definition at line 252 of file navdata.c.
References navdata_port::buffer, navdata_port::bytesRead, nav_fd, NAVDATA_BUFFER_SIZE, and navdata_port::totalBytesRead.
Referenced by navdata_update().
void navdata_update (void)
Definition at line 314 of file navdata.c.
References baro_update_logic(), navdata_port::buffer, navdata_port::bytesRead, navdata_port::checksum_errors, measures_t::chksum, FALSE, ins_update_sonar(), navdata_port::isInitialized, navdata_cropbuffer(), navdata_imu_available, navdata_init(), NAVDATA_PACKET_SIZE, navdata_read(), NAVDATA_START_BYTE, p, navdata_port::packetsRead, measures_t::pressure, sonar_meas, measures_t::temperature_pressure, TRUE, and measures_t::ultrasound.
Referenced by imu_ardrone2_event().
Variable Documentation
uint8_t baro_calibrated
Definition at line 115 of file navdata.h.
Referenced by acquire_baro_calibration(), ardrone_baro_event(), and navdata_init().
struct bmp180_baro_calibration baro_calibration
Definition at line 110 of file navdata.h.
Referenced by acquire_baro_calibration(), baro_apply_calibration(), and baro_apply_calibration_temp().
navdata_port nav_port
Definition at line 50 of file navdata.c.
measures_t navdata
Definition at line 53 of file navdata.c.
Referenced by ardrone_baro_event(), and imu_ardrone2_event().
uint8_t navdata_baro_available
Definition at line 114 of file navdata.h.
Referenced by ardrone_baro_event(), baro_update_logic(), and navdata_init().
uint16_t navdata_cks
Definition at line 112 of file navdata.h.
uint8_t navdata_imu_available
Definition at line 113 of file navdata.h.
Referenced by imu_ardrone2_event(), navdata_init(), and navdata_update().
navdata_port* port
Definition at line 111 of file navdata.h.
Referenced by uart_handler(), uart_periph_set_baudrate(), and uart_transmit().