Paparazzi UAS: sw/airborne/arch/omap/mcu_periph/uart_arch.c File Reference
uart_arch.c File Reference
omap uart handling
#include "mcu_periph/uart.h"
#include <stdint.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "serial_port.h"
#include <errno.h>
Macros
#define TRACE(fmt, args...)
Functions
void uart_periph_set_baudrate (struct uart_periph *periph, uint32_t baud)
void uart_transmit (struct uart_periph *periph, uint8_t data)
static void uart_handler (struct uart_periph *periph)
Detailed Description
omap uart handling
Definition in file uart_arch.c.
Macro Definition Documentation
#define TRACE (fmt, args...)
Definition at line 37 of file uart_arch.c.
Referenced by uart_handler(), uart_periph_set_baudrate(), and uart_transmit().
Function Documentation
static void uart_handler (struct uart_periph * periph) inline static
Definition at line 87 of file uart_arch.c.
References c, FALSE, SerialPort::fd, fd, port, uart_periph::reg_addr, uart_periph::rx_buf, uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, TRACE, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, UART_RX_BUFFER_SIZE, and UART_TX_BUFFER_SIZE.
void uart_periph_set_baudrate (struct uart_periph * periph, uint32_t baud)
Definition at line 40 of file uart_arch.c.
References uart_periph::dev, port, uart_periph::reg_addr, serial_port_close(), serial_port_free(), serial_port_new(), serial_port_open_raw(), and TRACE.
void uart_transmit (struct uart_periph * periph, uint8_t data)
Definition at line 63 of file uart_arch.c.
References SerialPort::fd, port, uart_periph::reg_addr, TRACE, TRUE, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, and UART_TX_BUFFER_SIZE.