Paparazzi UAS: sw/airborne/arch/omap/mcu_periph/gpio_arch.h File Reference
gpio_arch.h File Reference
GPIO helper functions for linux/omap.
#include "std.h"
Functions
void gpio_set (uint32_t port, uint16_t pin)
Set a gpio output to high level.
void gpio_clear (uint32_t port, uint16_t pin)
Clear a gpio output to low level.
uint16_t gpio_get (uint32_t gpioport, uint16_t gpios)
Read a gpio value.
Detailed Description
GPIO helper functions for linux/omap.
Todo:
implement gpio_set|clear
Definition in file gpio_arch.h.
Function Documentation
void gpio_clear (uint32_t port, uint16_t pin)
Clear a gpio output to low level.
Referenced by actuators_ardrone_init(), actuators_ardrone_motor_status(), actuators_ardrone_reset_flipflop(), baro_init(), cyrf6936_init(), main(), radio_control_spektrum_try_bind(), SpiSlaveSelect(), and w5100_init().
uint16_t gpio_get (uint32_t gpioport, uint16_t gpios)
Read a gpio value.
Referenced by actuators_ardrone_motor_status(), baro_eoc(), imu_aspirin_eoc(), mag_eoc(), radio_control_spektrum_try_bind(), and superbitrf_event().
void gpio_set (uint32_t port, uint16_t pin)
Set a gpio output to high level.
Referenced by actuators_ardrone_init(), actuators_ardrone_motor_status(), actuators_ardrone_reset_flipflop(), can_hw_init(), cyrf6936_init(), imu_impl_init(), main(), ms2100_arch_init(), radio_control_spektrum_try_bind(), SpiSlaveUnselect(), and w5100_init().