Paparazzi UAS: sw/airborne/math/pprz_isa.h File Reference
pprz_isa.h File Reference
Paparazzi atmospheric pressure convertion utilities.
#include "std.h"
#include <math.h>
Macros
#define PPRZ_ISA_SEA_LEVEL_PRESSURE 101325.0
#define PPRZ_ISA_SEA_LEVEL_TEMP 288.15
#define PPRZ_ISA_TEMP_LAPS_RATE 0.0065
#define PPRZ_ISA_GRAVITY 9.80665
#define PPRZ_ISA_AIR_GAS_CONSTANT (8.31447/0.0289644)
Functions
static float pprz_isa_altitude_of_pressure (float pressure)
Get absolute altitude from pressure (using simplified equation).
static float pprz_isa_height_of_pressure (float pressure, float ref)
Get relative altitude from pressure (using simplified equation).
static float pprz_isa_pressure_of_altitude (float altitude)
Get pressure in Pa from absolute altitude (using simplified equation).
static float pprz_isa_pressure_of_height (float altitude, float ref)
Get pressure in Pa from height (using simplified equation).
Variables
static const float PPRZ_ISA_M_OF_P_CONST = (PPRZ_ISA_AIR_GAS_CONSTANT*PPRZ_ISA_SEA_LEVEL_TEMP/PPRZ_ISA_GRAVITY)
Detailed Description
Paparazzi atmospheric pressure convertion utilities.
Conversion functions are use to approximate altitude from atmospheric pressure based on the standard model and the International Standard Atmosphere (ISA)
http://en.wikipedia.org/wiki/Atmospheric_pressure http://en.wikipedia.org/wiki/International_Standard_Atmosphere
Definition in file pprz_isa.h.
Macro Definition Documentation
#define PPRZ_ISA_AIR_GAS_CONSTANT (8.31447/0.0289644)
Definition at line 47 of file pprz_isa.h.
#define PPRZ_ISA_GRAVITY 9.80665
Definition at line 46 of file pprz_isa.h.
#define PPRZ_ISA_SEA_LEVEL_PRESSURE 101325.0
Definition at line 43 of file pprz_isa.h.
Referenced by pprz_isa_altitude_of_pressure(), and pprz_isa_pressure_of_altitude().
#define PPRZ_ISA_SEA_LEVEL_TEMP 288.15
Definition at line 44 of file pprz_isa.h.
#define PPRZ_ISA_TEMP_LAPS_RATE 0.0065
Definition at line 45 of file pprz_isa.h.
Function Documentation
static float pprz_isa_altitude_of_pressure (float pressure) inline static
Get absolute altitude from pressure (using simplified equation).
Referrence pressure is standard pressure at sea level
Parameters
pressure current pressure in Pascal (Pa)
Returns
altitude in pressure in ISA conditions
Definition at line 58 of file pprz_isa.h.
References PPRZ_ISA_M_OF_P_CONST, and PPRZ_ISA_SEA_LEVEL_PRESSURE.
Referenced by baro_ms5611_event().
static float pprz_isa_height_of_pressure (float pressure, float ref) inline static
Get relative altitude from pressure (using simplified equation).
Parameters
pressure current pressure in Pascal (Pa)
ref reference pressure (QFE) when height = 0
Returns
altitude in pressure in ISA conditions
Definition at line 73 of file pprz_isa.h.
References PPRZ_ISA_M_OF_P_CONST.
Referenced by baro_cb().
static float pprz_isa_pressure_of_altitude (float altitude) inline static
Get pressure in Pa from absolute altitude (using simplified equation).
Parameters
altitude current absolute altitude in meters
Returns
static pressure in Pa in ISA conditions
Definition at line 87 of file pprz_isa.h.
References PPRZ_ISA_M_OF_P_CONST, and PPRZ_ISA_SEA_LEVEL_PRESSURE.
Referenced by baro_sim_periodic().
static float pprz_isa_pressure_of_height (float altitude, float ref) inline static
Get pressure in Pa from height (using simplified equation).
Parameters
altitude current relative altitude in meters
ref reference pressure (QFE) when height = 0
Returns
static pressure in Pa in ISA conditions
Definition at line 98 of file pprz_isa.h.
References PPRZ_ISA_M_OF_P_CONST.
Variable Documentation
const float PPRZ_ISA_M_OF_P_CONST = (PPRZ_ISA_AIR_GAS_CONSTANT*PPRZ_ISA_SEA_LEVEL_TEMP/PPRZ_ISA_GRAVITY) static
Definition at line 49 of file pprz_isa.h.
Referenced by pprz_isa_altitude_of_pressure(), pprz_isa_height_of_pressure(), pprz_isa_pressure_of_altitude(), and pprz_isa_pressure_of_height().