Paparazzi UAS: sw/airborne/math/pprz_geodetic_float.h File Reference
pprz_geodetic_float.h File Reference
Paparazzi floating point math for geodetic calculations.
#include "pprz_geodetic.h"
#include "pprz_algebra_float.h"
#include "std.h"
Data Structures
struct EcefCoor_f
vector in EarthCenteredEarthFixed coordinates
struct LlaCoor_f
vector in Latitude, Longitude and Altitude
struct NedCoor_f
vector in North East Down coordinates Units: meters
struct EnuCoor_f
vector in East North Up coordinates Units: meters
struct UtmCoor_f
position in UTM coordinates Units: meters
struct LtpDef_f
definition of the local (flat earth) coordinate system
Functions
void lla_of_utm_f (struct LlaCoor_f *lla, struct UtmCoor_f *utm)
void utm_of_lla_f (struct UtmCoor_f *utm, struct LlaCoor_f *lla)
void ltp_def_from_ecef_f (struct LtpDef_f *def, struct EcefCoor_f *ecef)
void ltp_def_from_lla_f (struct LtpDef_f *def, struct LlaCoor_f *lla)
void lla_of_ecef_f (struct LlaCoor_f *out, struct EcefCoor_f *in)
void ecef_of_lla_f (struct EcefCoor_f *out, struct LlaCoor_f *in)
void enu_of_ecef_point_f (struct EnuCoor_f *enu, struct LtpDef_f *def, struct EcefCoor_f *ecef)
void ned_of_ecef_point_f (struct NedCoor_f *ned, struct LtpDef_f *def, struct EcefCoor_f *ecef)
void enu_of_ecef_vect_f (struct EnuCoor_f *enu, struct LtpDef_f *def, struct EcefCoor_f *ecef)
void ned_of_ecef_vect_f (struct NedCoor_f *ned, struct LtpDef_f *def, struct EcefCoor_f *ecef)
void enu_of_lla_point_f (struct EnuCoor_f *enu, struct LtpDef_f *def, struct LlaCoor_f *lla)
void ned_of_lla_point_f (struct NedCoor_f *ned, struct LtpDef_f *def, struct LlaCoor_f *lla)
void ecef_of_enu_point_f (struct EcefCoor_f *ecef, struct LtpDef_f *def, struct EnuCoor_f *enu)
void ecef_of_ned_point_f (struct EcefCoor_f *ecef, struct LtpDef_f *def, struct NedCoor_f *ned)
void ecef_of_enu_vect_f (struct EcefCoor_f *ecef, struct LtpDef_f *def, struct EnuCoor_f *enu)
void ecef_of_ned_vect_f (struct EcefCoor_f *ecef, struct LtpDef_f *def, struct NedCoor_f *ned)
Detailed Description
Paparazzi floating point math for geodetic calculations.
This is the more detailed description of this file.
Definition in file pprz_geodetic_float.h.
Function Documentation
void ecef_of_enu_point_f (struct EcefCoor_f * ecef, struct LtpDef_f * def, struct EnuCoor_f * enu)
Definition at line 93 of file pprz_geodetic_float.c.
References LtpDef_f::ecef, LtpDef_f::ltp_of_ecef, DoubleMat33::m, FloatMat33::m, MAT33_VECT3_TRANSP_MUL, EcefCoor_f::x, EcefCoor_d::x, EnuCoor_f::x, EcefCoor_f::y, EcefCoor_d::y, EnuCoor_f::y, EcefCoor_f::z, EcefCoor_d::z, and EnuCoor_f::z.
Referenced by ecef_of_ned_point_f().
void ecef_of_enu_vect_f (struct EcefCoor_f * ecef, struct LtpDef_f * def, struct EnuCoor_f * enu)
Definition at line 126 of file pprz_geodetic_float.c.
References LtpDef_f::ltp_of_ecef, DoubleMat33::m, FloatMat33::m, MAT33_VECT3_TRANSP_MUL, EcefCoor_f::x, EcefCoor_d::x, EnuCoor_f::x, EcefCoor_f::y, EcefCoor_d::y, EnuCoor_f::y, EcefCoor_d::z, EcefCoor_f::z, and EnuCoor_f::z.
Referenced by ecef_of_ned_vect_f().
void ecef_of_lla_f (struct EcefCoor_f * out, struct LlaCoor_f * in)
Definition at line 199 of file pprz_geodetic_float.c.
References LlaCoor_f::alt, LlaCoor_f::lat, LlaCoor_f::lon, EcefCoor_f::x, EcefCoor_f::y, and EcefCoor_f::z.
Referenced by enu_of_lla_point_f(), ltp_def_from_lla_f(), ned_of_lla_point_f(), parse_nmea_GPGGA(), stateCalcPositionEcef_f(), stateCalcPositionEcef_i(), stateCalcPositionEnu_i(), and stateCalcPositionNed_i().
void ecef_of_ned_point_f (struct EcefCoor_f * ecef, struct LtpDef_f * def, struct NedCoor_f * ned)
Definition at line 120 of file pprz_geodetic_float.c.
References ecef_of_enu_point_f(), and ENU_OF_TO_NED.
Referenced by stateCalcPositionEcef_f(), stateCalcPositionEcef_i(), stateCalcPositionLla_f(), and stateCalcPositionLla_i().
void ecef_of_ned_vect_f (struct EcefCoor_f * ecef, struct LtpDef_f * def, struct NedCoor_f * ned)
Definition at line 153 of file pprz_geodetic_float.c.
References ecef_of_enu_vect_f(), and ENU_OF_TO_NED.
Referenced by stateCalcAccelEcef_f(), and stateCalcSpeedEcef_f().
void enu_of_ecef_point_f (struct EnuCoor_f * enu, struct LtpDef_f * def, struct EcefCoor_f * ecef)
Definition at line 55 of file pprz_geodetic_float.c.
References LtpDef_f::ecef, LtpDef_f::ltp_of_ecef, MAT33_VECT3_MUL, and VECT3_DIFF.
Referenced by enu_of_lla_point_f(), ned_of_ecef_point_f(), stateCalcPositionEnu_f(), and stateCalcPositionEnu_i().
void enu_of_ecef_vect_f (struct EnuCoor_f * enu, struct LtpDef_f * def, struct EcefCoor_f * ecef)
Definition at line 68 of file pprz_geodetic_float.c.
References LtpDef_f::ltp_of_ecef, and MAT33_VECT3_MUL.
Referenced by ned_of_ecef_vect_f(), and stateCalcSpeedEnu_f().
void enu_of_lla_point_f (struct EnuCoor_f * enu, struct LtpDef_f * def, struct LlaCoor_f * lla)
Definition at line 78 of file pprz_geodetic_float.c.
References ecef_of_lla_f(), and enu_of_ecef_point_f().
Referenced by stateCalcPositionEnu_f().
void lla_of_ecef_f (struct LlaCoor_f * out, struct EcefCoor_f * in)
Definition at line 164 of file pprz_geodetic_float.c.
References LlaCoor_f::alt, c, LlaCoor_f::lat, LlaCoor_f::lon, Q, EcefCoor_f::x, EcefCoor_f::y, and EcefCoor_f::z.
Referenced by ltp_def_from_ecef_f(), stateCalcPositionLla_f(), and stateCalcPositionLla_i().
void lla_of_utm_f (struct LlaCoor_f * lla, struct UtmCoor_f * utm)
Definition at line 282 of file pprz_geodetic_float.c.
References LlaCoor_f::alt, UtmCoor_f::alt, CScal, CSin, CSub, DELTA_EAST, DELTA_NORTH, E, UtmCoor_f::east, complex::im, inverse_isometric_latitude_f(), isometric_latitude_fast_f(), LambdaOfUtmZone, LlaCoor_f::lat, LlaCoor_f::lon, N, UtmCoor_f::north, complex::re, serie_coeff_proj_mercator, serie_coeff_proj_mercator_inverse, and UtmCoor_f::zone.
Referenced by nav_reset_utm_zone(), stateCalcPositionLla_f(), stateCalcPositionLla_i(), and vPoint().
void ltp_def_from_ecef_f (struct LtpDef_f * def, struct EcefCoor_f * ecef)
Definition at line 9 of file pprz_geodetic_float.c.
References LtpDef_f::ecef, LlaCoor_f::lat, LtpDef_f::lla, lla_of_ecef_f(), LlaCoor_f::lon, LtpDef_f::ltp_of_ecef, FloatMat33::m, and VECT3_COPY.
void ltp_def_from_lla_f (struct LtpDef_f * def, struct LlaCoor_f * lla)
Definition at line 32 of file pprz_geodetic_float.c.
References LtpDef_f::ecef, ecef_of_lla_f(), LlaCoor_f::lat, LtpDef_f::lla, LLA_COPY, LlaCoor_f::lon, LtpDef_f::ltp_of_ecef, and FloatMat33::m.
void ned_of_ecef_point_f (struct NedCoor_f * ned, struct LtpDef_f * def, struct EcefCoor_f * ecef)
Definition at line 61 of file pprz_geodetic_float.c.
References enu_of_ecef_point_f(), and ENU_OF_TO_NED.
Referenced by ned_of_lla_point_f(), stateCalcPositionNed_f(), and stateCalcPositionNed_i().
void ned_of_ecef_vect_f (struct NedCoor_f * ned, struct LtpDef_f * def, struct EcefCoor_f * ecef)
Definition at line 72 of file pprz_geodetic_float.c.
References enu_of_ecef_vect_f(), and ENU_OF_TO_NED.
Referenced by stateCalcAccelNed_f(), stateCalcHorizontalSpeedNorm_i(), and stateCalcSpeedNed_f().
void ned_of_lla_point_f (struct NedCoor_f * ned, struct LtpDef_f * def, struct LlaCoor_f * lla)
Definition at line 84 of file pprz_geodetic_float.c.
References ecef_of_lla_f(), and ned_of_ecef_point_f().
Referenced by stateCalcPositionNed_f().
void utm_of_lla_f (struct UtmCoor_f * utm, struct LlaCoor_f * lla)
Definition at line 257 of file pprz_geodetic_float.c.
References LlaCoor_f::alt, UtmCoor_f::alt, CAdd, CScal, CSin, DELTA_EAST, DELTA_NORTH, E, UtmCoor_f::east, complex::im, isometric_latitude_f(), isometric_latitude_fast_f(), LambdaOfUtmZone, LlaCoor_f::lat, LlaCoor_f::lon, N, UtmCoor_f::north, complex::re, serie_coeff_proj_mercator, and UtmCoor_f::zone.
Referenced by dl_parse_msg(), gps_feed_value(), gps_mtk_read_message(), gps_skytraq_read_message(), gps_ubx_read_message(), nav_reset_reference(), nav_reset_utm_zone(), parse_dl_move_wp(), parse_ins_msg(), parse_nmea_GPGGA(), sim_use_gps_pos(), sirf_parse_41(), stateCalcPositionEnu_f(), stateCalcPositionEnu_i(), stateCalcPositionNed_f(), stateCalcPositionNed_i(), and stateCalcPositionUtm_f().