Paparazzi UAS: sw/airborne/math/pprz_geodetic_int.h File Reference
pprz_geodetic_int.h File Reference
Paparazzi fixed point math for geodetic calculations.
#include "pprz_geodetic.h"
#include "std.h"
#include "pprz_algebra_int.h"
Data Structures
struct EcefCoor_i
vector in EarthCenteredEarthFixed coordinates
struct LlaCoor_i
vector in Latitude, Longitude and Altitude
struct NedCoor_i
vector in North East Down coordinates
struct EnuCoor_i
vector in East North Up coordinates
struct UtmCoor_i
position in UTM coordinates
struct LtpDef_i
definition of the local (flat earth) coordinate system
Macros
#define CM_OF_M(_m) ((_m)*1e2)
#define M_OF_CM(_cm) ((_cm)/1e2)
#define MM_OF_M(_m) ((_m)*1e3)
#define M_OF_MM(_mm) ((_mm)/1e3)
#define EM7RAD_OF_RAD(_r) ((_r)*1e7)
#define RAD_OF_EM7RAD(_r) ((_r)/1e7)
#define VECT3_ENU_OF_NED(_o, _i)
#define VECT3_NED_OF_ENU(_o, _i) VECT3_ENU_OF_NED(_o,_i)
#define INT32_VECT3_NED_OF_ENU(_o, _i) VECT3_ENU_OF_NED(_o,_i)
#define INT32_VECT3_ENU_OF_NED(_o, _i) VECT3_ENU_OF_NED(_o,_i)
#define ECEF_BFP_OF_REAL(_o, _i)
#define ECEF_FLOAT_OF_BFP(_o, _i)
#define LLA_BFP_OF_REAL(_o, _i)
#define LLA_FLOAT_OF_BFP(_o, _i)
#define NED_BFP_OF_REAL(_o, _i)
#define ENU_BFP_OF_REAL(_o, _i) NED_BFP_OF_REAL(_o, _i)
#define NED_FLOAT_OF_BFP(_o, _i)
#define ENU_FLOAT_OF_BFP(_o, _i) NED_FLOAT_OF_BFP(_o, _i)
#define INT32_VECT2_ENU_OF_NED(_o, _i)
#define INT32_VECT2_NED_OF_ENU(_o, _i) INT32_VECT2_ENU_OF_NED(_o,_i)
Functions
void ltp_of_ecef_rmat_from_lla_i (struct Int32Mat33 *ltp_of_ecef, struct LlaCoor_i *lla)
void ltp_def_from_ecef_i (struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ltp_def_from_lla_i (struct LtpDef_i *def, struct LlaCoor_i *lla)
void lla_of_ecef_i (struct LlaCoor_i *out, struct EcefCoor_i *in)
void ecef_of_lla_i (struct EcefCoor_i *out, struct LlaCoor_i *in)
void enu_of_ecef_point_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ned_of_ecef_point_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void enu_of_ecef_pos_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct EcefCoor_i *ecef)
Convert a ECEF position to local ENU.
void ned_of_ecef_pos_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct EcefCoor_i *ecef)
Convert a ECEF position to local NED.
void enu_of_ecef_vect_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ned_of_ecef_vect_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void enu_of_lla_point_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct LlaCoor_i *lla)
void ned_of_lla_point_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct LlaCoor_i *lla)
void enu_of_lla_vect_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct LlaCoor_i *lla)
void ned_of_lla_vect_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct LlaCoor_i *lla)
void ecef_of_enu_point_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct EnuCoor_i *enu)
Convert a point in local ENU to ECEF.
void ecef_of_ned_point_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct NedCoor_i *ned)
Convert a point in local NED to ECEF.
void ecef_of_enu_pos_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct EnuCoor_i *enu)
Convert a local ENU position to ECEF.
void ecef_of_ned_pos_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct NedCoor_i *ned)
Convert a local NED position to ECEF.
void ecef_of_enu_vect_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct EnuCoor_i *enu)
void ecef_of_ned_vect_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct NedCoor_i *ned)
Detailed Description
Paparazzi fixed point math for geodetic calculations.
This is the more detailed description of this file.
Definition in file pprz_geodetic_int.h.
Macro Definition Documentation
#define CM_OF_M (_m) ((_m)*1e2)
Definition at line 122 of file pprz_geodetic_int.h.
Referenced by ecef_of_lla_i().
#define ECEF_BFP_OF_REAL (_o, _i)
Value:
{          \
    (_o).x = (int32_t)CM_OF_M((_i).x);      \
    (_o).y = (int32_t)CM_OF_M((_i).y);      \
    (_o).z = (int32_t)CM_OF_M((_i).z);      \
  }
Definition at line 139 of file pprz_geodetic_int.h.
Referenced by gps_ardrone2_parse(), and stateCalcPositionEcef_i().
#define ECEF_FLOAT_OF_BFP (_o, _i)
Value:
{           \
    (_o).x = (float)M_OF_CM((_i).x);          \
    (_o).y = (float)M_OF_CM((_i).y);          \
    (_o).z = (float)M_OF_CM((_i).z);          \
  }
Definition at line 145 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEcef_f(), stateCalcPositionLla_f(), and stateSetLocalOrigin_i().
#define EM7RAD_OF_RAD (_r) ((_r)*1e7)
Definition at line 126 of file pprz_geodetic_int.h.
Referenced by lla_of_ecef_i().
#define ENU_BFP_OF_REAL (_o, _i) NED_BFP_OF_REAL(_o, _i)
Definition at line 169 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEnu_i(), stateCalcPositionNed_i(), and stateCalcSpeedEnu_i().
#define ENU_FLOAT_OF_BFP (_o, _i) NED_FLOAT_OF_BFP(_o, _i)
Definition at line 177 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEnu_f(), stateCalcPositionNed_f(), and stateCalcSpeedEnu_f().
#define INT32_VECT2_ENU_OF_NED (_o, _i)
Value:
{   \
    (_o).x = (_i).y;        \
    (_o).y = (_i).x;        \
  }
Definition at line 179 of file pprz_geodetic_int.h.
#define INT32_VECT2_NED_OF_ENU (_o, _i) INT32_VECT2_ENU_OF_NED(_o,_i)
Definition at line 184 of file pprz_geodetic_int.h.
Referenced by guidance_h_nav_enter(), and guidance_h_run().
#define INT32_VECT3_ENU_OF_NED (_o, _i) VECT3_ENU_OF_NED(_o,_i)
Definition at line 137 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEnu_i(), and stateCalcSpeedEnu_i().
#define INT32_VECT3_NED_OF_ENU (_o, _i) VECT3_ENU_OF_NED(_o,_i)
Definition at line 136 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionNed_i(), and stateCalcSpeedNed_i().
#define LLA_BFP_OF_REAL (_o, _i)
Value:
{                \
    (_o).lat = (int32_t)EM7RAD_OF_RAD((_i).lat); \
    (_o).lon = (int32_t)EM7RAD_OF_RAD((_i).lon); \
    (_o).alt = (int32_t)MM_OF_M((_i).alt);       \
  }
Definition at line 151 of file pprz_geodetic_int.h.
Referenced by gps_ardrone2_parse(), sim_use_gps_pos(), and stateCalcPositionLla_i().
#define LLA_FLOAT_OF_BFP (_o, _i)
Value:
{                   \
    (_o).lat = (float)RAD_OF_EM7RAD((_i).lat);    \
    (_o).lon = (float)RAD_OF_EM7RAD((_i).lon);    \
    (_o).alt = (float)M_OF_MM((_i).alt);          \
  }
Definition at line 157 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEcef_f(), stateCalcPositionEnu_f(), stateCalcPositionEnu_i(), stateCalcPositionLla_f(), stateCalcPositionNed_f(), stateCalcPositionNed_i(), stateCalcPositionUtm_f(), and stateSetLocalOrigin_i().
#define M_OF_CM (_cm) ((_cm)/1e2)
Definition at line 123 of file pprz_geodetic_int.h.
Referenced by lla_of_ecef_i().
#define M_OF_MM (_mm) ((_mm)/1e3)
Definition at line 125 of file pprz_geodetic_int.h.
Referenced by ecef_of_lla_i(), and stateSetLocalOrigin_i().
#define MM_OF_M (_m) ((_m)*1e3)
Definition at line 124 of file pprz_geodetic_int.h.
Referenced by lla_of_ecef_i().
#define NED_BFP_OF_REAL (_o, _i)
Value:
{       \
    (_o).x = POS_BFP_OF_REAL((_i).x);   \
    (_o).y = POS_BFP_OF_REAL((_i).y);   \
    (_o).z = POS_BFP_OF_REAL((_i).z);   \
  }
Definition at line 163 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEnu_i(), and stateCalcPositionNed_i().
#define NED_FLOAT_OF_BFP (_o, _i)
Value:
{      \
    (_o).x = POS_FLOAT_OF_BFP((_i).x);  \
    (_o).y = POS_FLOAT_OF_BFP((_i).y);  \
    (_o).z = POS_FLOAT_OF_BFP((_i).z);  \
  }
Definition at line 171 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEnu_f(), stateCalcPositionLla_f(), and stateCalcPositionNed_f().
#define RAD_OF_EM7RAD (_r) ((_r)/1e7)
Definition at line 127 of file pprz_geodetic_int.h.
Referenced by ecef_of_lla_i(), and ltp_of_ecef_rmat_from_lla_i().
#define VECT3_ENU_OF_NED (_o, _i)
Value:
{   \
    (_o).x = (_i).y;                    \
    (_o).y = (_i).x;                    \
    (_o).z = -(_i).z;                   \
  }
Definition at line 129 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionEnu_f(), and stateCalcSpeedEnu_f().
#define VECT3_NED_OF_ENU (_o, _i) VECT3_ENU_OF_NED(_o,_i)
Definition at line 135 of file pprz_geodetic_int.h.
Referenced by stateCalcPositionNed_f(), and stateCalcSpeedNed_f().
Function Documentation
void ecef_of_enu_point_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct EnuCoor_i * enu)
Convert a point in local ENU to ECEF.
Parameters
[out] ecef ECEF point in cm
[in] def local coordinate system definition
[in] enu ENU point in cm
Definition at line 187 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, ecef_of_enu_vect_i(), and INT32_VECT3_ADD.
Referenced by ecef_of_ned_point_i().
void ecef_of_enu_pos_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct EnuCoor_i * enu)
Convert a local ENU position to ECEF.
Parameters
[out] ecef ECEF position in cm
[in] def local coordinate system definition
[in] enu ENU position in meter << INT32_POS_FRAC
Definition at line 210 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, ecef_of_enu_vect_i(), INT32_POS_FRAC, INT32_VECT3_ADD, INT32_VECT3_RSHIFT, and VECT3_SMUL.
Referenced by ecef_of_ned_pos_i().
void ecef_of_enu_vect_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct EnuCoor_i * enu)
Definition at line 156 of file pprz_geodetic_int.c.
References HIGH_RES_TRIG_FRAC, LtpDef_i::ltp_of_ecef, Int32Mat33::m, EcefCoor_i::x, EnuCoor_i::x, EcefCoor_i::y, EnuCoor_i::y, EcefCoor_i::z, and EnuCoor_i::z.
Referenced by ecef_of_enu_point_i(), ecef_of_enu_pos_i(), and ecef_of_ned_vect_i().
void ecef_of_lla_i (struct EcefCoor_i * out, struct LlaCoor_i * in)
Definition at line 284 of file pprz_geodetic_int.c.
References LlaCoor_d::alt, LlaCoor_i::alt, CM_OF_M, ecef_of_lla_d(), LlaCoor_d::lat, LlaCoor_i::lat, LlaCoor_d::lon, LlaCoor_i::lon, M_OF_MM, RAD_OF_EM7RAD, EcefCoor_d::x, EcefCoor_i::x, EcefCoor_d::y, EcefCoor_i::y, EcefCoor_d::z, and EcefCoor_i::z.
Referenced by enu_of_lla_point_i(), enu_of_lla_vect_i(), ins_init(), ins_init_origin_from_flightplan(), ltp_def_from_lla_i(), ned_of_lla_point_i(), ned_of_lla_vect_i(), stateCalcPositionEcef_i(), stateCalcPositionEnu_f(), and stateCalcPositionNed_f().
void ecef_of_ned_point_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct NedCoor_i * ned)
Convert a point in local NED to ECEF.
Parameters
[out] ecef ECEF point in cm
[in] def local coordinate system definition
[in] ned NED point in cm
Definition at line 198 of file pprz_geodetic_int.c.
References ecef_of_enu_point_i(), and ENU_OF_TO_NED.
void ecef_of_ned_pos_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct NedCoor_i * ned)
Convert a local NED position to ECEF.
Parameters
[out] ecef ECEF position in cm
[in] def local coordinate system definition
[in] ned NED position in meter << INT32_POS_FRAC
Definition at line 229 of file pprz_geodetic_int.c.
References ecef_of_enu_pos_i(), and ENU_OF_TO_NED.
Referenced by stateCalcPositionEcef_f(), stateCalcPositionEcef_i(), and stateCalcPositionLla_i().
void ecef_of_ned_vect_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct NedCoor_i * ned)
Definition at line 175 of file pprz_geodetic_int.c.
References ecef_of_enu_vect_i(), and ENU_OF_TO_NED.
Referenced by stateCalcAccelEcef_i(), and stateCalcSpeedEcef_i().
void enu_of_ecef_point_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 74 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, HIGH_RES_TRIG_FRAC, LtpDef_i::ltp_of_ecef, Int32Mat33::m, VECT3_DIFF, EcefCoor_i::x, EnuCoor_i::x, EcefCoor_i::y, EnuCoor_i::y, EcefCoor_i::z, and EnuCoor_i::z.
Referenced by enu_of_ecef_pos_i(), enu_of_lla_point_i(), and ned_of_ecef_point_i().
void enu_of_ecef_pos_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Convert a ECEF position to local ENU.
Parameters
[out] enu ENU position in meter << INT32_POS_FRAC
[in] def local coordinate system definition
[in] ecef ECEF position in cm
Definition at line 106 of file pprz_geodetic_int.c.
References enu_of_ecef_point_i(), INT32_POS_FRAC, INT32_VECT3_LSHIFT, and VECT3_SDIV.
Referenced by ned_of_ecef_pos_i(), stateCalcPositionEnu_f(), and stateCalcPositionEnu_i().
void enu_of_ecef_vect_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 131 of file pprz_geodetic_int.c.
References HIGH_RES_TRIG_FRAC, LtpDef_i::ltp_of_ecef, Int32Mat33::m, EcefCoor_i::x, EnuCoor_i::x, EcefCoor_i::y, EnuCoor_i::y, EcefCoor_i::z, and EnuCoor_i::z.
Referenced by enu_of_lla_vect_i(), ned_of_ecef_vect_i(), and stateCalcSpeedEnu_i().
void enu_of_lla_point_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 236 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and enu_of_ecef_point_i().
Referenced by nav_move_waypoint_lla(), and stateCalcPositionEnu_i().
void enu_of_lla_vect_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 248 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and enu_of_ecef_vect_i().
void lla_of_ecef_i (struct LlaCoor_i * out, struct EcefCoor_i * in)
Definition at line 267 of file pprz_geodetic_int.c.
References LlaCoor_d::alt, LlaCoor_i::alt, EM7RAD_OF_RAD, LlaCoor_d::lat, LlaCoor_i::lat, lla_of_ecef_d(), LlaCoor_d::lon, LlaCoor_i::lon, M_OF_CM, MM_OF_M, EcefCoor_d::x, EcefCoor_i::x, EcefCoor_d::y, EcefCoor_i::y, EcefCoor_d::z, and EcefCoor_i::z.
Referenced by ltp_def_from_ecef_i(), and stateCalcPositionLla_i().
void ltp_def_from_ecef_i (struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 52 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, LtpDef_i::lla, lla_of_ecef_i(), LtpDef_i::ltp_of_ecef, ltp_of_ecef_rmat_from_lla_i(), and VECT3_COPY.
Referenced by gps_skytraq_read_message(), ins_init(), ins_init_origin_from_flightplan(), and ins_update_gps().
void ltp_def_from_lla_i (struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 63 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, ecef_of_lla_i(), LtpDef_i::lla, LLA_COPY, LtpDef_i::ltp_of_ecef, and ltp_of_ecef_rmat_from_lla_i().
void ltp_of_ecef_rmat_from_lla_i (struct Int32Mat33 * ltp_of_ecef, struct LlaCoor_i * lla)
Definition at line 27 of file pprz_geodetic_int.c.
References BFP_OF_REAL, HIGH_RES_TRIG_FRAC, LlaCoor_i::lat, LlaCoor_i::lon, Int32Mat33::m, and RAD_OF_EM7RAD.
Referenced by ltp_def_from_ecef_i(), and ltp_def_from_lla_i().
void ned_of_ecef_point_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 94 of file pprz_geodetic_int.c.
References enu_of_ecef_point_i(), and ENU_OF_TO_NED.
Referenced by ins_update_gps(), and ned_of_lla_point_i().
void ned_of_ecef_pos_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Convert a ECEF position to local NED.
Parameters
[out] ned NED position in meter << INT32_POS_FRAC
[in] def local coordinate system definition
[in] ecef ECEF position in cm
Definition at line 125 of file pprz_geodetic_int.c.
References enu_of_ecef_pos_i(), and ENU_OF_TO_NED.
Referenced by stateCalcPositionNed_f(), and stateCalcPositionNed_i().
void ned_of_ecef_vect_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 149 of file pprz_geodetic_int.c.
References enu_of_ecef_vect_i(), and ENU_OF_TO_NED.
Referenced by gps_skytraq_read_message(), ins_update_gps(), ned_of_lla_vect_i(), stateCalcAccelNed_i(), stateCalcHorizontalSpeedNorm_i(), and stateCalcSpeedNed_i().
void ned_of_lla_point_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 242 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and ned_of_ecef_point_i().
Referenced by stateCalcPositionNed_i().
void ned_of_lla_vect_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 254 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and ned_of_ecef_vect_i().