Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot.h File Reference
autopilot.h File Reference
Autopilot modes.
#include "std.h"
#include "led.h"
#include "generated/airframe.h"
#include "subsystems/ins.h"
Macros
#define AP_MODE_FAILSAFE 0
#define AP_MODE_KILL 1
#define AP_MODE_RATE_DIRECT 2
#define AP_MODE_ATTITUDE_DIRECT 3
#define AP_MODE_RATE_RC_CLIMB 4
#define AP_MODE_ATTITUDE_RC_CLIMB 5
#define AP_MODE_ATTITUDE_CLIMB 6
#define AP_MODE_RATE_Z_HOLD 7
#define AP_MODE_ATTITUDE_Z_HOLD 8
#define AP_MODE_HOVER_DIRECT 9
#define AP_MODE_HOVER_CLIMB 10
#define AP_MODE_HOVER_Z_HOLD 11
#define AP_MODE_NAV 12
#define AP_MODE_RC_DIRECT 13
#define AP_MODE_CARE_FREE_DIRECT 14
#define AP_MODE_FORWARD 15
#define MODE_MANUAL AP_MODE_RATE_DIRECT
Default RC mode.
#define MODE_AUTO1 AP_MODE_ATTITUDE_DIRECT
#define MODE_AUTO2 AP_MODE_ATTITUDE_Z_HOLD
#define THRESHOLD_1_PPRZ (MIN_PPRZ / 2)
#define THRESHOLD_2_PPRZ (MAX_PPRZ / 2)
#define AP_MODE_OF_PPRZ(_rc, _mode)
#define autopilot_KillThrottle(_kill)
#define autopilot_SetPowerSwitch(_v)
#define SetRotorcraftCommands(_cmd, _in_flight,_motor_on)
Set Rotorcraft commands.
#define THRESHOLD_GROUND_DETECT 25.0
Z-acceleration threshold to detect ground in m/s^2.
Functions
void autopilot_init (void)
Autopilot inititalization.
void autopilot_periodic (void)
void autopilot_on_rc_frame (void)
void autopilot_set_mode (uint8_t new_autopilot_mode)
void autopilot_set_motors_on (bool_t motors_on)
void autopilot_check_in_flight (bool_t motors_on)
static void DetectGroundEvent (void)
Ground detection based on vertical acceleration.
Variables
uint8_t autopilot_mode
uint8_t autopilot_mode_auto2
bool_t autopilot_motors_on
bool_t autopilot_in_flight
bool_t kill_throttle
bool_t autopilot_rc
bool_t autopilot_power_switch
bool_t autopilot_ground_detected
bool_t autopilot_detect_ground_once
uint16_t autopilot_flight_time
flight time in seconds.
Detailed Description
Autopilot modes.
Definition in file autopilot.h.
Macro Definition Documentation
#define AP_MODE_ATTITUDE_CLIMB 6
Definition at line 45 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_ATTITUDE_DIRECT 3
Definition at line 42 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_ATTITUDE_RC_CLIMB 5
Definition at line 44 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_ATTITUDE_Z_HOLD 8
Definition at line 47 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_CARE_FREE_DIRECT 14
Definition at line 53 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_FAILSAFE 0
Definition at line 39 of file autopilot.h.
Referenced by autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), DetectGroundEvent(), and failsafe_check().
#define AP_MODE_FORWARD 15
Definition at line 54 of file autopilot.h.
Referenced by autopilot_set_mode(), stabilization_attitude_read_rc_setpoint_eulers(), and stabilization_attitude_read_rc_setpoint_eulers_f().
#define AP_MODE_HOVER_CLIMB 10
Definition at line 49 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_HOVER_DIRECT 9
Definition at line 48 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_HOVER_Z_HOLD 11
Definition at line 50 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_KILL 1
Definition at line 40 of file autopilot.h.
Referenced by autopilot_arming_check_motors_on(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), and failsafe_check().
#define AP_MODE_NAV 12
Definition at line 51 of file autopilot.h.
Referenced by autopilot_on_rc_frame(), autopilot_set_mode(), and failsafe_check().
#define AP_MODE_OF_PPRZ (_rc, _mode)
Value:
{               \
    if      (_rc > THRESHOLD_2_PPRZ)                 \
      _mode = autopilot_mode_auto2;                 \
    else if (_rc > THRESHOLD_1_PPRZ)          \
      _mode = MODE_AUTO1;                           \
    else                                            \
      _mode = MODE_MANUAL;                          \
  }
Definition at line 93 of file autopilot.h.
Referenced by autopilot_on_rc_frame().
#define AP_MODE_RATE_DIRECT 2
Definition at line 41 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_RATE_RC_CLIMB 4
Definition at line 43 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_RATE_Z_HOLD 7
Definition at line 46 of file autopilot.h.
Referenced by autopilot_set_mode().
#define AP_MODE_RC_DIRECT 13
Definition at line 52 of file autopilot.h.
Referenced by autopilot_set_mode().
#define autopilot_KillThrottle (_kill)
Value:
{ \
    if (_kill)                          \
      autopilot_set_motors_on(FALSE);   \
    else                                \
      autopilot_set_motors_on(TRUE);    \
  }
Definition at line 102 of file autopilot.h.
#define autopilot_SetPowerSwitch (_v)
Value:
{   \
    autopilot_power_switch = _v;    \
  }
Definition at line 116 of file autopilot.h.
#define MODE_AUTO1 AP_MODE_ATTITUDE_DIRECT
Definition at line 83 of file autopilot.h.
#define MODE_AUTO2 AP_MODE_ATTITUDE_Z_HOLD
Definition at line 86 of file autopilot.h.
Referenced by autopilot_init().
#define MODE_MANUAL AP_MODE_RATE_DIRECT
Default RC mode.
Definition at line 80 of file autopilot.h.
Referenced by autopilot_arming_check_motors_on(), and autopilot_arming_set().
#define SetRotorcraftCommands (_cmd, _in_flight, _motor_on)
Value:
{ \
  if (!(_in_flight)) { _cmd[COMMAND_YAW] = 0; }               \
  if (!(_motor_on)) { _cmd[COMMAND_THRUST] = 0; }             \
  commands[COMMAND_ROLL] = _cmd[COMMAND_ROLL];                \
  commands[COMMAND_PITCH] = _cmd[COMMAND_PITCH];              \
  commands[COMMAND_YAW] = _cmd[COMMAND_YAW];                  \
  commands[COMMAND_THRUST] = _cmd[COMMAND_THRUST];            \
}
Set Rotorcraft commands.
Limit thrust and/or yaw depending of the in_flight and motors_on flag status
Definition at line 126 of file autopilot.h.
Referenced by autopilot_periodic().
#define THRESHOLD_1_PPRZ (MIN_PPRZ / 2)
Definition at line 90 of file autopilot.h.
#define THRESHOLD_2_PPRZ (MAX_PPRZ / 2)
Definition at line 91 of file autopilot.h.
#define THRESHOLD_GROUND_DETECT 25.0
Z-acceleration threshold to detect ground in m/s^2.
Definition at line 146 of file autopilot.h.
Referenced by DetectGroundEvent().
Function Documentation
void autopilot_check_in_flight (bool_t motors_on)
Definition at line 368 of file autopilot.c.
References autopilot_in_flight, autopilot_in_flight_counter, AUTOPILOT_IN_FLIGHT_MIN_ACCEL, AUTOPILOT_IN_FLIGHT_MIN_SPEED, AUTOPILOT_IN_FLIGHT_MIN_THRUST, AUTOPILOT_IN_FLIGHT_TIME, FALSE, stabilization_cmd, stateGetAccelNed_f(), stateGetSpeedNed_f(), and TRUE.
Referenced by failsafe_check().
void autopilot_init (void)
Autopilot inititalization.
Definition at line 138 of file autopilot.c.
References AP_MODE_KILL, autopilot_arming_init(), autopilot_detect_ground_once, autopilot_flight_time, autopilot_ground_detected, autopilot_in_flight, autopilot_in_flight_counter, autopilot_mode, autopilot_mode_auto2, autopilot_motors_on, autopilot_power_switch, autopilot_rc, autopilot_send_mode(), autopilot_set_mode(), FALSE, gps_lost, guidance_h_init(), guidance_v_init(), kill_throttle, lateral_mode, LATERAL_MODE_MANUAL, launch, LED_ON, MODE_AUTO2, MODE_STARTUP, nav_init(), power_switch, POWER_SWITCH_LED, pprz_mode, PPRZ_MODE_AUTO2, register_periodic_telemetry(), send_airspeed(), send_alive(), send_attitude(), send_bat(), send_desired(), send_dl_value(), send_downlink(), send_energy(), send_estimator(), send_fp(), send_rc(), send_rotorcraft_cmd(), send_rotorcraft_rc(), send_status(), stabilization_init(), and TRUE.
Referenced by init_ap(), and main_init().
void autopilot_on_rc_frame (void)
Definition at line 416 of file autopilot.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, AP_MODE_NAV, AP_MODE_OF_PPRZ, autopilot_arming_check_motors_on(), autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_set_mode(), commands, GpsIsLost(), guidance_h_read_rc(), guidance_v_read_rc(), kill_switch_is_on(), kill_throttle, radio_control, RADIO_MODE, and RadioControl::values.
Referenced by main_event(), and on_rc_message().
void autopilot_periodic (void)
Definition at line 230 of file autopilot.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, autopilot_detect_ground_once, autopilot_ground_detected, autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_set_mode(), commands_failsafe, FALSE, guidance_h_run(), guidance_v_run(), nav_periodic_task(), NAV_PRESCALER, SetCommands, SetRotorcraftCommands, and stabilization_cmd.
Referenced by main_periodic().
void autopilot_set_mode (uint8_t new_autopilot_mode)
Definition at line 272 of file autopilot.c.
References ahrs_is_aligned(), AP_MODE_ATTITUDE_CLIMB, AP_MODE_ATTITUDE_DIRECT, AP_MODE_ATTITUDE_RC_CLIMB, AP_MODE_ATTITUDE_Z_HOLD, AP_MODE_CARE_FREE_DIRECT, AP_MODE_FAILSAFE, AP_MODE_FORWARD, AP_MODE_HOVER_CLIMB, AP_MODE_HOVER_DIRECT, AP_MODE_HOVER_Z_HOLD, AP_MODE_KILL, AP_MODE_NAV, AP_MODE_RATE_DIRECT, AP_MODE_RATE_RC_CLIMB, AP_MODE_RATE_Z_HOLD, AP_MODE_RC_DIRECT, autopilot_in_flight, autopilot_in_flight_counter, autopilot_mode, autopilot_set_motors_on(), FALSE, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, guidance_h_mode_changed(), GUIDANCE_H_MODE_FORWARD, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_KILL, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_v_mode_changed(), GUIDANCE_V_MODE_CLIMB, GUIDANCE_V_MODE_HOVER, GUIDANCE_V_MODE_KILL, GUIDANCE_V_MODE_NAV, GUIDANCE_V_MODE_RC_CLIMB, GUIDANCE_V_MODE_RC_DIRECT, guidance_v_zd_sp, SPEED_BFP_OF_REAL, stabilization_attitude_set_failsafe_setpoint(), and stabilization_cmd.
Referenced by autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), and failsafe_check().
void autopilot_set_motors_on (bool_t motors_on)
Definition at line 406 of file autopilot.c.
References ahrs_is_aligned(), autopilot_arming_set(), autopilot_motors_on, FALSE, kill_throttle, and TRUE.
Referenced by actuators_ardrone_motor_status(), and autopilot_set_mode().
static void DetectGroundEvent (void) inline static
Ground detection based on vertical acceleration.
Definition at line 150 of file autopilot.h.
References AP_MODE_FAILSAFE, autopilot_detect_ground_once, autopilot_ground_detected, autopilot_mode, FALSE, stateGetAccelNed_f(), THRESHOLD_GROUND_DETECT, TRUE, and NedCoor_f::z.
Referenced by main_event().
Variable Documentation
bool_t autopilot_detect_ground_once
Definition at line 58 of file autopilot.c.
Referenced by autopilot_init(), autopilot_periodic(), and DetectGroundEvent().
uint16_t autopilot_flight_time
flight time in seconds.
Definition at line 43 of file autopilot.c.
Referenced by attitude_loop(), autopilot_init(), generic_com_periodic(), gsm_send_report_continue(), main_periodic(), monitor_task(), send_bat(), send_fp(), and telecommand_task().
bool_t autopilot_ground_detected
Definition at line 57 of file autopilot.c.
Referenced by autopilot_init(), autopilot_periodic(), DetectGroundEvent(), and nav_detect_ground().
bool_t autopilot_in_flight
Definition at line 47 of file autopilot.c.
Referenced by autopilot_check_in_flight(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), main_periodic(), nav_is_in_flight(), and send_status().
uint8_t autopilot_mode
Definition at line 44 of file autopilot.c.
Referenced by autopilot_arming_check_motors_on(), autopilot_arming_set(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), DetectGroundEvent(), event_task_fbw(), failsafe_check(), main_periodic(), send_status(), stabilization_attitude_read_rc_setpoint_eulers(), and stabilization_attitude_read_rc_setpoint_eulers_f().
uint8_t autopilot_mode_auto2
Definition at line 45 of file autopilot.c.
Referenced by autopilot_init().
bool_t autopilot_motors_on
Definition at line 51 of file autopilot.c.
Referenced by actuators_ardrone_motor_status(), autopilot_arming_check_motors_on(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_motors_on(), failsafe_check(), geo_mag_periodic(), and send_status().
bool_t autopilot_power_switch
Definition at line 55 of file autopilot.c.
Referenced by autopilot_init().
bool_t autopilot_rc
Definition at line 54 of file autopilot.c.
Referenced by autopilot_init(), and main_event().
bool_t kill_throttle
Definition at line 37 of file autopilot.c.
Referenced by attitude_loop(), autopilot_init(), autopilot_on_rc_frame(), autopilot_set_motors_on(), BungeeTakeoff(), InitializeBungeeTakeoff(), monitor_task(), send_bat(), SkidLanding(), and v_ctl_climb_loop().