Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot.c File Reference
autopilot.c File Reference
Autopilot.
#include "firmwares/rotorcraft/autopilot.h"
#include "mcu_periph/uart.h"
#include "subsystems/radio_control.h"
#include "subsystems/gps.h"
#include "subsystems/commands.h"
#include "subsystems/actuators.h"
#include "subsystems/electrical.h"
#include "subsystems/settings.h"
#include "subsystems/datalink/telemetry.h"
#include "firmwares/rotorcraft/navigation.h"
#include "firmwares/rotorcraft/guidance.h"
#include "firmwares/rotorcraft/stabilization.h"
#include "led.h"
#include "subsystems/ahrs.h"
#include "autopilot_arming_yaw.h"
Macros
#define AUTOPILOT_IN_FLIGHT_TIME 20
#define AUTOPILOT_IN_FLIGHT_MIN_SPEED 0.2
minimum vertical speed for in_flight condition in m/s
#define AUTOPILOT_IN_FLIGHT_MIN_ACCEL 2.0
minimum vertical acceleration for in_flight condition in m/s^2
#define AUTOPILOT_IN_FLIGHT_MIN_THRUST 500
minimum thrust for in_flight condition in pprz_t units
#define MODE_STARTUP AP_MODE_KILL
Functions
static int ahrs_is_aligned (void)
static void send_alive (void)
static void send_status (void)
static void send_fp (void)
static void send_rc (void)
static void send_rotorcraft_rc (void)
static void send_dl_value (void)
static void send_rotorcraft_cmd (void)
void autopilot_init (void)
Autopilot inititalization.
void autopilot_periodic (void)
void autopilot_set_mode (uint8_t new_autopilot_mode)
void autopilot_check_in_flight (bool_t motors_on)
void autopilot_set_motors_on (bool_t motors_on)
void autopilot_on_rc_frame (void)
Variables
uint8_t autopilot_mode
uint8_t autopilot_mode_auto2
bool_t autopilot_in_flight
uint32_t autopilot_in_flight_counter
uint16_t autopilot_flight_time
flight time in seconds.
bool_t autopilot_motors_on
bool_t kill_throttle
bool_t autopilot_rc
bool_t autopilot_power_switch
bool_t autopilot_ground_detected
bool_t autopilot_detect_ground_once
Detailed Description
Autopilot.
Definition in file autopilot.c.
Macro Definition Documentation
#define AUTOPILOT_IN_FLIGHT_MIN_ACCEL 2.0
minimum vertical acceleration for in_flight condition in m/s^2
Definition at line 69 of file autopilot.c.
Referenced by autopilot_check_in_flight().
#define AUTOPILOT_IN_FLIGHT_MIN_SPEED 0.2
minimum vertical speed for in_flight condition in m/s
Definition at line 64 of file autopilot.c.
Referenced by autopilot_check_in_flight().
#define AUTOPILOT_IN_FLIGHT_MIN_THRUST 500
minimum thrust for in_flight condition in pprz_t units
Definition at line 74 of file autopilot.c.
Referenced by autopilot_check_in_flight().
#define AUTOPILOT_IN_FLIGHT_TIME 20
Definition at line 60 of file autopilot.c.
Referenced by autopilot_check_in_flight().
#define MODE_STARTUP AP_MODE_KILL
Definition at line 101 of file autopilot.c.
Referenced by autopilot_init().
Function Documentation
static int ahrs_is_aligned (void) inline static
Definition at line 79 of file autopilot.c.
References ahrs, AHRS_RUNNING, and Ahrs::status.
Referenced by autopilot_set_mode(), and autopilot_set_motors_on().
void autopilot_check_in_flight (bool_t motors_on)
Definition at line 368 of file autopilot.c.
References autopilot_in_flight, autopilot_in_flight_counter, AUTOPILOT_IN_FLIGHT_MIN_ACCEL, AUTOPILOT_IN_FLIGHT_MIN_SPEED, AUTOPILOT_IN_FLIGHT_MIN_THRUST, AUTOPILOT_IN_FLIGHT_TIME, FALSE, stabilization_cmd, stateGetAccelNed_f(), stateGetSpeedNed_f(), and TRUE.
Referenced by failsafe_check().
void autopilot_init (void)
Autopilot inititalization.
Definition at line 188 of file autopilot.c.
References AP_MODE_KILL, autopilot_arming_init(), autopilot_detect_ground_once, autopilot_flight_time, autopilot_ground_detected, autopilot_in_flight, autopilot_in_flight_counter, autopilot_mode, autopilot_mode_auto2, autopilot_motors_on, autopilot_power_switch, autopilot_rc, autopilot_send_mode(), autopilot_set_mode(), FALSE, gps_lost, guidance_h_init(), guidance_v_init(), kill_throttle, lateral_mode, LATERAL_MODE_MANUAL, launch, LED_ON, MODE_AUTO2, MODE_STARTUP, nav_init(), power_switch, POWER_SWITCH_LED, pprz_mode, PPRZ_MODE_AUTO2, register_periodic_telemetry(), send_airspeed(), send_alive(), send_attitude(), send_bat(), send_desired(), send_dl_value(), send_downlink(), send_energy(), send_estimator(), send_fp(), send_rc(), send_rotorcraft_cmd(), send_rotorcraft_rc(), send_status(), stabilization_init(), and TRUE.
void autopilot_on_rc_frame (void)
Definition at line 416 of file autopilot.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, AP_MODE_NAV, AP_MODE_OF_PPRZ, autopilot_arming_check_motors_on(), autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_set_mode(), commands, GpsIsLost(), guidance_h_read_rc(), guidance_v_read_rc(), kill_switch_is_on(), kill_throttle, radio_control, RADIO_MODE, and RadioControl::values.
Referenced by main_event(), and on_rc_message().
void autopilot_periodic (void)
Definition at line 230 of file autopilot.c.
References AP_MODE_FAILSAFE, AP_MODE_KILL, autopilot_detect_ground_once, autopilot_ground_detected, autopilot_in_flight, autopilot_mode, autopilot_motors_on, autopilot_set_mode(), commands_failsafe, FALSE, guidance_h_run(), guidance_v_run(), nav_periodic_task(), NAV_PRESCALER, SetCommands, SetRotorcraftCommands, and stabilization_cmd.
Referenced by main_periodic().
void autopilot_set_mode (uint8_t new_autopilot_mode)
Definition at line 272 of file autopilot.c.
References ahrs_is_aligned(), AP_MODE_ATTITUDE_CLIMB, AP_MODE_ATTITUDE_DIRECT, AP_MODE_ATTITUDE_RC_CLIMB, AP_MODE_ATTITUDE_Z_HOLD, AP_MODE_CARE_FREE_DIRECT, AP_MODE_FAILSAFE, AP_MODE_FORWARD, AP_MODE_HOVER_CLIMB, AP_MODE_HOVER_DIRECT, AP_MODE_HOVER_Z_HOLD, AP_MODE_KILL, AP_MODE_NAV, AP_MODE_RATE_DIRECT, AP_MODE_RATE_RC_CLIMB, AP_MODE_RATE_Z_HOLD, AP_MODE_RC_DIRECT, autopilot_in_flight, autopilot_in_flight_counter, autopilot_mode, autopilot_set_motors_on(), FALSE, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, guidance_h_mode_changed(), GUIDANCE_H_MODE_FORWARD, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_KILL, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_v_mode_changed(), GUIDANCE_V_MODE_CLIMB, GUIDANCE_V_MODE_HOVER, GUIDANCE_V_MODE_KILL, GUIDANCE_V_MODE_NAV, GUIDANCE_V_MODE_RC_CLIMB, GUIDANCE_V_MODE_RC_DIRECT, guidance_v_zd_sp, SPEED_BFP_OF_REAL, stabilization_attitude_set_failsafe_setpoint(), and stabilization_cmd.
Referenced by autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), and failsafe_check().
void autopilot_set_motors_on (bool_t motors_on)
Definition at line 406 of file autopilot.c.
References ahrs_is_aligned(), autopilot_arming_set(), autopilot_motors_on, FALSE, kill_throttle, and TRUE.
Referenced by actuators_ardrone_motor_status(), and autopilot_set_mode().
static void send_alive (void) static
Definition at line 105 of file autopilot.c.
References DefaultChannel, and DefaultDevice.
Referenced by autopilot_init().
static void send_dl_value (void) static
Definition at line 175 of file autopilot.c.
References DefaultChannel, and DefaultDevice.
Referenced by autopilot_init().
static void send_fp (void) static
Definition at line 127 of file autopilot.c.
References autopilot_flight_time, DefaultChannel, DefaultDevice, guidance_h_heading_sp, guidance_h_pos_sp, guidance_v_z_sp, FloatEulers::phi, FloatEulers::psi, stabilization_cmd, stateGetNedToBodyEulers_i(), stateGetPositionEnu_i(), stateGetSpeedEnu_i(), FloatEulers::theta, Int32Vect2::x, and Int32Vect2::y.
Referenced by autopilot_init().
static void send_rc (void) static
Definition at line 148 of file autopilot.c.
References DefaultChannel, DefaultDevice, radio_control, RADIO_CONTROL_NB_CHANNEL, and RadioControl::values.
Referenced by autopilot_init(), and init_fbw().
static void send_rotorcraft_cmd (void) static
Definition at line 179 of file autopilot.c.
References DefaultChannel, DefaultDevice, and stabilization_cmd.
Referenced by autopilot_init().
static void send_rotorcraft_rc (void) static
Definition at line 152 of file autopilot.c.
References DefaultChannel, DefaultDevice, radio_control, RADIO_KILL_SWITCH, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RADIO_YAW, RadioControl::status, and RadioControl::values.
Referenced by autopilot_init().
static void send_status (void) static
Definition at line 109 of file autopilot.c.
References autopilot_in_flight, autopilot_mode, autopilot_motors_on, DefaultChannel, DefaultDevice, electrical, GpsState::fix, RadioControl::frame_rate, gps, GPS_FIX_NONE, guidance_h_mode, guidance_v_mode, sys_time::nb_sec, radio_control, RadioControl::status, and Electrical::vsupply.
Referenced by ahrs_init(), and autopilot_init().
Variable Documentation
bool_t autopilot_detect_ground_once
Definition at line 58 of file autopilot.c.
Referenced by autopilot_init(), autopilot_periodic(), and DetectGroundEvent().
uint16_t autopilot_flight_time
flight time in seconds.
Definition at line 49 of file autopilot.c.
bool_t autopilot_ground_detected
Definition at line 57 of file autopilot.c.
Referenced by autopilot_init(), autopilot_periodic(), DetectGroundEvent(), and nav_detect_ground().
bool_t autopilot_in_flight
Definition at line 47 of file autopilot.c.
Referenced by autopilot_check_in_flight(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), main_periodic(), nav_is_in_flight(), and send_status().
uint32_t autopilot_in_flight_counter
Definition at line 48 of file autopilot.c.
Referenced by autopilot_check_in_flight(), autopilot_init(), and autopilot_set_mode().
uint8_t autopilot_mode
Definition at line 44 of file autopilot.c.
Referenced by autopilot_arming_check_motors_on(), autopilot_arming_set(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_mode(), DetectGroundEvent(), event_task_fbw(), failsafe_check(), main_periodic(), send_status(), stabilization_attitude_read_rc_setpoint_eulers(), and stabilization_attitude_read_rc_setpoint_eulers_f().
uint8_t autopilot_mode_auto2
Definition at line 45 of file autopilot.c.
Referenced by autopilot_init().
bool_t autopilot_motors_on
Definition at line 51 of file autopilot.c.
Referenced by actuators_ardrone_motor_status(), autopilot_arming_check_motors_on(), autopilot_init(), autopilot_on_rc_frame(), autopilot_periodic(), autopilot_set_motors_on(), failsafe_check(), geo_mag_periodic(), and send_status().
bool_t autopilot_power_switch
Definition at line 55 of file autopilot.c.
Referenced by autopilot_init().
bool_t autopilot_rc
Definition at line 54 of file autopilot.c.
Referenced by autopilot_init(), and main_event().
bool_t kill_throttle
Definition at line 52 of file autopilot.c.