Paparazzi UAS: sw/airborne/subsystems/radio_control/sbus.c File Reference
sbus.c File Reference
Futaba SBUS decoder.
#include "subsystems/radio_control.h"
#include "subsystems/radio_control/sbus.h"
#include <BOARD_CONFIG>
#include "mcu_periph/uart.h"
#include "mcu_periph/gpio.h"
#include <string.h>
Macros
#define SBUS_START_BYTE 0x0f
#define SBUS_END_BYTE 0x00
#define SBUS_BIT_PER_CHANNEL 11
#define SBUS_BIT_PER_BYTE 8
#define SBUS_FLAGS_BYTE 22
#define SBUS_FRAME_LOST_BIT 2
#define SBUS_STATUS_UNINIT 0
#define SBUS_STATUS_GOT_START 1
#define RC_SET_POLARITY gpio_set
Set polarity using RC_POLARITY_GPIO.
Functions
void radio_control_impl_init (void)
static void decode_sbus_buffer (const uint8_t *src, uint16_t *dst, bool_t *available)
Decode the raw buffer.
void sbus_decode_event (void)
Decoding event function.
Variables
struct _sbus sbus
SBUS struct.
Detailed Description
Futaba SBUS decoder.
Definition in file sbus.c.
Macro Definition Documentation
#define RC_SET_POLARITY gpio_set
Set polarity using RC_POLARITY_GPIO.
SBUS signal has a reversed polarity compared to normal UART this allows to using hardware UART peripheral by changing the input signal polarity. Setting this gpio ouput high inverts the signal, output low sets it to normal polarity.
Definition at line 55 of file sbus.c.
Referenced by radio_control_impl_init().
#define SBUS_BIT_PER_BYTE 8
Definition at line 40 of file sbus.c.
Referenced by decode_sbus_buffer().
#define SBUS_BIT_PER_CHANNEL 11
Definition at line 39 of file sbus.c.
Referenced by decode_sbus_buffer().
#define SBUS_END_BYTE 0x00
Definition at line 38 of file sbus.c.
Referenced by sbus_decode_event().
#define SBUS_FLAGS_BYTE 22
Definition at line 41 of file sbus.c.
Referenced by decode_sbus_buffer().
#define SBUS_FRAME_LOST_BIT 2
Definition at line 42 of file sbus.c.
Referenced by decode_sbus_buffer().
#define SBUS_START_BYTE 0x0f
Definition at line 37 of file sbus.c.
Referenced by sbus_decode_event().
#define SBUS_STATUS_GOT_START 1
Definition at line 45 of file sbus.c.
Referenced by sbus_decode_event().
#define SBUS_STATUS_UNINIT 0
Definition at line 44 of file sbus.c.
Referenced by radio_control_impl_init(), and sbus_decode_event().
Function Documentation
static void decode_sbus_buffer (const uint8_t * src, uint16_t * dst, bool_t * available) static
Decode the raw buffer.
Definition at line 102 of file sbus.c.
References channel, SBUS_BIT_PER_BYTE, SBUS_BIT_PER_CHANNEL, SBUS_FLAGS_BYTE, SBUS_FRAME_LOST_BIT, and SBUS_NB_CHANNEL.
Referenced by sbus_decode_event().
void radio_control_impl_init (void)
Definition at line 80 of file sbus.c.
References B100000, FALSE, _sbus::frame_available, gpio_setup_output(), RC_POLARITY_GPIO_PIN, RC_POLARITY_GPIO_PORT, RC_SET_POLARITY, register_periodic_telemetry(), sbus, SBUS_STATUS_UNINIT, _sbus::status, uart_periph_set_baudrate(), uart_periph_set_bits_stop_parity(), UBITS_8, UPARITY_EVEN, and USTOP_2.
void sbus_decode_event (void)
Decoding event function.
Definition at line 136 of file sbus.c.
References _sbus::buffer, decode_sbus_buffer(), _sbus::frame_available, _sbus::idx, _sbus::pulses, sbus, SBUS_BUF_LENGTH, SBUS_END_BYTE, SBUS_START_BYTE, SBUS_STATUS_GOT_START, SBUS_STATUS_UNINIT, _sbus::status, uart_char_available(), and uart_getch().
Variable Documentation
struct _sbus sbus
SBUS struct.
Definition at line 60 of file sbus.c.
Referenced by radio_control_impl_init(), and sbus_decode_event().