Paparazzi UAS: sw/airborne/subsystems/radio_control/sbus.h File Reference
sbus.h File Reference
Futaba SBUS decoder.
#include "std.h"
#include "generated/radio.h"
Data Structures
struct _sbus
SBUS structure.
Macros
#define RC_PPM_TICKS_OF_USEC(_v) (_v)
Dummy macro to use radio.h file.
#define RC_PPM_SIGNED_TICKS_OF_USEC(_v) (_v)
#define USEC_OF_RC_PPM_TICKS(_v) (_v)
#define SBUS_BUF_LENGTH 24
Generated code holding the description of a given transmitter.
#define SBUS_NB_CHANNEL 16
#define RADIO_CONTROL_NB_CHANNEL SBUS_NB_CHANNEL
#define RadioControlEvent(_received_frame_handler)
Event macro with handler callback.
Functions
void sbus_decode_event (void)
Decoding event function.
Variables
struct _sbus sbus
SBUS struct.
Detailed Description
Futaba SBUS decoder.
Definition in file sbus.h.
Macro Definition Documentation
#define RADIO_CONTROL_NB_CHANNEL SBUS_NB_CHANNEL
Definition at line 56 of file sbus.h.
#define RadioControlEvent (_received_frame_handler)
Value:
{  \
  sbus_decode_event();                                \
  if (sbus.frame_available) {                         \
    radio_control.frame_cpt++;                        \
    radio_control.time_since_last_frame = 0;          \
    if (radio_control.radio_ok_cpt > 0) {             \
      radio_control.radio_ok_cpt--;                   \
    } else {                                          \
      radio_control.status = RC_OK;                   \
      NormalizePpmIIR(sbus.pulses,radio_control);     \
      _received_frame_handler();                      \
    }                                                 \
    sbus.frame_available = FALSE;                     \
  }                                                   \
}
Event macro with handler callback.
Definition at line 79 of file sbus.h.
#define RC_PPM_SIGNED_TICKS_OF_USEC (_v) (_v)
Definition at line 36 of file sbus.h.
#define RC_PPM_TICKS_OF_USEC (_v) (_v)
Dummy macro to use radio.h file.
Definition at line 35 of file sbus.h.
#define SBUS_BUF_LENGTH 24
Generated code holding the description of a given transmitter.
Define number of channels.
SBUS frame always have 16 channels but only the X first one will be available depending of the RC transmitter. The radio XML file is used to assign the input values to RC channels.
Definition at line 54 of file sbus.h.
Referenced by sbus_decode_event().
#define SBUS_NB_CHANNEL 16
Definition at line 55 of file sbus.h.
Referenced by decode_sbus_buffer().
#define USEC_OF_RC_PPM_TICKS (_v) (_v)
Definition at line 37 of file sbus.h.
Function Documentation
void sbus_decode_event (void)
Decoding event function.
Definition at line 136 of file sbus.c.
References _sbus::buffer, decode_sbus_buffer(), _sbus::frame_available, _sbus::idx, _sbus::pulses, sbus, SBUS_BUF_LENGTH, SBUS_END_BYTE, SBUS_START_BYTE, SBUS_STATUS_GOT_START, SBUS_STATUS_UNINIT, _sbus::status, uart_char_available(), and uart_getch().
Variable Documentation
struct _sbus sbus
SBUS struct.
Definition at line 60 of file sbus.c.
Referenced by radio_control_impl_init(), and sbus_decode_event().