Paparazzi UAS: sw/airborne/subsystems/navigation/spiral.h File Reference
spiral.h File Reference
Fixedwing navigation in a spiral/helix from Uni Stuttgart.
#include "std.h"
Functions
bool_t SpiralNav (void)
bool_t InitializeSpiral (uint8_t CenterWP, uint8_t EdgeWP, float StartRad, float IncRad, float Segments, float ZKoord)
Detailed Description
Fixedwing navigation in a spiral/helix from Uni Stuttgart.
Definition in file spiral.h.
Function Documentation
bool_t InitializeSpiral (uint8_t CenterWP, uint8_t EdgeWP, float StartRad, float IncRad, float Segments, float ZKoord)
Definition at line 75 of file spiral.c.
References Alphalimit, Center, CSpiralStatus, DistanceFromCenter, Edge, EdgeCurrentX, EdgeCurrentY, FALSE, FlyFromX, FlyFromY, IRad, MIN_CIRCLE_RADIUS, nav_radius_min, Outside, Segmente, Spiralradius, SRad, stateGetPositionEnu_f(), TransCurrentX, TransCurrentY, TransCurrentZ, WaypointX, WaypointY, EnuCoor_f::x, EnuCoor_f::y, EnuCoor_f::z, and ZPoint.
bool_t SpiralNav (void)
Definition at line 111 of file spiral.c.
References Alphalimit, Center, Circle, CSpiralStatus, dc_cam_angle, dc_cam_tracing, dc_Circle, dc_send_command(), DC_SHOOT, dc_stop(), DistanceFromCenter, FlyFromX, FlyFromY, IncSpiral, IRad, LastCircleX, LastCircleY, nav_approaching_xy(), nav_circle_XY(), nav_route_xy(), Outside, Segmente, Spiralradius, SRad, StartCircle, stateGetPositionEnu_f(), TransCurrentX, TransCurrentY, TransCurrentZ, TRUE, WaypointX, WaypointY, point::x, EnuCoor_f::x, point::y, EnuCoor_f::y, EnuCoor_f::z, and ZPoint.