Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_int.h File Reference
stabilization_attitude_ref_quat_int.h File Reference
Rotorcraft attitude reference generation.
#include "stabilization_attitude_ref_int.h"
Functions
void stabilization_attitude_ref_enter (void)
Variables
struct Int32Quat stab_att_sp_quat
with INT32_QUAT_FRAC
struct Int32Quat stab_att_ref_quat
with INT32_QUAT_FRAC
Detailed Description
Rotorcraft attitude reference generation.
(quaternion int version)
Definition in file stabilization_attitude_ref_quat_int.h.
Function Documentation
void stabilization_attitude_ref_enter (void)
Definition at line 51 of file stabilization_attitude_ref_euler_float.c.
References INT32_ANGLE_FRAC, INT32_EULERS_RSHIFT, INT32_QUAT_OF_EULERS, INT32_QUAT_WRAP_SHORTEST, REF_ANGLE_FRAC, reset_psi_ref_from_body(), stab_att_ref_accel, stab_att_ref_euler, stab_att_ref_quat, stab_att_ref_rate, and update_ref_quat_from_eulers().
Referenced by stabilization_attitude_enter().
Variable Documentation
struct Int32Quat stab_att_ref_quat
with INT32_QUAT_FRAC
Definition at line 46 of file stabilization_attitude_ref_quat_float.c.
struct Int32Quat stab_att_sp_quat
with INT32_QUAT_FRAC
Definition at line 44 of file stabilization_attitude_ref_quat_float.c.