Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_transformations.h File Reference
stabilization_attitude_quat_transformations.h File Reference
Quaternion transformation functions.
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_int.h"
Functions
void quat_from_rpy_cmd_i (struct Int32Quat *quat, struct Int32Eulers *rpy)
void quat_from_rpy_cmd_f (struct FloatQuat *quat, struct FloatEulers *rpy)
void quat_from_earth_cmd_i (struct Int32Quat *quat, struct Int32Vect2 *cmd, int32_t heading)
void quat_from_earth_cmd_f (struct FloatQuat *quat, struct FloatVect2 *cmd, float heading)
Detailed Description
Quaternion transformation functions.
Definition in file stabilization_attitude_quat_transformations.h.
Function Documentation
void quat_from_earth_cmd_f (struct FloatQuat * quat, struct FloatVect2 * cmd, float heading)
Todo:
optimize yaw angle calculation
Definition at line 60 of file stabilization_attitude_quat_transformations.c.
References FLOAT_QUAT_COMP, FLOAT_QUAT_NORMALIZE, FLOAT_QUAT_OF_ORIENTATION_VECT, FLOAT_QUAT_WRAP_SHORTEST, FLOAT_RMAT_OF_QUAT, FLOAT_VECT3_DIFF, FLOAT_VECT3_DOT_PRODUCT, FLOAT_VECT3_NORM, FLOAT_VECT3_SMUL, FloatRMat::m, QUAT_ASSIGN, VECT3_ASSIGN, VECT3_CROSS_PRODUCT, FloatVect2::x, and FloatVect2::y.
Referenced by quat_from_earth_cmd_i(), and stabilization_attitude_set_earth_cmd_i().
void quat_from_earth_cmd_i (struct Int32Quat * quat, struct Int32Vect2 * cmd, int32_t heading)
Definition at line 46 of file stabilization_attitude_quat_transformations.c.
References ANGLE_FLOAT_OF_BFP, QUAT_BFP_OF_REAL, quat_from_earth_cmd_f(), FloatVect2::x, Int32Vect2::x, FloatVect2::y, and Int32Vect2::y.
Referenced by stabilization_attitude_set_earth_cmd_i().
void quat_from_rpy_cmd_f (struct FloatQuat * quat, struct FloatEulers * rpy)
Definition at line 36 of file stabilization_attitude_quat_transformations.c.
References FLOAT_QUAT_OF_ORIENTATION_VECT, FloatEulers::phi, FloatEulers::psi, and FloatEulers::theta.
Referenced by quat_from_rpy_cmd_i(), and stabilization_attitude_set_rpy_setpoint_i().
void quat_from_rpy_cmd_i (struct Int32Quat * quat, struct Int32Eulers * rpy)
Definition at line 28 of file stabilization_attitude_quat_transformations.c.
References EULERS_FLOAT_OF_BFP, QUAT_BFP_OF_REAL, and quat_from_rpy_cmd_f().
Referenced by stabilization_attitude_set_rpy_setpoint_i().