Paparazzi UAS: sw/airborne/subsystems/datalink/superbitrf.c File Reference
superbitrf.c File Reference
DSM2 and DSMX datalink implementation for the cyrf6936 2.4GHz radio chip trough SPI.
#include "subsystems/datalink/superbitrf.h"
#include <string.h>
#include "paparazzi.h"
#include "mcu_periph/spi.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/gpio.h"
Macros
#define SUPERBITRF_SPI_DEV spi1
#define SUPERBITRF_RST_PORT GPIOC
#define SUPERBITRF_RST_PIN GPIO12
#define SUPERBITRF_DRDY_PORT GPIOB
#define SUPERBITRF_DRDY_PIN GPIO1
#define SUPERBITRF_FORCE_DSM2 TRUE
Functions
PRINT_CONFIG_VAR (SUPERBITRF_SPI_DEV)
PRINT_CONFIG_VAR (SUPERBITRF_RST_PORT)
PRINT_CONFIG_VAR (SUPERBITRF_RST_PIN)
PRINT_CONFIG_VAR (SUPERBITRF_DRDY_PORT)
PRINT_CONFIG_VAR (SUPERBITRF_DRDY_PIN)
PRINT_CONFIG_VAR (SUPERBITRF_FORCE_DSM2)
static void superbitrf_radio_to_channels (uint8_t *data, uint8_t nb_channels, bool_t is_11bit, int16_t *channels)
Parse a radio channel packet.
static void superbitrf_receive_packet_cb (bool_t error, uint8_t status, uint8_t packet[])
When we receive a packet this callback is called.
static void superbitrf_send_packet_cb (bool_t error)
static void superbitrf_gen_dsmx_channels (void)
Generate the channels.
void superbitrf_init (void)
Initialize the superbitrf.
void superbitrf_event (void)
The superbitrf on event call.
Variables
struct SuperbitRF superbitrf
static const uint8_t cyrf_stratup_config [][2]
static const uint8_t cyrf_bind_config [][2]
static const uint8_t cyrf_transfer_config [][2]
const uint8_t cyrf_abort_receive [][2]
const uint8_t cyrf_start_receive [][2]
static const uint8_t pn_codes [5][9][8]
static const uint8_t pn_bind [] = { 0x98, 0x88, 0x1B, 0xE4, 0x30, 0x79, 0x03, 0x84 }
Detailed Description
DSM2 and DSMX datalink implementation for the cyrf6936 2.4GHz radio chip trough SPI.
Definition in file superbitrf.c.
Macro Definition Documentation
#define SUPERBITRF_DRDY_PIN GPIO1
Definition at line 57 of file superbitrf.c.
Referenced by superbitrf_event(), and superbitrf_init().
#define SUPERBITRF_DRDY_PORT GPIOB
Definition at line 53 of file superbitrf.c.
Referenced by superbitrf_event(), and superbitrf_init().
#define SUPERBITRF_FORCE_DSM2 TRUE
Definition at line 63 of file superbitrf.c.
Referenced by superbitrf_event(), and superbitrf_receive_packet_cb().
#define SUPERBITRF_RST_PIN GPIO12
Definition at line 47 of file superbitrf.c.
Referenced by superbitrf_init().
#define SUPERBITRF_RST_PORT GPIOC
Definition at line 43 of file superbitrf.c.
Referenced by superbitrf_init().
#define SUPERBITRF_SPI_DEV spi1
Definition at line 37 of file superbitrf.c.
Referenced by superbitrf_init().
Function Documentation
PRINT_CONFIG_VAR (SUPERBITRF_SPI_DEV)
Referenced by electrical_init(), and superbitrf_event().
PRINT_CONFIG_VAR (SUPERBITRF_RST_PORT)
PRINT_CONFIG_VAR (SUPERBITRF_RST_PIN)
PRINT_CONFIG_VAR (SUPERBITRF_DRDY_PORT)
PRINT_CONFIG_VAR (SUPERBITRF_DRDY_PIN)
PRINT_CONFIG_VAR (SUPERBITRF_FORCE_DSM2)
void superbitrf_event (void)
The superbitrf on event call.
Definition at line 230 of file superbitrf.c.
References SuperbitRF::bind_mfg_id, SuperbitRF::bind_mfg_id32, SuperbitRF::channel, SuperbitRF::channel_idx, SuperbitRF::channels, SuperbitRF::crc_seed, SuperbitRF::cyrf6936, CYRF6936_IDLE, cyrf6936_multi_write(), cyrf6936_read_rx_irq_status_packet(), cyrf6936_send(), cyrf6936_write(), cyrf6936_write_chan_sop_data_crc(), cyrf_abort_receive, cyrf_bind_config, CYRF_CHANNEL, CYRF_RXC_IRQ, CYRF_RXE_IRQ, cyrf_start_receive, cyrf_stratup_config, cyrf_transfer_config, CYRF_TXC_IRQ, CYRF_TXE_IRQ, SuperbitRF::data_col, FALSE, get_sys_time_usec(), gpio_get(), Cyrf6936::has_irq, SuperbitRF::irq_count, IS_DSM2, IS_DSMX, SuperbitRF::num_channels, SuperbitRF::packet_loss, SuperbitRF::packet_loss_bit, pn_bind, pn_codes, PRINT_CONFIG_VAR(), SuperbitRF::protocol, SuperbitRF::resolution, SuperbitRF::resync_count, Cyrf6936::rx_irq_status, Cyrf6936::rx_packet, SuperbitRF::rx_packet_count, Cyrf6936::rx_status, SuperbitRF::sop_col, SPEKTRUM_BIND_PIN, SPEKTRUM_BIND_PIN_PORT, SuperbitRF::state, Cyrf6936::status, SuperbitRF::status, superbitrf, SUPERBITRF_BIND_RECV_TIME, SUPERBITRF_BINDING, SUPERBITRF_DATARECV_TIME, SUPERBITRF_DATARECVB_TIME, SUPERBITRF_DRDY_PIN, SUPERBITRF_DRDY_PORT, SUPERBITRF_FORCE_DSM2, superbitrf_gen_dsmx_channels(), SUPERBITRF_INIT_BINDING, SUPERBITRF_INIT_TRANSFER, superbitrf_receive_packet_cb(), SUPERBITRF_RECV_SHORT_TIME, SUPERBITRF_RECV_TIME, superbitrf_send_packet_cb(), SUPERBITRF_SYNC_RECV_TIME, SUPERBITRF_SYNCING_A, SUPERBITRF_SYNCING_B, SUPERBITRF_TRANSFER, SUPERBITRF_UNINIT, SuperbitRF::timeouts, SuperbitRF::timer, SuperbitRF::timer_overflow, SuperbitRF::transfer_timeouts, TRUE, SuperbitRF::tx_buffer, SuperbitRF::tx_extract_idx, SuperbitRF::tx_insert_idx, Cyrf6936::tx_irq_status, and SuperbitRF::tx_packet_count.
static void superbitrf_gen_dsmx_channels (void) inline static
Generate the channels.
Definition at line 958 of file superbitrf.c.
References SuperbitRF::bind_mfg_id, SuperbitRF::channels, and superbitrf.
Referenced by superbitrf_event().
void superbitrf_init (void)
Initialize the superbitrf.
Definition at line 201 of file superbitrf.c.
References SuperbitRF::cyrf6936, cyrf6936_init(), gpio_setup_input(), register_periodic_telemetry(), SuperbitRF::rx_packet_count, SPEKTRUM_BIND_PIN, SPEKTRUM_BIND_PIN_PORT, SuperbitRF::state, SuperbitRF::status, superbitrf, SUPERBITRF_DRDY_PIN, SUPERBITRF_DRDY_PORT, SUPERBITRF_RST_PIN, SUPERBITRF_RST_PORT, SUPERBITRF_SPI_DEV, SUPERBITRF_UNINIT, SuperbitRF::timer, SuperbitRF::tx_extract_idx, SuperbitRF::tx_insert_idx, and SuperbitRF::tx_packet_count.
Referenced by radio_control_impl_init().
static void superbitrf_radio_to_channels (uint8_t * data, uint8_t nb_channels, bool_t is_11bit, int16_t * channels) inline static
Parse a radio channel packet.
Definition at line 930 of file superbitrf.c.
References MAX_PPRZ, and val.
Referenced by superbitrf_receive_packet_cb().
static void superbitrf_receive_packet_cb (bool_t error, uint8_t status, uint8_t packet[]) inline static
When we receive a packet this callback is called.
Definition at line 638 of file superbitrf.c.
References SuperbitRF::bind_mfg_id, SuperbitRF::bind_mfg_id32, SuperbitRF::channel, SuperbitRF::channel_idx, SuperbitRF::channels, SuperbitRF::crc_seed, SuperbitRF::cyrf6936, cyrf6936_multi_write(), CYRF_BAD_CRC, cyrf_start_receive, SuperbitRF::data_col, dl_msg_available, FALSE, get_sys_time_usec(), IS_DSM2, IS_DSMX, transport::msg_received, SuperbitRF::num_channels, SuperbitRF::packet_loss, SuperbitRF::packet_loss_bit, parse_pprz(), pprz_parse_payload(), SuperbitRF::protocol, SuperbitRF::rc_count, SuperbitRF::rc_frame_available, SuperbitRF::rc_values, SuperbitRF::resolution, Cyrf6936::rx_count, SuperbitRF::rx_transport, SuperbitRF::sop_col, SuperbitRF::state, SuperbitRF::status, superbitrf, SUPERBITRF_BINDING, SUPERBITRF_FORCE_DSM2, SUPERBITRF_INIT_TRANSFER, superbitrf_radio_to_channels(), SUPERBITRF_RECV_SHORT_TIME, SUPERBITRF_RECV_TIME, SUPERBITRF_SYNCING_A, SUPERBITRF_SYNCING_B, SUPERBITRF_TRANSFER, SuperbitRF::timeouts, SuperbitRF::timer, SuperbitRF::timing1, SuperbitRF::timing2, pprz_transport::trans, TRUE, and SuperbitRF::uplink_count.
Referenced by superbitrf_event().
static void superbitrf_send_packet_cb (bool_t error) inline static
Definition at line 902 of file superbitrf.c.
References SuperbitRF::state, SuperbitRF::status, superbitrf, SUPERBITRF_SYNCING_A, SUPERBITRF_SYNCING_B, and SUPERBITRF_TRANSFER.
Referenced by superbitrf_event().
Variable Documentation
const uint8_t cyrf_abort_receive[][2]
Initial value:
 {
  {CYRF_XACT_CFG, CYRF_MODE_SYNTH_RX | CYRF_FRC_END},
  {CYRF_RX_ABORT, 0x00}
}
Definition at line 106 of file superbitrf.c.
Referenced by superbitrf_event().
const uint8_t cyrf_bind_config[][2] static
Initial value:
 {
  {CYRF_TX_CFG, CYRF_DATA_CODE_LENGTH | CYRF_DATA_MODE_SDR | CYRF_PA_4},
  {CYRF_FRAMING_CFG, CYRF_SOP_LEN | 0xE},
  {CYRF_RX_OVERRIDE, CYRF_FRC_RXDR | CYRF_DIS_RXCRC},
  {CYRF_EOP_CTRL, 0x02},
  {CYRF_TX_OVERRIDE, CYRF_DIS_TXCRC},
}
Definition at line 91 of file superbitrf.c.
Referenced by superbitrf_event().
const uint8_t cyrf_start_receive[][2]
Initial value:
 {
  {CYRF_RX_IRQ_STATUS, CYRF_RXOW_IRQ},
  {CYRF_RX_CTRL, CYRF_RX_GO | CYRF_RXC_IRQEN | CYRF_RXE_IRQEN}
}
Definition at line 111 of file superbitrf.c.
Referenced by superbitrf_event(), and superbitrf_receive_packet_cb().
const uint8_t cyrf_stratup_config[][2] static
Initial value:
 {
  {CYRF_MODE_OVERRIDE, CYRF_RST},
  {CYRF_CLK_EN, CYRF_RXF},
  {CYRF_AUTO_CAL_TIME, 0x3C},
  {CYRF_AUTO_CAL_OFFSET, 0x14},
  {CYRF_RX_CFG, CYRF_LNA | CYRF_FAST_TURN_EN},
  {CYRF_TX_OFFSET_LSB, 0x55},
  {CYRF_TX_OFFSET_MSB, 0x05},
  {CYRF_XACT_CFG, CYRF_MODE_SYNTH_RX | CYRF_FRC_END},
  {CYRF_TX_CFG, CYRF_DATA_CODE_LENGTH | CYRF_DATA_MODE_SDR | CYRF_PA_4},
  {CYRF_DATA64_THOLD, 0x0E},
  {CYRF_XACT_CFG, CYRF_MODE_SYNTH_RX},
}
Definition at line 77 of file superbitrf.c.
Referenced by superbitrf_event().
const uint8_t cyrf_transfer_config[][2] static
Initial value:
 {
  {CYRF_TX_CFG, CYRF_DATA_CODE_LENGTH | CYRF_DATA_MODE_8DR | CYRF_PA_4},
  {CYRF_FRAMING_CFG, CYRF_SOP_EN | CYRF_SOP_LEN | CYRF_LEN_EN | 0xE},
  {CYRF_TX_OVERRIDE, 0x00},
  {CYRF_RX_OVERRIDE, 0x00},
}
Definition at line 99 of file superbitrf.c.
Referenced by superbitrf_event().
const uint8_t pn_bind[] = { 0x98, 0x88, 0x1B, 0xE4, 0x30, 0x79, 0x03, 0x84 } static
Definition at line 174 of file superbitrf.c.
Referenced by superbitrf_event().
const uint8_t pn_codes[5][9][8] static
Definition at line 117 of file superbitrf.c.
Referenced by superbitrf_event().
struct SuperbitRF superbitrf
Definition at line 68 of file superbitrf.c.
Referenced by superbitrf_event(), superbitrf_gen_dsmx_channels(), superbitrf_init(), superbitrf_receive_packet_cb(), and superbitrf_send_packet_cb().