Paparazzi UAS: sw/airborne/subsystems/datalink/telemetry.c File Reference
telemetry.c File Reference
Periodic telemetry system utility function.
#include "subsystems/datalink/telemetry_common.h"
Functions
bool_t register_periodic_telemetry (struct pprz_telemetry *_pt, const char *_msg, telemetry_cb _cb)
Register a telemetry callback function.
Detailed Description
Periodic telemetry system utility function.
Definition in file telemetry.c.
Function Documentation
bool_t register_periodic_telemetry (struct pprz_telemetry * _pt, const char * _msg, telemetry_cb _cb)
Register a telemetry callback function.
Parameters
_pt periodic telemetry structure to register
_msg message name (string) as defined in telemetry xml file
_cb callback function, called according to telemetry mode and specified period
Returns
TRUE if message registered with success, FALSE otherwise
Definition at line 38 of file telemetry.c.
References telemetry_msg::cb, FALSE, telemetry_msg::msg, pprz_telemetry::msgs, pprz_telemetry::nb, and TRUE.
Referenced by ahrs_aligner_init(), ahrs_init(), air_data_init(), autopilot_init(), b2_hff_init(), cam_init(), gps_init(), guidance_h_init(), guidance_v_init(), h_ctl_init(), i2c_init(), imu_impl_init(), imu_init(), init_ap(), init_fbw(), ins_init(), nav_init(), navdata_init(), radio_control_impl_init(), rotorcraft_cam_init(), stabilization_attitude_init(), stabilization_rate_init(), superbitrf_init(), track_init(), uart_periph_init(), and vff_init().