Paparazzi UAS: sw/airborne/lisa/test_datalink.c File Reference
test_datalink.c File Reference
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/datalink/datalink.h"
Macros
#define DATALINK_C
Functions
static void main_init (void)
static void main_periodic (void)
static void main_event (void)
int main (void)
void dl_parse_msg (void)
Macro Definition Documentation
#define DATALINK_C
Definition at line 22 of file test_datalink.c.
Function Documentation
void dl_parse_msg (void)
NAV
WIND_INFO
Else there is no dl_settings section in the flight plan
Definition at line 60 of file test_datalink.c.
References c, datalink_time, DefaultChannel, DefaultDevice, dl_buffer, UtmCoor_f::east, gps_nb_ovrn, IdOfMsg, infrared, LlaCoor_f::lat, LED_TOGGLE, LlaCoor_f::lon, MOfCm, nav_goto_block(), nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), Infrared::pitch, tcas_ac_status::resolve, Infrared::roll, SEND_NAVIGATION, SenderIdOfMsg, SetAcInfo, stateGetAirspeed_f(), stateSetAirspeed_f(), stateSetHorizontalWindspeed_f(), tcas_acs_status, the_acs_id, Infrared::top, TRUE, utm_of_lla_f(), val, waypoints, FloatVect2::x, EnuCoor_i::x, FloatVect2::y, EnuCoor_i::y, and UtmCoor_f::zone.
int main (void)
Definition at line 35 of file test_datalink.c.
References main_event(), main_init(), main_periodic(), and sys_time_check_and_ack_timer().
static void main_event (void) inline static
static void main_init (void) inline static
static void main_periodic (void) inline static