Paparazzi UAS: sw/airborne/lisa/test_float.c File Reference
test_float.c File Reference
#include <math.h>
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/datalink/downlink.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic (void)
int main (void)
Function Documentation
int main (void)
Definition at line 33 of file test_float.c.
References main_init(), main_periodic(), and sys_time_check_and_ack_timer().
static void main_init (void) inline static
static void main_periodic (void) inline static