Paparazzi UAS: sw/airborne/mcu_periph/uart.c File Reference
uart.c File Reference
#include "mcu_periph/uart.h"
Functions
void uart_periph_init (struct uart_periph *p)
bool_t uart_check_free_space (struct uart_periph *p, uint8_t len)
uint8_t uart_getch (struct uart_periph *p)
Function Documentation
bool_t uart_check_free_space (struct uart_periph * p, uint8_t len)
Definition at line 197 of file uart.c.
References uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, and UART_TX_BUFFER_SIZE.
Referenced by main().
uint8_t uart_getch (struct uart_periph * p)
Definition at line 204 of file uart.c.
References uart_periph::rx_buf, uart_periph::rx_extract_idx, and UART_RX_BUFFER_SIZE.
Referenced by main(), main_event_task(), ReadGX3Buffer(), sbus_decode_event(), test_uart_event(), and uart_transfer_event().
void uart_periph_init (struct uart_periph * p)
Definition at line 181 of file uart.c.
References FALSE, uart_periph::fe_err, uart_periph::ne_err, uart_periph::ore, register_periodic_telemetry(), uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, and uart_periph::tx_running.