Paparazzi UAS: sw/airborne/modules/nav/zamboni_survey.h File Reference
zamboni_survey.h File Reference
Zamboni pattern survey for fixedwings.
#include "std.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct ZamboniSurvey
Enumerations
enum z_survey_stage {
Z_ERR, Z_ENTRY, Z_SEG, Z_TURN1,
Z_RET, Z_TURN2
}
Functions
bool_t init_zamboni_survey (uint8_t center_wp, uint8_t dir_wp, float sweep_length, float sweep_spacing, int sweep_lines, float altitude)
initializes the variables needed for the survey to start.
bool_t zamboni_survey (void)
main navigation routine.
Detailed Description
Zamboni pattern survey for fixedwings.
Definition in file zamboni_survey.h.
Enumeration Type Documentation
enum z_survey_stage
Enumerator:
Z_ERR
Z_ENTRY
Z_SEG
Z_TURN1
Z_RET
Z_TURN2
Definition at line 34 of file zamboni_survey.h.
Function Documentation
bool_t init_zamboni_survey (uint8_t center_wp, uint8_t dir_wp, float sweep_length, float sweep_spacing, int sweep_lines, float altitude)
initializes the variables needed for the survey to start.
Parameters
center_wp the waypoint defining the center of the survey-rectangle
dir_wp the waypoint defining the orientation of the survey-rectangle
sweep_length the length of the survey-rectangle
sweep_spacing distance between the sweeps
sweep_lines number of sweep_lines to fly
altitude the altitude that must be reached before the flyover starts
Definition at line 51 of file zamboni_survey.c.
References ZamboniSurvey::altitude, ZamboniSurvey::current_laps, FALSE, ZamboniSurvey::flight_angle, FLOAT_VECT2_NORMALIZE, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, ZamboniSurvey::pre_leave_angle, ZamboniSurvey::ret_end, ZamboniSurvey::ret_start, ZamboniSurvey::return_angle, ZamboniSurvey::seg_end, ZamboniSurvey::seg_start, ZamboniSurvey::stage, ZamboniSurvey::sweep_width, ZamboniSurvey::total_laps, ZamboniSurvey::turn_center1, ZamboniSurvey::turn_center2, ZamboniSurvey::turnradius1, ZamboniSurvey::turnradius2, VECT2_COPY, VECT2_DIFF, VECT2_SMUL, VECT2_SUM, waypoints, ZamboniSurvey::wp_center, ZamboniSurvey::wp_dir, FloatVect2::x, FloatVect2::y, Z_ENTRY, and zs.
bool_t zamboni_survey (void)
main navigation routine.
This is called periodically evaluates the current Position and stage and navigates accordingly.
Returns
TRUE until the survey is finished
Definition at line 124 of file zamboni_survey.c.
References ZamboniSurvey::altitude, ZamboniSurvey::current_laps, FALSE, ZamboniSurvey::flight_angle, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCourseCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, ZamboniSurvey::pre_leave_angle, ZamboniSurvey::ret_end, ZamboniSurvey::ret_start, ZamboniSurvey::return_angle, ZamboniSurvey::seg_end, ZamboniSurvey::seg_start, ZamboniSurvey::stage, ZamboniSurvey::sweep_width, ZamboniSurvey::total_laps, TRUE, ZamboniSurvey::turn_center1, ZamboniSurvey::turn_center2, ZamboniSurvey::turnradius1, ZamboniSurvey::turnradius2, VECT2_ADD, ZamboniSurvey::wp_center, FloatVect2::x, FloatVect2::y, Z_ENTRY, Z_RET, Z_SEG, Z_TURN1, Z_TURN2, and zs.