Paparazzi UAS: sw/airborne/boards/ardrone/actuators_at.c File Reference
actuators_at.c File Reference
ardrone2-sdk actuators are driven by external software controller by AT-commands
#include "subsystems/ahrs/ahrs_ardrone2.h"
#include "actuators_at.h"
#include "generated/airframe.h"
#include "boards/ardrone/at_com.h"
Functions
void actuators_init (void)
void actuators_set (pprz_t commands[])
Detailed Description
ardrone2-sdk actuators are driven by external software controller by AT-commands
Definition in file actuators_at.c.
Function Documentation
void actuators_init (void)
Definition at line 32 of file actuators_at.c.
References init_at_com().
Referenced by init_fbw(), and main_init().
void actuators_set (pprz_t commands[])
Definition at line 36 of file actuators_at.c.
References ahrs_impl, ARDRONE_EMERGENCY_MASK, ARDRONE_MAGNETO_NEEDS_CALIB, at_com_send_calib(), at_com_send_config(), at_com_send_pcmd(), at_com_send_ref(), AhrsARDrone::control_state, CTRL_DEFAULT, CTRL_FLYING, CTRL_HOVERING, CTRL_INIT, CTRL_LANDED, MAX_PPRZ, REF_EMERGENCY, REF_TAKEOFF, and AhrsARDrone::state.