Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_gx3.c File Reference
ahrs_gx3.c File Reference
Driver for Microstrain GX3 IMU/AHRS subsystem.
#include "subsystems/ahrs/ahrs_gx3.h"
#include "mcu_periph/sys_time.h"
Macros
#define GX3_TIME(_ubx_payload) (uint32_t)((uint32_t)(*((uint8_t*)_ubx_payload+62+3))|(uint32_t)(*((uint8_t*)_ubx_payload+62+2))<<8|(uint32_t)(*((uint8_t*)_ubx_payload+62+1))<<16|(uint32_t)(*((uint8_t*)_ubx_payload+62+0))<<24)
#define GX3_CHKSM(_ubx_payload) (uint16_t)((uint16_t)(*((uint8_t*)_ubx_payload+66+1))|(uint16_t)(*((uint8_t*)_ubx_payload+66+0))<<8)
#define IMU_DIV1 0
#define IMU_DIV2 2
#define ACC_FILT_DIV 2
#define MAG_FILT_DIV 30
Functions
static bool_t GX3_verify_chk (volatile uint8_t *buff_add)
static float bef (volatile uint8_t *c)
void ahrs_align (void)
Aligns the AHRS.
void imu_impl_init (void)
void imu_periodic (void)
void GX3_packet_read_message (void)
void GX3_packet_parse (uint8_t c)
void ahrs_init (void)
AHRS initialization.
void ahrs_aligner_run (void)
void ahrs_aligner_init (void)
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Variables
struct GX3_packet GX3_packet
enum GX3Status GX3_status
uint32_t GX3_time
uint32_t GX3_ltime
uint16_t GX3_chksm
uint16_t GX3_calcsm
float GX3_freq
struct FloatVect3 GX3_accel
struct FloatRates GX3_rate
struct FloatRMat GX3_rmat
struct FloatQuat GX3_quat
struct FloatEulers GX3_euler
struct AhrsFloatQuat ahrs_impl
struct AhrsAligner ahrs_aligner
Detailed Description
Driver for Microstrain GX3 IMU/AHRS subsystem.
Takes care of configuration of the IMU, communication and parsing the received packets. See GX3 datasheet for configuration options.
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file ahrs_gx3.c.
Macro Definition Documentation
#define ACC_FILT_DIV 2
Referenced by imu_impl_init().
#define GX3_CHKSM (_ubx_payload) (uint16_t)((uint16_t)(*((uint8_t*)_ubx_payload+66+1))|(uint16_t)(*((uint8_t*)_ubx_payload+66+0))<<8)
Definition at line 36 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
#define GX3_TIME (_ubx_payload) (uint32_t)((uint32_t)(*((uint8_t*)_ubx_payload+62+3))|(uint32_t)(*((uint8_t*)_ubx_payload+62+2))<<8|(uint32_t)(*((uint8_t*)_ubx_payload+62+1))<<16|(uint32_t)(*((uint8_t*)_ubx_payload+62+0))<<24)
Definition at line 35 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
#define IMU_DIV1 0
Referenced by imu_impl_init().
#define IMU_DIV2 2
Referenced by imu_impl_init().
#define MAG_FILT_DIV 30
Referenced by imu_impl_init().
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 85 of file ahrs_gx3.c.
References GX3_status, GX3Link, GX3Running, and GX3Uninit.
void ahrs_aligner_init (void)
Definition at line 303 of file ahrs_gx3.c.
References accel_sum, ahrs_aligner, AHRS_ALIGNER_RUNNING, gyro_sum, INT_RATES_ZERO, INT_VECT3_ZERO, AhrsAligner::low_noise_cnt, mag_sum, AhrsAligner::noise, samples_idx, and AhrsAligner::status.
void ahrs_aligner_run (void)
Definition at line 290 of file ahrs_gx3.c.
References Imu::accel, accel_sum, ahrs, ahrs_aligner, AHRS_ALIGNER_LOCKED, AHRS_RUNNING, GX3_freq, GX3_MIN_FREQ, Imu::gyro, gyro_sum, imu, INT_RATES_ZERO, INT_VECT3_ZERO, LED_ON, LED_TOGGLE, AhrsAligner::low_noise_cnt, LOW_NOISE_THRESHOLD, LOW_NOISE_TIME, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, Imu::mag, mag_sum, AhrsAligner::noise, RATES_ADD, RATES_SDIV, ref_sensor_samples, samples_idx, SAMPLES_NB, Ahrs::status, AhrsAligner::status, VECT3_ADD, VECT3_SDIV, and Int32Vect3::z.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 274 of file ahrs_gx3.c.
References ahrs, ahrs_aligner, AHRS_ALIGNER_LOCKED, ahrs_impl, AHRS_UNINIT, FLOAT_RATES_ZERO, AhrsARDrone::ltp_to_imu_quat, QUAT_COPY, Ahrs::status, and AhrsAligner::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 306 of file ahrs_gx3.c.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 309 of file ahrs_gx3.c.
void ahrs_update_gps (void)
Update AHRS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 315 of file ahrs_gx3.c.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 312 of file ahrs_gx3.c.
static float bef (volatile uint8_t * c) inline static
Definition at line 65 of file ahrs_gx3.c.
References c, and p.
Referenced by GX3_packet_read_message().
void GX3_packet_parse (uint8_t c)
Definition at line 242 of file ahrs_gx3.c.
References c, GX3_packet::chksm_error, FALSE, GX3_HEADER, GX3_MSG_LEN, GX3_verify_chk(), GX3PacketReading, GX3PacketWaiting, GX3_packet::hdr_error, GX3_packet::msg_available, GX3_packet::msg_buf, GX3_packet::msg_idx, GX3_packet::status, and TRUE.
Referenced by ReadGX3Buffer().
void GX3_packet_read_message (void)
Definition at line 192 of file ahrs_gx3.c.
References Imu::accel, ACCELS_BFP_OF_REAL, ahrs_impl, bef(), FLOAT_QUAT_COMP_INV, FLOAT_QUAT_OF_RMAT, FLOAT_RMAT_TRANSP_RATEMULT, GX3_accel, GX3_calcsm, GX3_CHKSM, GX3_chksm, GX3_freq, GX3_ltime, GX3_quat, GX3_rate, GX3_rmat, GX3_TIME, GX3_time, imu, AhrsARDrone::ltp_to_imu_quat, FloatRMat::m, GX3_packet::msg_buf, FloatRates::p, FloatRates::q, FloatRates::r, stateSetBodyRates_f(), stateSetNedToBodyQuat_f(), VECT3_SMUL, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ImuEvent().
static bool_t GX3_verify_chk (volatile uint8_t * buff_add) inline static
Definition at line 76 of file ahrs_gx3.c.
References chk_calc, and GX3_MSG_LEN.
Referenced by GX3_packet_parse().
void imu_impl_init (void)
Definition at line 99 of file ahrs_gx3.c.
References ACC_FILT_DIV, ahrs_align(), GX3_packet::chksm_error, FALSE, GX3_status, GX3Link, GX3PacketWaiting, GX3Uninit, GX3_packet::hdr_error, IMU_DIV1, IMU_DIV2, IMU_GX3_LONG_DELAY, MAG_FILT_DIV, GX3_packet::msg_available, GX3_packet::msg_idx, and GX3_packet::status.
void imu_periodic (void)
Definition at line 185 of file ahrs_gx3.c.
Variable Documentation
struct AhrsAligner ahrs_aligner
Definition at line 59 of file ahrs_gx3.c.
struct AhrsFloatQuat ahrs_impl
Definition at line 58 of file ahrs_gx3.c.
struct FloatVect3 GX3_accel
Definition at line 52 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
uint16_t GX3_calcsm
Definition at line 49 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
uint16_t GX3_chksm
Definition at line 48 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
struct FloatEulers GX3_euler
Definition at line 56 of file ahrs_gx3.c.
float GX3_freq
Definition at line 50 of file ahrs_gx3.c.
Referenced by ahrs_aligner_run(), and GX3_packet_read_message().
uint32_t GX3_ltime
Definition at line 47 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
struct GX3_packet GX3_packet
Definition at line 44 of file ahrs_gx3.c.
struct FloatQuat GX3_quat
Definition at line 55 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
struct FloatRates GX3_rate
Definition at line 53 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
struct FloatRMat GX3_rmat
Definition at line 54 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().
enum GX3Status GX3_status
Definition at line 45 of file ahrs_gx3.c.
Referenced by ahrs_align(), and imu_impl_init().
uint32_t GX3_time
Definition at line 46 of file ahrs_gx3.c.
Referenced by GX3_packet_read_message().