Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_float_mlkf.c File Reference
ahrs_float_mlkf.c File Reference
Multiplicative linearized Kalman Filter in quaternion formulation.
#include "subsystems/ahrs/ahrs_float_mlkf.h"
#include "subsystems/ahrs/ahrs_aligner.h"
#include "subsystems/ahrs/ahrs_float_utils.h"
#include <float.h>
#include <string.h>
#include <math.h>
#include "state.h"
#include "subsystems/imu.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_simple_matrix.h"
#include "generated/airframe.h"
Macros
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Functions
static void propagate_ref (void)
static void propagate_state (void)
Progagate filter's covariance We don't propagate state as we assume to have reseted.
static void update_state (const struct FloatVect3 *i_expected, struct FloatVect3 *b_measured, const float noise[])
Incorporate one 3D vector measurement.
static void reset_state (void)
Incorporate errors to reference and zeros state.
static void set_body_state_from_quat (void)
Compute body orientation and rates from imu orientation and rates.
void ahrs_init (void)
AHRS initialization.
void ahrs_align (void)
Aligns the AHRS.
void ahrs_propagate (void)
Propagation.
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Variables
struct AhrsMlkf ahrs_impl
Detailed Description
Multiplicative linearized Kalman Filter in quaternion formulation.
Estimate the attitude, heading and gyro bias.
Definition in file ahrs_float_mlkf.c.
Macro Definition Documentation
#define AHRS_PROPAGATE_FREQUENCY PERIODIC_FREQUENCY
Definition at line 50 of file ahrs_float_mlkf.c.
Referenced by propagate_ref(), and propagate_state().
Function Documentation
void ahrs_align (void)
Aligns the AHRS.
Called after ahrs_aligner has run to set initial attitude and biases. Must set the ahrs status to AHRS_RUNNING. Needs to be implemented by each AHRS algorithm.
Definition at line 97 of file ahrs_float_mlkf.c.
References ahrs, ahrs_aligner, ahrs_float_get_quat_from_accel_mag(), ahrs_impl, AHRS_RUNNING, FLOAT_RMAT_OF_QUAT, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, AhrsARDrone::ltp_to_imu_quat, RATES_COPY, RATES_FLOAT_OF_BFP, set_body_state_from_quat(), and Ahrs::status.
void ahrs_init (void)
AHRS initialization.
Called at startup. Needs to be implemented by each AHRS algorithm.
Definition at line 62 of file ahrs_float_mlkf.c.
References ahrs, ahrs_impl, AHRS_UNINIT, FLOAT_QUAT_OF_EULERS, FLOAT_RATES_ZERO, FLOAT_RMAT_OF_EULERS, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, AhrsARDrone::ltp_to_imu_quat, QUAT_COPY, RMAT_COPY, and Ahrs::status.
void ahrs_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 116 of file ahrs_float_mlkf.c.
References propagate_ref(), propagate_state(), and set_body_state_from_quat().
void ahrs_update_accel (void)
Update AHRS state with accerleration measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 122 of file ahrs_float_mlkf.c.
References Imu::accel, ACCELS_FLOAT_OF_BFP, ahrs_impl, dn, FLOAT_VECT3_NORM, imu, reset_state(), and update_state().
void ahrs_update_mag (void)
Update AHRS state with magnetometer measurements.
Reads the global imu data struct. Needs to be implemented by each AHRS algorithm.
Definition at line 137 of file ahrs_float_mlkf.c.
References AHRS_H_X, AHRS_H_Y, imu, Imu::mag, MAGS_FLOAT_OF_BFP, reset_state(), and update_state().
static void propagate_ref (void) inline static
Definition at line 147 of file ahrs_float_mlkf.c.
References ahrs_impl, AHRS_PROPAGATE_FREQUENCY, FLOAT_RATES_LIN_CMB, FLOAT_RATES_NORM, FLOAT_RMAT_OF_QUAT, Imu::gyro_prev, imu, AhrsARDrone::ltp_to_imu_quat, Int32Quat::qi, Int32Quat::qx, Int32Quat::qy, Int32Quat::qz, RATES_COPY, RATES_FLOAT_OF_BFP, and RATES_SUB.
Referenced by ahrs_propagate().
static void propagate_state (void) inline static
Progagate filter's covariance We don't propagate state as we assume to have reseted.
Definition at line 195 of file ahrs_float_mlkf.c.
References ahrs_impl, AHRS_PROPAGATE_FREQUENCY, MAT_MUL, and MAT_MUL_T.
Referenced by ahrs_propagate().
static void reset_state (void) inline static
Incorporate errors to reference and zeros state.
Definition at line 280 of file ahrs_float_mlkf.c.
References ahrs_impl, FLOAT_QUAT_COMP, FLOAT_QUAT_NORMALIZE, FLOAT_QUAT_ZERO, FLOAT_RMAT_OF_QUAT, and AhrsARDrone::ltp_to_imu_quat.
Referenced by ahrs_update_accel(), and ahrs_update_mag().
static void set_body_state_from_quat (void) inline static
Compute body orientation and rates from imu orientation and rates.
Definition at line 295 of file ahrs_float_mlkf.c.
References ahrs_impl, FLOAT_QUAT_COMP_INV, FLOAT_RMAT_TRANSP_RATEMULT, AhrsARDrone::ltp_to_imu_quat, stateSetBodyRates_f(), and stateSetNedToBodyQuat_f().
Referenced by ahrs_align(), and ahrs_propagate().
static void update_state (const struct FloatVect3 * i_expected, struct FloatVect3 * b_measured, const float noise[]) inline static
Incorporate one 3D vector measurement.
Definition at line 224 of file ahrs_float_mlkf.c.
References ahrs_impl, FLOAT_RMAT_VECT3_MUL, MAT_INV33, MAT_MUL, MAT_MUL_T, MAT_SUB, VECT3_DIFF, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ahrs_update_accel(), and ahrs_update_mag().
Variable Documentation
struct AhrsMlkf ahrs_impl
Definition at line 59 of file ahrs_float_mlkf.c.