Paparazzi UAS: sw/airborne/arch/lpc21/armVIC.h File Reference
armVIC.h File Reference
Macros
#define __VIC_CNTL(idx) VICVectCntl##idx
#define __VIC_ADDR(idx) VICVectAddr##idx
#define _VIC_CNTL(idx) __VIC_CNTL(idx)
#define _VIC_ADDR(idx) __VIC_ADDR(idx)
#define ISR_ENTRY()
#define ISR_EXIT()
Functions
unsigned disableIRQ (void)
unsigned enableIRQ (void)
unsigned restoreIRQ (unsigned oldCPSR)
unsigned disableFIQ (void)
unsigned enableFIQ (void)
unsigned restoreFIQ (unsigned oldCPSR)
Macro Definition Documentation
#define __VIC_ADDR (idx) VICVectAddr##idx
Definition at line 18 of file armVIC.h.
#define __VIC_CNTL (idx) VICVectCntl##idx
Definition at line 17 of file armVIC.h.
#define _VIC_ADDR (idx) __VIC_ADDR(idx)
Definition at line 20 of file armVIC.h.
Referenced by actuators_4015_init(), adc_init(), imu_crista_arch_init(), max11040_hw_init(), max1168_arch_init(), micromag_hw_init(), ms2100_arch_init(), spi1_arch_init(), spi_slave_hs_init(), and sys_time_arch_init().
#define _VIC_CNTL (idx) __VIC_CNTL(idx)
Definition at line 19 of file armVIC.h.
Referenced by actuators_4015_init(), adc_init(), ADS8344_init(), baro_scp_init(), imu_crista_arch_init(), lcd_dogm_init_hw(), max11040_hw_init(), max1168_arch_init(), max3100_init(), micromag_hw_init(), ms2100_arch_init(), spi1_arch_init(), spi_slave_hs_init(), and sys_time_arch_init().
#define ISR_ENTRY ()
Value:
asm volatile(" sub   lr, lr,#4\n" \
                                 " stmfd sp!,{r0-r12,lr}\n" \
                                 " mrs   r1, spsr\n" \
                                 " stmfd sp!,{r1}")
Definition at line 40 of file armVIC.h.
Referenced by adcISR0(), adcISR1(), EXTINT0_ISR(), EXTINT_ISR(), PWM_ISR(), SPI1_ISR(), spi1_ISR(), SSP_ISR(), TIMER0_ISR(), and TIMER1_ISR().
#define ISR_EXIT ()
Value:
asm volatile(" ldmfd sp!,{r1}\n" \
                                 " msr   spsr_c,r1\n" \
                                 " ldmfd sp!,{r0-r12,pc}^")
Definition at line 61 of file armVIC.h.
Referenced by adcISR0(), adcISR1(), EXTINT0_ISR(), EXTINT_ISR(), PWM_ISR(), SPI1_ISR(), spi1_ISR(), SSP_ISR(), TIMER0_ISR(), and TIMER1_ISR().
Function Documentation
unsigned disableFIQ (void)
Definition at line 60 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and FIQ_MASK.
unsigned disableIRQ (void)
Definition at line 33 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and IRQ_MASK.
Referenced by flash_detect(), i2c_submit(), pflash_erase_page(), pflash_program_array(), spi_submit(), and uart_transmit().
unsigned enableFIQ (void)
Definition at line 78 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and FIQ_MASK.
unsigned enableIRQ (void)
Definition at line 51 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and IRQ_MASK.
Referenced by flash_detect(), i2c_submit(), pflash_erase_page(), pflash_program_array(), and spi_submit().
unsigned restoreFIQ (unsigned oldCPSR)
Definition at line 69 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and FIQ_MASK.
unsigned restoreIRQ (unsigned oldCPSR)
Definition at line 42 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and IRQ_MASK.
Referenced by uart_transmit().