Paparazzi UAS: sw/airborne/subsystems/sensors/baro.h File Reference
baro.h File Reference
Common barometric sensor implementation.
#include <std.h>
#include <BOARD_CONFIG>
Data Structures
struct Baro
Enumerations
enum BaroStatus { BS_UNINITIALIZED, BS_RUNNING }
Functions
void baro_init (void)
Implementation of the generic baro interface initialization.
void baro_periodic (void)
Implementation of the generic baro interface periodic task.
Variables
struct Baro baro
Detailed Description
Common barometric sensor implementation.
Definition in file baro.h.
Enumeration Type Documentation
enum BaroStatus
Enumerator:
BS_UNINITIALIZED
BS_RUNNING
Definition at line 34 of file baro.h.
Function Documentation
void baro_init (void)
Implementation of the generic baro interface initialization.
No need to call this functions from the modules, already done by main.
Definition at line 42 of file baro_board.c.
References Baro::absolute, adc_buf_channel(), ADC_CHANNEL_BARO, ads1114_init(), baro, baro_board, baro_pc_available, BARO_STARTUP_COUNTER, bmp085_baro_read_calibration(), BS_UNINITIALIZED, BaroBoard::buf, DACSet(), BaroBoard::data_available, DEFAULT_AV_NB_SAMPLE, Baro::differential, FALSE, input_buf_ms5611, LBS_UNINITIALIZED, LED_OFF, mcp355x_init(), mpl3115_init(), MS5611_BUFFER_LENGTH, MS5611_SLAVE_DEV, ms5611_status, ms5611_trans, MS5611_UNINIT, BaroBoard::offset, prom_cnt, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, startup_cnt, BaroBoard::status, Baro::status, trans_cb_ms5611(), and BaroBoard::value_filtered.
Referenced by baro_event(), init_ap(), and main_init().
void baro_periodic (void)
Implementation of the generic baro interface periodic task.
No need to call this functions from the modules, already done by main.
Definition at line 50 of file baro_board.c.
References Baro::absolute, ads1114_read(), adc_buf::av_nb_sample, baro, BARO_ABS_ADDR, BARO_ABS_ADS, baro_board, baro_board_calibrate(), baro_board_read_from_current_register(), baro_board_send_config_abs(), baro_board_send_config_diff(), baro_board_send_reset(), baro_board_set_current_register(), BARO_DIFF_ADDR, baro_eoc(), baro_trans, bmp085_read_pressure(), bmp085_read_temp(), bmp085_request_pressure(), bmp085_request_temp(), BS_RUNNING, BS_UNINITIALIZED, BaroBoard::buf, i2c_transaction::buf, Mpu60x0_I2c::config, BaroBoard::data_available, DefaultChannel, DefaultDevice, FALSE, i2c_idle(), i2c_transceive(), i2c_transmit(), I2CTransPending, I2CTransRunning, imu_apogee, Mpu60x0Config::initialized, LBS_INITIALIZING_ABS, LBS_INITIALIZING_ABS_1, LBS_INITIALIZING_DIFF, LBS_INITIALIZING_DIFF_1, LBS_READ, LBS_READ_ABS, LBS_READ_DIFF, LBS_READ_TEMP, LBS_READING, LBS_READING_ABS, LBS_READING_DIFF, LBS_READING_TEMP, LBS_REQUEST, LBS_REQUEST_TEMP, LBS_RESETED, LBS_UNINITIALIZED, LED_ON, LED_TOGGLE, mcp355x_read(), mpl3115_data_available, Mpl3115Periodic, ImuApogee::mpu, MS5611_ADC_D1, MS5611_ADC_D2, MS5611_ADC_READ, ms5611_c, MS5611_CONV_D1, MS5611_CONV_D1_OK, MS5611_CONV_D2, MS5611_CONV_D2_OK, MS5611_I2C_DEV, MS5611_IDLE, MS5611_PROM, MS5611_PROM_READ, MS5611_RESET, MS5611_RESET_OK, MS5611_SLAVE_ADDR, MS5611_SOFT_RESET, MS5611_SPI_DEV, MS5611_START_CONV_D1, ms5611_status, ms5611_trans, MS5611_UNINIT, navdata_baro_available, sys_time::nb_sec, prom_cnt, spi_submit(), startup_cnt, BaroBoard::status, Baro::status, i2c_transaction::status, adc_buf::sum, TRUE, and BaroBoard::value_filtered.
Referenced by handle_periodic_tasks(), main_periodic_task(), sensors_task(), and test_baro_periodic().
Variable Documentation
struct Baro baro
Definition at line 36 of file baro_board.c.
Referenced by baro_board_calibrate(), baro_event(), baro_feed_value(), baro_init(), baro_periodic(), ins_propagate(), ins_update_baro(), ins_update_sonar(), main_on_baro_abs(), on_overo_link_msg_received(), test_baro_on_baro_abs(), test_baro_on_baro_diff(), and vi_overo_link_on_msg_received().