Paparazzi UAS: sw/airborne/boards/booz/baro_board.c File Reference
baro_board.c File Reference
#include "subsystems/sensors/baro.h"
#include "generated/airframe.h"
#include "led.h"
Macros
#define BOOZ_ANALOG_BARO_THRESHOLD 850
Functions
void baro_init (void)
void baro_periodic (void)
void baro_board_calibrate (void)
Variables
struct Baro baro
struct BaroBoard baro_board
Macro Definition Documentation
#define BOOZ_ANALOG_BARO_THRESHOLD 850
Definition at line 31 of file baro_board.c.
Referenced by baro_board_calibrate().
Function Documentation
void baro_board_calibrate (void)
Definition at line 68 of file baro_board.c.
References baro, baro_board, BOOZ_ANALOG_BARO_THRESHOLD, BS_RUNNING, DACSet(), LED_ON, LED_TOGGLE, BaroBoard::offset, Baro::status, and BaroBoard::value_filtered.
Referenced by baro_periodic().
void baro_init (void)
Definition at line 38 of file baro_board.c.
References Baro::absolute, adc_buf_channel(), ADC_CHANNEL_BARO, baro, baro_board, BS_UNINITIALIZED, BaroBoard::buf, DACSet(), BaroBoard::data_available, DEFAULT_AV_NB_SAMPLE, Baro::differential, FALSE, LED_OFF, BaroBoard::offset, Baro::status, and BaroBoard::value_filtered.
void baro_periodic (void)
Definition at line 56 of file baro_board.c.
References Baro::absolute, adc_buf::av_nb_sample, baro, baro_board, baro_board_calibrate(), BS_UNINITIALIZED, BaroBoard::buf, BaroBoard::data_available, Baro::status, adc_buf::sum, TRUE, and BaroBoard::value_filtered.
Variable Documentation
struct Baro baro
Definition at line 34 of file baro_board.c.
struct BaroBoard baro_board
Definition at line 35 of file baro_board.c.
Referenced by baro_board_calibrate(), baro_board_SetOffset(), baro_event(), baro_init(), and baro_periodic().