Paparazzi UAS: sw/airborne/subsystems/navigation/discsurvey.h File Reference
discsurvey.h File Reference
#include "std.h"
Functions
bool_t disc_survey_init (float grid)
bool_t disc_survey (uint8_t c, float radius)
Detailed Description
Definition in file discsurvey.h.
Function Documentation
bool_t disc_survey (uint8_t c, float radius)
Not null even if wind_east=wind_north=0
Definition at line 52 of file discsurvey.c.
References c, c1, c2, DOWNWIND, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), nav_survey_shift, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, radius, SEGMENT, sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), TRUE, UTURN, WaypointAlt, WaypointX, WaypointY, point::x, FloatVect2::x, EnuCoor_f::x, point::y, FloatVect2::y, and EnuCoor_f::y.
bool_t disc_survey_init (float grid)
Definition at line 43 of file discsurvey.c.
References c1, DOWNWIND, FALSE, nav_survey_shift, sign, stateGetPositionEnu_f(), point::x, EnuCoor_f::x, point::y, and EnuCoor_f::y.