Paparazzi UAS: sw/airborne/boards/ardrone/gpio_ardrone.c File Reference
gpio_ardrone.c File Reference
ardrone GPIO driver
#include <stdio.h>
#include <stdlib.h>
#include "gpio_ardrone.h"
Functions
int gpio_set (int nr, int val)
Detailed Description
ardrone GPIO driver
Definition in file gpio_ardrone.c.
Function Documentation
int gpio_set (int nr, int val)
Definition at line 32 of file gpio_ardrone.c.
Referenced by actuators_ardrone_init(), can_hw_init(), gpio_output_high(), main(), ms2100_arch_init(), radio_control_spektrum_try_bind(), SpiSlaveUnselect(), and w5100_init().