Paparazzi UAS: sw/airborne/mcu_periph/gpio.h File Reference
gpio.h File Reference
Some architecture independent helper functions for GPIOs.
#include "std.h"
#include "mcu_periph/gpio_arch.h"
Functions
void gpio_setup_output (uint32_t port, uint16_t pin)
Setup gpio pin as generic output.
void gpio_setup_input (uint32_t port, uint16_t pin)
Setup a gpio pin as generic input.
Detailed Description
Some architecture independent helper functions for GPIOs.
Definition in file gpio.h.
Function Documentation
void gpio_setup_input (uint32_t port, uint16_t pin)
Setup a gpio pin as generic input.
Referenced by radio_control_spektrum_try_bind().
void gpio_setup_output (uint32_t port, uint16_t pin)
Setup gpio pin as generic output.
Referenced by imu_impl_init(), radio_control_spektrum_try_bind(), and spi_init_slaves().