Paparazzi UAS: sw/airborne/subsystems/imu/imu_drotek_10dof_v2.c File Reference
imu_drotek_10dof_v2.c File Reference
Driver for the Drotek 10DOF V2 IMU.
#include "subsystems/imu.h"
#include "mcu_periph/i2c.h"
Macros
#define DROTEK_2_LOWPASS_FILTER MPU60X0_DLPF_42HZ
#define DROTEK_2_SMPLRT_DIV 9
#define DROTEK_2_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define DROTEK_2_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
#define DROTEK_2_MPU_I2C_ADDR MPU60X0_ADDR_ALT
#define DROTEK_2_HMC_I2C_ADDR HMC58XX_ADDR
Functions
void imu_impl_init (void)
void imu_periodic (void)
void imu_drotek2_event (void)
bool_t imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void *mpu)
callback function to configure hmc5883 mag
Variables
struct ImuDrotek2 imu_drotek2
Detailed Description
Driver for the Drotek 10DOF V2 IMU.
MPU6050 + HMC5883 + MS5611 Reading the baro is not part of the IMU driver.
By default the axes orientation should be as printed on the pcb, meaning z-axis pointing down if ICs are facing down. The orientation can be switched so that the IMU can be mounted ICs facing up by defining IMU_DROTEK_2_ORIENTATION_IC_UP.
Definition in file imu_drotek_10dof_v2.c.
Macro Definition Documentation
#define DROTEK_2_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 53 of file imu_drotek_10dof_v2.c.
Referenced by imu_impl_init().
#define DROTEK_2_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 48 of file imu_drotek_10dof_v2.c.
Referenced by imu_impl_init().
#define DROTEK_2_HMC_I2C_ADDR HMC58XX_ADDR
Definition at line 63 of file imu_drotek_10dof_v2.c.
Referenced by imu_impl_init().
#define DROTEK_2_LOWPASS_FILTER MPU60X0_DLPF_42HZ
Definition at line 40 of file imu_drotek_10dof_v2.c.
Referenced by imu_impl_init().
#define DROTEK_2_MPU_I2C_ADDR MPU60X0_ADDR_ALT
Definition at line 58 of file imu_drotek_10dof_v2.c.
Referenced by imu_impl_init().
#define DROTEK_2_SMPLRT_DIV 9
Definition at line 41 of file imu_drotek_10dof_v2.c.
Referenced by imu_impl_init().
Function Documentation
bool_t imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void * mpu)
callback function to configure hmc5883 mag
Returns
TRUE if mag configuration finished
Definition at line 152 of file imu_drotek_10dof_v2.c.
References FALSE, ImuDrotek2::hmc, hmc58xx_start_configure(), imu_drotek2, Hmc58xx::initialized, and TRUE.
Referenced by imu_impl_init().
void imu_drotek2_event (void)
Definition at line 109 of file imu_drotek_10dof_v2.c.
References Imu::accel_unscaled, ImuDrotek2::accel_valid, Hmc58xx::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Hmc58xx::data_available, Mpu60x0_I2c::data_rates, FALSE, Imu::gyro_unscaled, ImuDrotek2::gyro_valid, ImuDrotek2::hmc, hmc58xx_event(), imu, imu_drotek2, Imu::mag_unscaled, ImuDrotek2::mag_valid, ImuDrotek2::mpu, mpu60x0_i2c_event(), Int16Rates::p, Int32Rates::p, Int16Rates::q, Int32Rates::q, Int16Rates::r, Int32Rates::r, Mpu60x0_I2c::rates, RATES_COPY, TRUE, Mpu60x0_I2c::vect, Hmc58xx::vect, VECT3_COPY, Int16Vect3::x, Int32Vect3::x, Int16Vect3::y, Int32Vect3::y, Int16Vect3::z, and Int32Vect3::z.
Referenced by ImuEvent().
void imu_impl_init (void)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Definition at line 70 of file imu_drotek_10dof_v2.c.
References Mpu60x0Config::accel_range, ImuDrotek2::accel_valid, Mpu60x0_I2c::config, Mpu60x0I2cSlave::configure, Mpu60x0Config::dlpf_cfg, DROTEK_2_ACCEL_RANGE, DROTEK_2_GYRO_RANGE, DROTEK_2_HMC_I2C_ADDR, DROTEK_2_LOWPASS_FILTER, DROTEK_2_MPU_I2C_ADDR, DROTEK_2_SMPLRT_DIV, FALSE, Mpu60x0Config::gyro_range, ImuDrotek2::gyro_valid, ImuDrotek2::hmc, hmc58xx_init(), Mpu60x0Config::i2c_bypass, imu_drotek2_configure_mag_slave(), ImuDrotek2::mag_valid, ImuDrotek2::mpu, mpu60x0_i2c_init(), Mpu60x0Config::nb_slaves, Mpu60x0Config::slaves, Mpu60x0Config::smplrt_div, and TRUE.
void imu_periodic (void)
Definition at line 98 of file imu_drotek_10dof_v2.c.
References Mpu60x0_I2c::config, ImuDrotek2::hmc, hmc58xx_read(), imu_drotek2, Mpu60x0Config::initialized, ImuDrotek2::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
struct ImuDrotek2 imu_drotek2
Definition at line 68 of file imu_drotek_10dof_v2.c.
Referenced by imu_drotek2_configure_mag_slave(), imu_drotek2_event(), imu_periodic(), and ImuEvent().