Paparazzi UAS: sw/airborne/subsystems/ins.h File Reference
ins.h File Reference
Integrated Navigation System interface.
#include "std.h"
#include "math/pprz_geodetic_int.h"
#include "math/pprz_algebra_float.h"
#include "state.h"
Data Structures
struct Ins
Inertial Navigation System state.
Macros
#define INS_UNINIT 0
#define INS_RUNNING 1
Functions
void ins_init (void)
INS initialization.
void ins_periodic (void)
INS periodic call.
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
void ins_realign_v (float z)
INS vertical realign.
void ins_propagate (void)
Propagation.
void ins_update_baro (void)
Update INS state with barometer measurements.
void ins_update_gps (void)
Update INS state with GPS measurements.
void ins_update_sonar (void)
Update INS state with sonar measurements.
Variables
struct Ins ins
global INS state
Detailed Description
Integrated Navigation System interface.
Definition in file ins.h.
Macro Definition Documentation
#define INS_RUNNING 1
Definition at line 36 of file ins.h.
Referenced by ins_init().
#define INS_UNINIT 0
Definition at line 35 of file ins.h.
Function Documentation
void ins_init (void)
INS initialization.
Called at startup. Needs to be implemented by each INS algorithm.
Definition at line 178 of file ins_xsens700.c.
References LlaCoor_i::alt, alt_kalman_init(), b2_hff_init(), baro_median, ecef_of_lla_i(), EstimatorSetAlt, FALSE, gps, ground_alt, Ins::hf_realign, LtpDef_i::hmsl, init_median_filter(), ins, ins_baro_alt, ins_baro_initialised, ins_ltp_accel, ins_ltp_def, ins_ltp_pos, ins_ltp_speed, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_qfe, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, INS_RUNNING, INS_SONAR_OFFSET, INT32_RAD_OF_DEG, INT32_VECT3_ZERO, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def_from_ecef_i(), ltp_def_from_lla_i(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, GpsState::nb_channels, sonar_median, stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), stateSetPositionUtm_f(), Ins::status, TRUE, UNINIT, Ins::vf_realign, vff_init(), xsens_configured, xsens_msg_statusword, xsens_status, and xsens_time_stamp.
Referenced by ahrs_init(), imu_init(), init_ap(), and main_init().
void ins_periodic (void)
INS periodic call.
Needs to be implemented by each INS algorithm.
Definition at line 75 of file ins_alt_float.c.
Referenced by sensors_task().
void ins_propagate (void)
Propagation.
Usually integrates the gyro rates to angles. Reads the global imu data struct. Needs to be implemented by each INS algorithm.
Definition at line 84 of file ins_alt_float.c.
References Imu::accel, AhrsARDrone::accel, ACCEL_BFP_OF_REAL, ACCEL_FLOAT_OF_BFP, ahrs_impl, AhrsARDrone::altitude, b2_hff_propagate(), baro, Imu::body_to_imu_rmat, BS_RUNNING, FLOAT_RMAT_VECT3_TRANSP_MUL, imu, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_RMAT_TRANSP_VMULT, POS_BFP_OF_REAL, AhrsARDrone::speed, SPEED_BFP_OF_REAL, stateGetNedToBodyRMat_f(), stateGetNedToBodyRMat_i(), stateSetAccelNed_f(), stateSetPositionNed_i(), stateSetSpeedNed_f(), Baro::status, vff_propagate(), vff_z, vff_zdot, vff_zdotdot, NedCoor_f::x, Int32Vect3::x, NedCoor_f::y, Int32Vect3::y, NedCoor_f::z, NedCoor_i::z, and Int32Vect3::z.
Referenced by on_gyro_accel_event(), and on_gyro_event().
void ins_realign_h (struct FloatVect2 pos, struct FloatVect2 speed)
INS horizontal realign.
Parameters
pos new horizontal position to set
speed new horizontal speed to set Needs to be implemented by each INS algorithm.
Definition at line 78 of file ins_alt_float.c.
References b2_hff_realign().
Referenced by track_event().
void ins_realign_v (float z)
INS vertical realign.
Parameters
z new altitude to set Needs to be implemented by each INS algorithm.
Definition at line 81 of file ins_alt_float.c.
References vff_realign(), and EcefCoor_i::z.
void ins_update_baro (void)
Update INS state with barometer measurements.
Reads the global baro data struct. Needs to be implemented by each INS algorithm.
Definition at line 87 of file ins_alt_float.c.
References Baro::absolute, ACCEL_BFP_OF_REAL, UtmCoor_f::alt, baro, baro_median, BS_RUNNING, EstimatorSetAlt, FALSE, ground_alt, ins, ins_alt, ins_alt_dot, ins_baro_alt, ins_baro_initialised, ins_ltp_accel, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, ins_qfe, POS_BFP_OF_REAL, POS_FLOAT_OF_BFP, sonar_meas, SPEED_BFP_OF_REAL, stateGetPositionUtm_f(), stateGetSpeedNed_f(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), Baro::status, TRUE, update_median_filter(), UTM_COPY, Ins::vf_realign, vff_realign(), vff_update(), vff_update_baro(), vff_z, vff_zdot, vff_zdotdot, NedCoor_f::z, and NedCoor_i::z.
Referenced by on_baro_abs_event().
void ins_update_gps (void)
Update INS state with GPS measurements.
Reads the global gps data struct. Needs to be implemented by each INS algorithm.
Definition at line 119 of file ins_alt_float.c.
References LlaCoor_i::alt, UtmCoor_f::alt, b2_hff_realign(), b2_hff_update_gps(), UtmCoor_f::east, UtmCoor_i::east, GpsState::ecef_pos, GpsState::ecef_vel, EstimatorSetAlt, FALSE, GpsState::fix, gps, GPS_FIX_3D, Ins::hf_realign, GpsState::hmsl, LtpDef_i::hmsl, ins, ins_alt, ins_alt_dot, ins_gps_pos_cm_ned, ins_gps_speed_cm_s_ned, ins_ltp_def, ins_ltp_pos, ins_ltp_speed, INS_NED_TO_STATE, INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_SPEED_OF_CM_S_DEN, INT32_SPEED_OF_CM_S_NUM, INT32_VECT2_RSHIFT, INT32_VECT2_SCALE_2, INT32_VECT3_SCALE_2, LtpDef_i::lla, GpsState::lla_pos, ltp_def_from_ecef_i(), nav_utm_zone0, ned_of_ecef_point_i(), ned_of_ecef_vect_i(), GpsState::ned_vel, UtmCoor_f::north, UtmCoor_i::north, stateSetLocalOrigin_i(), stateSetPositionNed_i(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), TRUE, GpsState::utm_pos, VECT2_ADD, VECT2_ASSIGN, VECT2_COPY, VECT2_SDIV, NedCoor_i::x, NedCoor_i::y, NedCoor_f::z, NedCoor_i::z, and UtmCoor_f::zone.
Referenced by on_gps_event(), and on_gps_solution().
void ins_update_sonar (void)
Update INS state with sonar measurements.
Reads the global #sonar data struct. Needs to be implemented by each INS algorithm.
Definition at line 145 of file ins_alt_float.c.
References Baro::absolute, baro, BS_RUNNING, DefaultChannel, DefaultDevice, ins_baro_alt, ins_sonar_offset, POS_BFP_OF_REAL, POS_FLOAT_OF_BFP, sonar_meas, sonar_median, stabilization_cmd, Baro::status, update_median_filter(), variance_float(), vff_offset, VFF_R_SONAR_0, VFF_R_SONAR_OF_M, vff_update_alt_conf(), and vff_update_offset().
Variable Documentation
struct Ins ins
global INS state
Definition at line 30 of file ins.c.
Referenced by imu_periodic(), ins_init(), ins_update_baro(), ins_update_gps(), nav_reset_alt(), nav_reset_reference(), and track_event().