Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_fbw.h File Reference
main_fbw.h File Reference
FBW (FlyByWire) process API.
#include "std.h"
Macros
#define FBW_MODE_MANUAL 0
Fly by wire modes.
#define FBW_MODE_AUTO 1
#define FBW_MODE_FAILSAFE 2
#define FBW_MODE_OF_PPRZ(mode) ((mode) < THRESHOLD_MANUAL_PPRZ ? FBW_MODE_MANUAL : FBW_MODE_AUTO)
Functions
void init_fbw (void)
void handle_periodic_tasks_fbw (void)
void periodic_task_fbw (void)
void event_task_fbw (void)
Variables
uint8_t fbw_mode
bool_t failsafe_mode
Detailed Description
FBW (FlyByWire) process API.
Definition in file main_fbw.h.
Macro Definition Documentation
#define FBW_MODE_AUTO 1
Definition at line 36 of file main_fbw.h.
Referenced by event_task_fbw(), and periodic_task_fbw().
#define FBW_MODE_FAILSAFE 2
Definition at line 37 of file main_fbw.h.
Referenced by event_task_fbw(), init_fbw(), and set_failsafe_mode().
#define FBW_MODE_MANUAL 0
Fly by wire modes.
Definition at line 35 of file main_fbw.h.
Referenced by handle_rc_frame(), and periodic_task_fbw().
#define FBW_MODE_OF_PPRZ (mode) ((mode) < THRESHOLD_MANUAL_PPRZ ? FBW_MODE_MANUAL : FBW_MODE_AUTO)
Definition at line 38 of file main_fbw.h.
Referenced by handle_rc_frame().
Function Documentation
void event_task_fbw (void)
Definition at line 133 of file main_fbw.c.
References ap_state, autopilot_mode, command_pitch_trim, command_roll_trim, command_yaw_trim, commands, DatalinkEvent, FALSE, fbw_mode, FBW_MODE_AUTO, FBW_MODE_FAILSAFE, fbw_new_actuators, handle_rc_frame(), i2c_event(), inter_mcu_received_ap, link_mcu_event_task(), link_mcu_received, MAX_PPRZ, RadioControlEvent, set_failsafe_mode(), SetActuatorsFromCommands, and SetCommands.
Referenced by sim_periodic_task().
void handle_periodic_tasks_fbw (void)
Definition at line 260 of file main_fbw.c.
References electrical_periodic(), electrical_tid, fbw_periodic_tid, periodic_task_fbw(), and sys_time_check_and_ack_timer().
void init_fbw (void)
Definition at line 75 of file main_fbw.c.
References actuators_init(), commands_failsafe, electrical_init(), electrical_tid, fbw_mode, FBW_MODE_FAILSAFE, fbw_new_actuators, fbw_periodic_tid, link_mcu_init(), mcu_init(), mcu_int_enable, PERIODIC_FREQUENCY, radio_control_init(), SetCommands, and sys_time_register_timer().
Referenced by sim_init().
void periodic_task_fbw (void)
Definition at line 227 of file main_fbw.c.
References actuators, DefaultChannel, DefaultDevice, fbw_downlink_periodic_task(), fbw_mode, FBW_MODE_AUTO, FBW_MODE_MANUAL, link_mcu_periodic_task(), radio_control, radio_control_periodic_task(), RC_REALLY_LOST, set_failsafe_mode(), and RadioControl::status.
Referenced by handle_periodic_tasks_fbw(), and sim_periodic_task().
Variable Documentation
bool_t failsafe_mode
uint8_t fbw_mode
Definition at line 56 of file main_fbw.c.
Referenced by event_task_fbw(), handle_rc_frame(), init_fbw(), periodic_task_fbw(), and set_failsafe_mode().