Paparazzi UAS: sw/airborne/peripherals/mpu60x0.c File Reference
mpu60x0.c File Reference
MPU-60X0 driver common functions (I2C and SPI).
#include "peripherals/mpu60x0.h"
Functions
void mpu60x0_set_default_config (struct Mpu60x0Config *c)
void mpu60x0_send_config (Mpu60x0ConfigSet mpu_set, void *mpu, struct Mpu60x0Config *config)
Configuration sequence called once before normal use.
Detailed Description
MPU-60X0 driver common functions (I2C and SPI).
Still needs the either the I2C or SPI specific implementation.
Definition in file mpu60x0.c.
Function Documentation
void mpu60x0_send_config (Mpu60x0ConfigSet mpu_set, void * mpu, struct Mpu60x0Config * config)
Configuration sequence called once before normal use.
Definition at line 51 of file mpu60x0.c.
References Mpu60x0Config::accel_range, Mpu60x0Config::clk_sel, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::drdy_int_enable, Mpu60x0Config::gyro_range, Mpu60x0Config::init_status, Mpu60x0Config::initialized, MPU60X0_CONF_ACCEL, MPU60X0_CONF_DLPF, MPU60X0_CONF_DONE, MPU60X0_CONF_GYRO, MPU60X0_CONF_I2C_SLAVES, MPU60X0_CONF_INT_ENABLE, MPU60X0_CONF_PWR, MPU60X0_CONF_RESET, MPU60X0_CONF_SD, MPU60X0_CONF_USER_RESET, mpu60x0_configure_i2c_slaves(), MPU60X0_FIFO_RESET, MPU60X0_I2C_MST_RESET, MPU60X0_REG_ACCEL_CONFIG, MPU60X0_REG_CONFIG, MPU60X0_REG_GYRO_CONFIG, MPU60X0_REG_INT_ENABLE, MPU60X0_REG_PWR_MGMT_1, MPU60X0_REG_SMPLRT_DIV, MPU60X0_REG_USER_CTRL, MPU60X0_SIG_COND_RESET, Mpu60x0Config::nb_slaves, Mpu60x0Config::smplrt_div, and TRUE.
Referenced by mpu60x0_i2c_event(), mpu60x0_i2c_start_configure(), mpu60x0_spi_event(), and mpu60x0_spi_start_configure().
void mpu60x0_set_default_config (struct Mpu60x0Config * c)
Definition at line 32 of file mpu60x0.c.
References Mpu60x0Config::accel_range, Mpu60x0Config::clk_sel, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::drdy_int_enable, FALSE, Mpu60x0Config::gyro_range, Mpu60x0Config::i2c_bypass, MPU60X0_DEFAULT_AFS_SEL, MPU60X0_DEFAULT_CLK_SEL, MPU60X0_DEFAULT_DLPF_CFG, MPU60X0_DEFAULT_FS_SEL, MPU60X0_DEFAULT_SMPLRT_DIV, Mpu60x0Config::nb_bytes, Mpu60x0Config::nb_slaves, and Mpu60x0Config::smplrt_div.
Referenced by mpu60x0_i2c_init(), and mpu60x0_spi_init().