Paparazzi UAS: sw/airborne/subsystems/navigation/OSAMNav.h File Reference
OSAMNav.h File Reference
#include "std.h"
Data Structures
struct Point2D
struct Line
Macros
#define PolygonSize 10
#define MaxFloat 1000000000
#define MinFloat -1000000000
Functions
bool_t FlowerNav (void)
bool_t InitializeFlower (uint8_t CenterWP, uint8_t EdgeWP)
bool_t InitializeBungeeTakeoff (uint8_t BungeeWP)
bool_t BungeeTakeoff (void)
bool_t InitializeSkidLanding (uint8_t AFWP, uint8_t TDWP, float radius)
bool_t SkidLanding (void)
bool_t InitializePolygonSurvey (uint8_t FirstWP, uint8_t Size, float Sweep, float Orientation)
bool_t PolygonSurvey (void)
bool_t InitializeVerticalRaster (void)
bool_t VerticalRaster (uint8_t wp1, uint8_t wp2, float radius, float AltSweep)
bool_t FlightLine (uint8_t From_WP, uint8_t To_WP, float radius, float Space_Before, float Space_After)
bool_t FlightLineBlock (uint8_t First_WP, uint8_t Last_WP, float radius, float Space_Before, float Space_After)
void TranslateAndRotateFromWorld (struct Point2D *p, float Zrot, float transX, float transY)
void RotateAndTranslateToWorld (struct Point2D *p, float Zrot, float transX, float transY)
Rotates point round z by -Zrot then translates so (0,0) becomes (transX,transY)
void FindInterceptOfTwoLines (float *x, float *y, struct Line L1, struct Line L2)
float EvaluateLineForY (float x, struct Line L)
float EvaluateLineForX (float y, struct Line L)
float DistanceEquation (struct Point2D p1, struct Point2D p2)
Variables
uint16_t PolySurveySweepNum
uint16_t PolySurveySweepBackNum
Detailed Description
Definition in file OSAMNav.h.
Macro Definition Documentation
#define MaxFloat 1000000000
Definition at line 46 of file OSAMNav.h.
Referenced by InitializePolygonSurvey().
#define MinFloat -1000000000
Definition at line 47 of file OSAMNav.h.
#define PolygonSize 10
Definition at line 45 of file OSAMNav.h.
Function Documentation
bool_t BungeeTakeoff (void)
Definition at line 260 of file OSAMNav.c.
References AboveLine, BungeeAlt, BungeeWaypoint, CTakeoffStatus, FALSE, Finished, initialx, initialy, kill_throttle, Launch, nav_init_stage(), nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavVerticalThrottleMode, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), Takeoff_Height, Takeoff_MinSpeed, Takeoff_Speed, TDistance, Throttle, throttlePx, throttlePy, ThrottleSlope, TRUE, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
float DistanceEquation (struct Point2D p1, struct Point2D p2)
Definition at line 1217 of file OSAMNav.c.
References Point2D::x, and Point2D::y.
float EvaluateLineForX (float y, struct Line L)
Definition at line 1212 of file OSAMNav.c.
References Line::b, and Line::m.
Referenced by InitializePolygonSurvey(), and PolygonSurvey().
float EvaluateLineForY (float x, struct Line L)
Definition at line 1207 of file OSAMNav.c.
References Line::b, and Line::m.
void FindInterceptOfTwoLines (float * x, float * y, struct Line L1, struct Line L2)
Definition at line 1201 of file OSAMNav.c.
References Line::b, and Line::m.
Referenced by InitializePolygonSurvey().
bool_t FlightLine (uint8_t From_WP, uint8_t To_WP, float radius, float Space_Before, float Space_After)
Definition at line 1032 of file OSAMNav.c.
References CFLStatus, FALSE, FLCircle, FLCircleS, FLFinished, FLFROMWP, FLInitialize, FLLine, FLQDR, FLRadius, FLTOWP, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCircleCount, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, radius, stateGetPositionEnu_f(), TranslateAndRotateFromWorld(), TRUE, waypoints, WaypointX, WaypointY, Point2D::x, EnuCoor_f::x, Point2D::y, and EnuCoor_f::y.
Referenced by FlightLineBlock().
bool_t FlightLineBlock (uint8_t First_WP, uint8_t Last_WP, float radius, float Space_Before, float Space_After)
Definition at line 1139 of file OSAMNav.c.
References CFLStatus, FALSE, FLBlockCount, FlightLine(), FLInitialize, and TRUE.
bool_t FlowerNav (void)
Definition at line 96 of file OSAMNav.c.
References point::a, Center, CFlowerStatus, Circle, CircleX, CircleY, DistanceFromCenter, Edge, EdgeCurrentX, EdgeCurrentY, FALSE, FlowerLine, Flowerradius, FlowerTheta, Fly2X, Fly2Y, FlyFromX, FlyFromY, nav_circle_XY(), nav_init_stage(), nav_radius, nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, Outside, stateGetPositionEnu_f(), TransCurrentX, TransCurrentY, TRUE, waypoints, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
bool_t InitializeBungeeTakeoff (uint8_t BungeeWP)
Definition at line 206 of file OSAMNav.c.
References AboveLine, BungeeAlt, BungeeWaypoint, CTakeoffStatus, FALSE, initialx, initialy, kill_throttle, Launch, stateGetPositionEnu_f(), Takeoff_Distance, TDistance, throttlePx, throttlePy, ThrottleSlope, TRUE, waypoints, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
bool_t InitializeFlower (uint8_t CenterWP, uint8_t EdgeWP)
Definition at line 66 of file OSAMNav.c.
References Center, CFlowerStatus, CircleX, CircleY, DistanceFromCenter, Edge, EdgeCurrentX, EdgeCurrentY, FALSE, FlowerLine, Flowerradius, FlowerTheta, Fly2X, Fly2Y, FlyFromX, FlyFromY, Outside, stateGetPositionEnu_f(), TransCurrentX, TransCurrentY, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
bool_t InitializePolygonSurvey (uint8_t FirstWP, uint8_t Size, float Sweep, float Orientation)
Definition at line 378 of file OSAMNav.c.
References Line::b, CSurveyStatus, dSweep, EdgeMaxY, EdgeMinY, Edges, Entry, EvaluateLineForX(), FALSE, FindInterceptOfTwoLines(), Init, LINE_STOP_FUNCTION, Line::m, MaxFloat, MaxY, PolySurveySweepBackNum, PolySurveySweepNum, SmallestCorner, SurveyCircle, SurveyCircleQdr, SurveyEntryWP, SurveyFromWP, SurveyRadius, SurveySize, SurveyTheta, SurveyToWP, TranslateAndRotateFromWorld(), TRUE, waypoints, Point2D::x, EnuCoor_i::x, Point2D::y, and EnuCoor_i::y.
bool_t InitializeSkidLanding (uint8_t AFWP, uint8_t TDWP, float radius)
Definition at line 917 of file OSAMNav.c.
References AFWaypoint, ApproachQDR, CircleDown, CLandingStatus, FALSE, FinalLandAltitude, FinalLandCount, LandAppAlt, LandCircle, LandCircleQDR, Landing_AFHeight, Landing_FinalHeight, LandRadius, radius, stateGetPositionEnu_f(), TDWaypoint, waypoints, WaypointX, WaypointY, Point2D::x, Point2D::y, and EnuCoor_f::z.
bool_t InitializeVerticalRaster (void)
Definition at line 771 of file OSAMNav.c.
References FALSE, and LR12.
bool_t PolygonSurvey (void)
Definition at line 574 of file OSAMNav.c.
References CSurveyStatus, dSweep, EdgeMaxY, EdgeMinY, Edges, Entry, EvaluateLineForX(), FALSE, Init, LINE_START_FUNCTION, LINE_STOP_FUNCTION, MaxY, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCircleCount, NavCircleCountNoRewind, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, PolySurveySweepBackNum, PolySurveySweepNum, RotateAndTranslateToWorld(), SmallestCorner, stateGetPositionEnu_f(), SurveyCircle, SurveyCircleQdr, SurveyEntryWP, SurveyFromWP, SurveyRadius, SurveySize, SurveyTheta, SurveyToWP, Sweep, SweepCircle, TRUE, waypoints, Point2D::x, and Point2D::y.
void RotateAndTranslateToWorld (struct Point2D * p, float Zrot, float transX, float transY)
Rotates point round z by -Zrot then translates so (0,0) becomes (transX,transY)
Definition at line 1190 of file OSAMNav.c.
References Point2D::x, and Point2D::y.
Referenced by PolygonSurvey().
bool_t SkidLanding (void)
Definition at line 956 of file OSAMNav.c.
References AFWaypoint, Approach, ApproachQDR, CircleDown, CLandingStatus, Final, FinalLandAltitude, FinalLandCount, kill_throttle, LandAppAlt, LandCircle, LandCircleQDR, Landing_FinalStageTime, LandingWait, LandRadius, nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCircleCount, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, stage_time, stateGetPositionEnu_f(), TDWaypoint, TRUE, waypoints, WaypointX, WaypointY, Point2D::x, and Point2D::y.
void TranslateAndRotateFromWorld (struct Point2D * p, float Zrot, float transX, float transY)
Definition at line 1177 of file OSAMNav.c.
References Point2D::x, and Point2D::y.
Referenced by FlightLine(), and InitializePolygonSurvey().
bool_t VerticalRaster (uint8_t wp1, uint8_t wp2, float radius, float AltSweep)
Definition at line 776 of file OSAMNav.c.
References point::a, LQC11, LQC12, LQC21, LQC22, LR12, LR21, LTC1, LTC2, nav_circle_XY(), nav_init_stage(), NavApproachingFrom, NavQdrCloseTo, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, stateGetPositionEnu_f(), TRUE, WaypointAlt, waypoints, WaypointX, WaypointY, point::x, and point::y.
Variable Documentation
uint16_t PolySurveySweepBackNum
Definition at line 376 of file OSAMNav.c.
Referenced by InitializePolygonSurvey(), and PolygonSurvey().
uint16_t PolySurveySweepNum
Definition at line 375 of file OSAMNav.c.
Referenced by InitializePolygonSurvey(), and PolygonSurvey().