Paparazzi UAS: sw/airborne/modules/multi/potential.c File Reference
potential.c File Reference
#include <math.h>
#include "subsystems/datalink/downlink.h"
#include "dl_protocol.h"
#include "potential.h"
#include "state.h"
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include "firmwares/fixedwing/guidance/guidance_v.h"
#include "autopilot.h"
#include "subsystems/gps.h"
#include "generated/airframe.h"
Macros
#define POTENTIAL_C
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
#define FORCE_POS_GAIN 1.
#define FORCE_SPEED_GAIN 1.
#define FORCE_CLIMB_GAIN 1.
#define FORCE_MAX_DIST 100.
Functions
void potential_init (void)
int potential_task (void)
Variables
struct force_ potential_force
float force_pos_gain
float force_speed_gain
float force_climb_gain
Detailed Description
Definition in file potential.c.
Macro Definition Documentation
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 9 of file potential.c.
#define FORCE_CLIMB_GAIN 1.
Definition at line 39 of file potential.c.
Referenced by potential_init().
#define FORCE_MAX_DIST 100.
Definition at line 43 of file potential.c.
Referenced by potential_task().
#define FORCE_POS_GAIN 1.
Definition at line 31 of file potential.c.
Referenced by potential_init().
#define FORCE_SPEED_GAIN 1.
Definition at line 35 of file potential.c.
Referenced by potential_init().
#define POTENTIAL_C
Definition at line 4 of file potential.c.
Function Documentation
void potential_init (void)
Definition at line 46 of file potential.c.
References force_::alt, force_::east, force_climb_gain, FORCE_CLIMB_GAIN, force_pos_gain, FORCE_POS_GAIN, force_speed_gain, FORCE_SPEED_GAIN, force_::north, and potential_force.
int potential_task (void)
Definition at line 58 of file potential.c.
References ac_id, force_::alt, ac_info_::alt, force_::climb, ac_info_::climb, ac_info_::course, DefaultChannel, DefaultDevice, desired_x, desired_y, dn, force_::east, ac_info_::east, fly_to_xy(), force_climb_gain, FORCE_MAX_DIST, force_pos_gain, force_speed_gain, get_ac_info(), gps, ac_info_::gspeed, ac_info_::itow, Max, NavVerticalAutoThrottleMode, NavVerticalClimbMode, NB_ACS, force_::north, ac_info_::north, potential_force, force_::speed, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetSpeedEnu_f(), the_acs, GpsState::tow, TRUE, V_CTL_ALTITUDE_MAX_CLIMB, v_ctl_auto_throttle_cruise_throttle, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Variable Documentation
float force_climb_gain
Definition at line 28 of file potential.c.
Referenced by potential_init(), and potential_task().
float force_pos_gain
Definition at line 26 of file potential.c.
Referenced by potential_init(), and potential_task().
float force_speed_gain
Definition at line 27 of file potential.c.
Referenced by potential_init(), and potential_task().
struct force_ potential_force
Definition at line 24 of file potential.c.
Referenced by potential_init(), and potential_task().