Paparazzi UAS: sw/airborne/math/pprz_geodetic_int.c File Reference
pprz_geodetic_int.c File Reference
#include "pprz_geodetic_int.h"
#include "pprz_algebra_int.h"
#include "pprz_geodetic_float.h"
#include "pprz_geodetic_double.h"
Macros
#define HIGH_RES_TRIG_FRAC 20
Functions
void ltp_def_from_ecef_i (struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ltp_def_from_lla_i (struct LtpDef_i *def, struct LlaCoor_i *lla)
void enu_of_ecef_point_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ned_of_ecef_point_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void enu_of_ecef_pos_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct EcefCoor_i *ecef)
Convert a ECEF position to local ENU.
void ned_of_ecef_pos_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct EcefCoor_i *ecef)
Convert a ECEF position to local NED.
void enu_of_ecef_vect_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ned_of_ecef_vect_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct EcefCoor_i *ecef)
void ecef_of_enu_vect_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct EnuCoor_i *enu)
void ecef_of_ned_vect_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct NedCoor_i *ned)
void ecef_of_enu_point_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct EnuCoor_i *enu)
Convert a point in local ENU to ECEF.
void ecef_of_ned_point_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct NedCoor_i *ned)
Convert a point in local NED to ECEF.
void ecef_of_enu_pos_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct EnuCoor_i *enu)
Convert a local ENU position to ECEF.
void ecef_of_ned_pos_i (struct EcefCoor_i *ecef, struct LtpDef_i *def, struct NedCoor_i *ned)
Convert a local NED position to ECEF.
void enu_of_lla_point_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct LlaCoor_i *lla)
void ned_of_lla_point_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct LlaCoor_i *lla)
void enu_of_lla_vect_i (struct EnuCoor_i *enu, struct LtpDef_i *def, struct LlaCoor_i *lla)
void ned_of_lla_vect_i (struct NedCoor_i *ned, struct LtpDef_i *def, struct LlaCoor_i *lla)
void lla_of_ecef_i (struct LlaCoor_i *out, struct EcefCoor_i *in)
void ecef_of_lla_i (struct EcefCoor_i *out, struct LlaCoor_i *in)
Macro Definition Documentation
#define HIGH_RES_TRIG_FRAC 20
Definition at line 25 of file pprz_geodetic_int.c.
Referenced by ecef_of_enu_vect_i(), enu_of_ecef_point_i(), enu_of_ecef_vect_i(), ltp_def_from_ecef_i(), and ltp_def_from_lla_i().
Function Documentation
void ecef_of_enu_point_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct EnuCoor_i * enu)
Convert a point in local ENU to ECEF.
Parameters
[out] ecef ECEF point in cm
[in] def local coordinate system definition
[in] enu ENU point in cm
Definition at line 206 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, ecef_of_enu_vect_i(), and INT32_VECT3_ADD.
Referenced by ecef_of_ned_point_i().
void ecef_of_enu_pos_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct EnuCoor_i * enu)
Convert a local ENU position to ECEF.
Parameters
[out] ecef ECEF position in cm
[in] def local coordinate system definition
[in] enu ENU position in meter << INT32_POS_FRAC
Definition at line 229 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, ecef_of_enu_vect_i(), INT32_POS_FRAC, INT32_VECT3_ADD, INT32_VECT3_RSHIFT, and VECT3_SMUL.
Referenced by ecef_of_ned_pos_i().
void ecef_of_enu_vect_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct EnuCoor_i * enu)
Definition at line 175 of file pprz_geodetic_int.c.
References HIGH_RES_TRIG_FRAC, LtpDef_i::ltp_of_ecef, Int32Mat33::m, EcefCoor_i::x, EnuCoor_i::x, EcefCoor_i::y, EnuCoor_i::y, EcefCoor_i::z, and EnuCoor_i::z.
Referenced by ecef_of_enu_point_i(), ecef_of_enu_pos_i(), and ecef_of_ned_vect_i().
void ecef_of_lla_i (struct EcefCoor_i * out, struct LlaCoor_i * in)
Definition at line 303 of file pprz_geodetic_int.c.
References LlaCoor_d::alt, LlaCoor_i::alt, CM_OF_M, ecef_of_lla_d(), LlaCoor_d::lat, LlaCoor_i::lat, LlaCoor_d::lon, LlaCoor_i::lon, M_OF_MM, RAD_OF_EM7RAD, EcefCoor_d::x, EcefCoor_i::x, EcefCoor_d::y, EcefCoor_i::y, EcefCoor_d::z, and EcefCoor_i::z.
Referenced by enu_of_lla_point_i(), enu_of_lla_vect_i(), ins_init(), ltp_def_from_lla_i(), ned_of_lla_point_i(), ned_of_lla_vect_i(), stateCalcPositionEcef_i(), stateCalcPositionEnu_f(), and stateCalcPositionNed_f().
void ecef_of_ned_point_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct NedCoor_i * ned)
Convert a point in local NED to ECEF.
Parameters
[out] ecef ECEF point in cm
[in] def local coordinate system definition
[in] ned NED point in cm
Definition at line 217 of file pprz_geodetic_int.c.
References ecef_of_enu_point_i(), and ENU_OF_TO_NED.
void ecef_of_ned_pos_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct NedCoor_i * ned)
Convert a local NED position to ECEF.
Parameters
[out] ecef ECEF position in cm
[in] def local coordinate system definition
[in] ned NED position in meter << INT32_POS_FRAC
Definition at line 248 of file pprz_geodetic_int.c.
References ecef_of_enu_pos_i(), and ENU_OF_TO_NED.
Referenced by stateCalcPositionEcef_f(), stateCalcPositionEcef_i(), and stateCalcPositionLla_i().
void ecef_of_ned_vect_i (struct EcefCoor_i * ecef, struct LtpDef_i * def, struct NedCoor_i * ned)
Definition at line 194 of file pprz_geodetic_int.c.
References ecef_of_enu_vect_i(), and ENU_OF_TO_NED.
Referenced by stateCalcAccelEcef_i(), and stateCalcSpeedEcef_i().
void enu_of_ecef_point_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 93 of file pprz_geodetic_int.c.
References LtpDef_i::ecef, HIGH_RES_TRIG_FRAC, LtpDef_i::ltp_of_ecef, Int32Mat33::m, VECT3_DIFF, EcefCoor_i::x, EnuCoor_i::x, EcefCoor_i::y, EnuCoor_i::y, EcefCoor_i::z, and EnuCoor_i::z.
Referenced by enu_of_ecef_pos_i(), enu_of_lla_point_i(), and ned_of_ecef_point_i().
void enu_of_ecef_pos_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Convert a ECEF position to local ENU.
Parameters
[out] enu ENU position in meter << INT32_POS_FRAC
[in] def local coordinate system definition
[in] ecef ECEF position in cm
Definition at line 125 of file pprz_geodetic_int.c.
References enu_of_ecef_point_i(), INT32_POS_FRAC, INT32_VECT3_LSHIFT, and VECT3_SDIV.
Referenced by ned_of_ecef_pos_i(), stateCalcPositionEnu_f(), and stateCalcPositionEnu_i().
void enu_of_ecef_vect_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 150 of file pprz_geodetic_int.c.
References HIGH_RES_TRIG_FRAC, LtpDef_i::ltp_of_ecef, Int32Mat33::m, EcefCoor_i::x, EnuCoor_i::x, EcefCoor_i::y, EnuCoor_i::y, EcefCoor_i::z, and EnuCoor_i::z.
Referenced by enu_of_lla_vect_i(), ned_of_ecef_vect_i(), and stateCalcSpeedEnu_i().
void enu_of_lla_point_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 255 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and enu_of_ecef_point_i().
Referenced by dl_parse_msg(), and stateCalcPositionEnu_i().
void enu_of_lla_vect_i (struct EnuCoor_i * enu, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 267 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and enu_of_ecef_vect_i().
void lla_of_ecef_i (struct LlaCoor_i * out, struct EcefCoor_i * in)
Definition at line 286 of file pprz_geodetic_int.c.
References LlaCoor_d::alt, LlaCoor_i::alt, EM7RAD_OF_RAD, LlaCoor_d::lat, LlaCoor_i::lat, lla_of_ecef_d(), LlaCoor_d::lon, LlaCoor_i::lon, M_OF_CM, MM_OF_M, EcefCoor_d::x, EcefCoor_i::x, EcefCoor_d::y, EcefCoor_i::y, EcefCoor_d::z, and EcefCoor_i::z.
Referenced by ltp_def_from_ecef_i(), and stateCalcPositionLla_i().
void ltp_def_from_ecef_i (struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 27 of file pprz_geodetic_int.c.
References BFP_OF_REAL, LtpDef_i::ecef, HIGH_RES_TRIG_FRAC, LlaCoor_i::lat, LtpDef_i::lla, lla_of_ecef_i(), LlaCoor_i::lon, LtpDef_i::ltp_of_ecef, Int32Mat33::m, RAD_OF_EM7RAD, and VECT3_COPY.
Referenced by gps_skytraq_read_message(), ins_init(), and ins_update_gps().
void ltp_def_from_lla_i (struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 60 of file pprz_geodetic_int.c.
References BFP_OF_REAL, LtpDef_i::ecef, ecef_of_lla_i(), HIGH_RES_TRIG_FRAC, LlaCoor_i::lat, LtpDef_i::lla, LLA_COPY, LlaCoor_i::lon, LtpDef_i::ltp_of_ecef, Int32Mat33::m, and RAD_OF_EM7RAD.
Referenced by ins_init().
void ned_of_ecef_point_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 113 of file pprz_geodetic_int.c.
References enu_of_ecef_point_i(), and ENU_OF_TO_NED.
Referenced by ins_update_gps(), and ned_of_lla_point_i().
void ned_of_ecef_pos_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Convert a ECEF position to local NED.
Parameters
[out] ned NED position in meter << INT32_POS_FRAC
[in] def local coordinate system definition
[in] ecef ECEF position in cm
Definition at line 144 of file pprz_geodetic_int.c.
References enu_of_ecef_pos_i(), and ENU_OF_TO_NED.
Referenced by stateCalcPositionNed_f(), and stateCalcPositionNed_i().
void ned_of_ecef_vect_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct EcefCoor_i * ecef)
Definition at line 168 of file pprz_geodetic_int.c.
References enu_of_ecef_vect_i(), and ENU_OF_TO_NED.
Referenced by gps_skytraq_read_message(), ins_update_gps(), ned_of_lla_vect_i(), stateCalcAccelNed_i(), stateCalcHorizontalSpeedNorm_i(), and stateCalcSpeedNed_i().
void ned_of_lla_point_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 261 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and ned_of_ecef_point_i().
Referenced by stateCalcPositionNed_i().
void ned_of_lla_vect_i (struct NedCoor_i * ned, struct LtpDef_i * def, struct LlaCoor_i * lla)
Definition at line 273 of file pprz_geodetic_int.c.
References ecef_of_lla_i(), and ned_of_ecef_vect_i().