Paparazzi UAS: sw/airborne/firmwares/rotorcraft/datalink.c File Reference
datalink.c File Reference
Handling of messages coming from ground and other A/Cs.
#include "subsystems/datalink/datalink.h"
#include "generated/modules.h"
#include "generated/settings.h"
#include "subsystems/datalink/downlink.h"
#include "messages.h"
#include "dl_protocol.h"
#include "mcu_periph/uart.h"
#include "firmwares/rotorcraft/navigation.h"
#include "math/pprz_geodetic_int.h"
#include "subsystems/ins.h"
Macros
#define DATALINK_C
#define MODULES_DATALINK_C
#define IdOfMsg(x) (x[1])
Functions
void dl_parse_msg (void)
Detailed Description
Handling of messages coming from ground and other A/Cs.
Definition in file datalink.c.
Macro Definition Documentation
#define DATALINK_C
Definition at line 28 of file datalink.c.
#define IdOfMsg (x) (x[1])
Definition at line 54 of file datalink.c.
Referenced by dl_parse_msg().
#define MODULES_DATALINK_C
Definition at line 29 of file datalink.c.
Function Documentation
void dl_parse_msg (void)
NAV
WIND_INFO
Else there is no dl_settings section in the flight plan
Definition at line 56 of file datalink.c.
References ac_id, LlaCoor_i::alt, datalink_time, DefaultChannel, DefaultDevice, dl_buffer, enu_of_lla_point_i(), LtpDef_i::hmsl, IdOfMsg, ins_ltp_def, INT32_RAD_OF_DEG, LlaCoor_i::lat, LED_TOGGLE, LtpDef_i::lla, LlaCoor_i::lon, nav_goto_block(), parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), POS_BFP_OF_REAL, val, VECT3_ASSIGN, waypoints, EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.