Paparazzi UAS: sw/airborne/firmwares/setup/setup_actuators.c File Reference
setup_actuators.c File Reference
#include "generated/airframe.h"
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "subsystems/actuators.h"
#include "firmwares/fixedwing/main_fbw.h"
#include "subsystems/datalink/datalink.h"
#include "subsystems/datalink/pprz_transport.h"
#include "mcu_periph/uart.h"
#include "subsystems/datalink/downlink.h"
#include "generated/settings.h"
Macros
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
#define DATALINK_C
#define IdOfMsg(x) (x[1])
Functions
void dl_parse_msg (void)
void init_fbw (void)
void handle_periodic_tasks_fbw (void)
void periodic_task_fbw (void)
void event_task_fbw (void)
Macro Definition Documentation
#define DATALINK_C
Definition at line 15 of file setup_actuators.c.
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 12 of file setup_actuators.c.
#define IdOfMsg (x) (x[1])
Definition at line 23 of file setup_actuators.c.
Referenced by dl_parse_msg().
Function Documentation
void dl_parse_msg (void)
NAV
WIND_INFO
Else there is no dl_settings section in the flight plan
Definition at line 26 of file setup_actuators.c.
References DefaultChannel, DefaultDevice, dl_buffer, IdOfMsg, LED_TOGGLE, and val.
void event_task_fbw (void)
Definition at line 88 of file setup_actuators.c.
References ap_state, autopilot_mode, command_pitch_trim, command_roll_trim, command_yaw_trim, commands, DatalinkEvent, FALSE, fbw_mode, FBW_MODE_AUTO, FBW_MODE_FAILSAFE, fbw_new_actuators, handle_rc_frame(), i2c_event(), inter_mcu_received_ap, link_mcu_event_task(), link_mcu_received, MAX_PPRZ, RadioControlEvent, set_failsafe_mode(), SetActuatorsFromCommands, and SetCommands.
void handle_periodic_tasks_fbw (void)
Definition at line 71 of file setup_actuators.c.
References electrical_periodic(), electrical_tid, fbw_periodic_tid, periodic_task_fbw(), and sys_time_check_and_ack_timer().
void init_fbw (void)
Definition at line 54 of file setup_actuators.c.
References actuators_init(), commands_failsafe, electrical_init(), electrical_tid, fbw_mode, FBW_MODE_FAILSAFE, fbw_new_actuators, fbw_periodic_tid, link_mcu_init(), mcu_init(), mcu_int_enable, PERIODIC_FREQUENCY, radio_control_init(), SetCommands, and sys_time_register_timer().
void periodic_task_fbw (void)
Definition at line 78 of file setup_actuators.c.
References actuators, DefaultChannel, DefaultDevice, fbw_downlink_periodic_task(), fbw_mode, FBW_MODE_AUTO, FBW_MODE_MANUAL, link_mcu_periodic_task(), radio_control, radio_control_periodic_task(), RC_REALLY_LOST, set_failsafe_mode(), and RadioControl::status.