Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_euler_float.c File Reference
stabilization_attitude_euler_float.c File Reference
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.h"
#include "math/pprz_algebra_float.h"
#include "state.h"
#include "subsystems/radio_control.h"
#include "generated/airframe.h"
Macros
#define MAX_SUM_ERR RadOfDeg(56000)
Functions
void stabilization_attitude_init (void)
void stabilization_attitude_read_rc (bool_t in_flight)
void stabilization_attitude_enter (void)
void stabilization_attitude_set_failsafe_setpoint (void)
void stabilization_attitude_set_from_eulers_i (struct Int32Eulers *sp_euler)
void stabilization_attitude_run (bool_t in_flight)
Variables
struct FloatAttitudeGains stabilization_gains
struct FloatEulers stabilization_att_sum_err
float stabilization_att_fb_cmd [COMMANDS_NB]
float stabilization_att_ff_cmd [COMMANDS_NB]
Macro Definition Documentation
#define MAX_SUM_ERR RadOfDeg(56000)
Definition at line 94 of file stabilization_attitude_euler_float.c.
Referenced by stabilization_attitude_run().
Function Documentation
void stabilization_attitude_enter (void)
Definition at line 73 of file stabilization_attitude_euler_float.c.
References FLOAT_EULERS_ZERO, Int32Eulers::psi, stab_att_sp_euler, stabilization_att_sum_err, stabilization_attitude_get_heading_f(), and stabilization_attitude_ref_enter().
void stabilization_attitude_init (void)
Definition at line 39 of file stabilization_attitude_euler_float.c.
References Int32AttitudeGains::d, Int32AttitudeGains::dd, FLOAT_EULERS_ZERO, Int32AttitudeGains::i, Int32AttitudeGains::p, stabilization_att_sum_err, stabilization_attitude_ref_init(), stabilization_gains, and VECT3_ASSIGN.
void stabilization_attitude_read_rc (bool_t in_flight)
Definition at line 68 of file stabilization_attitude_euler_float.c.
References stab_att_sp_euler, and stabilization_attitude_read_rc_setpoint_eulers_f().
void stabilization_attitude_run (bool_t in_flight)
Definition at line 96 of file stabilization_attitude_euler_float.c.
References Int32AttitudeGains::d, Int32AttitudeGains::dd, EULERS_ADD, EULERS_BOUND_CUBE, EULERS_DIFF, FLOAT_ANGLE_NORMALIZE, FLOAT_EULERS_ZERO, Int32AttitudeGains::i, MAX_SUM_ERR, Int32AttitudeGains::p, FloatRates::p, FloatEulers::phi, Int32Eulers::phi, FloatEulers::psi, Int32Eulers::psi, FloatRates::q, FloatRates::r, RATES_DIFF, stab_att_ref_accel, stab_att_ref_euler, stab_att_ref_rate, stabilization_att_fb_cmd, stabilization_att_ff_cmd, stabilization_att_sum_err, stabilization_attitude_ref_update(), stabilization_cmd, stabilization_gains, stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), FloatEulers::theta, Int32Eulers::theta, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void stabilization_attitude_set_failsafe_setpoint (void)
Definition at line 83 of file stabilization_attitude_euler_float.c.
References Int32Eulers::phi, FloatEulers::psi, Int32Eulers::psi, stab_att_sp_euler, stateGetNedToBodyEulers_f(), and Int32Eulers::theta.
void stabilization_attitude_set_from_eulers_i (struct Int32Eulers * sp_euler)
Definition at line 89 of file stabilization_attitude_euler_float.c.
References EULERS_FLOAT_OF_BFP, and stab_att_sp_euler.
Variable Documentation
float stabilization_att_fb_cmd[COMMANDS_NB]
Definition at line 35 of file stabilization_attitude_euler_float.c.
float stabilization_att_ff_cmd[COMMANDS_NB]
Definition at line 36 of file stabilization_attitude_euler_float.c.
struct FloatEulers stabilization_att_sum_err
Definition at line 33 of file stabilization_attitude_euler_float.c.
struct FloatAttitudeGains stabilization_gains
Definition at line 32 of file stabilization_attitude_euler_float.c.