Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization.c File Reference
stabilization.c File Reference
General stabilization interface for rotorcrafts.
#include "firmwares/rotorcraft/stabilization.h"
Functions
void stabilization_init (void)
Variables
int32_t stabilization_cmd [COMMANDS_NB]
Stabilization commands.
Detailed Description
General stabilization interface for rotorcrafts.
Definition in file stabilization.c.
Function Documentation
void stabilization_init (void)
Definition at line 30 of file stabilization.c.
References stabilization_attitude_init(), stabilization_none_init(), and stabilization_rate_init().
Referenced by autopilot_init().
Variable Documentation
int32_t stabilization_cmd[COMMANDS_NB]
Stabilization commands.
Contains the resulting stabilization commands, regardless of whether rate or attitude is currently used. Range -MAX_PPRZ:MAX_PPRZ
Definition at line 28 of file stabilization.c.
Referenced by autopilot_check_in_flight_no_rc(), autopilot_periodic(), guidance_v_run(), ins_update_sonar(), stabilization_attitude_run(), stabilization_none_run(), and stabilization_rate_run().