Paparazzi UAS: sw/airborne/arch/stm32/subsystems/actuators/actuators_pwm_arch.c File Reference
actuators_pwm_arch.c File Reference
STM32 PWM servos handling.
#include "subsystems/actuators/actuators_pwm_arch.h"
#include "subsystems/actuators/actuators_pwm.h"
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/timer.h>
Macros
#define ONE_MHZ_CLK 1000000
#define SERVO_HZ 40
Default servo update rate in Hz.
#define TIM1_SERVO_HZ SERVO_HZ
#define TIM2_SERVO_HZ SERVO_HZ
#define TIM3_SERVO_HZ SERVO_HZ
#define TIM4_SERVO_HZ SERVO_HZ
#define TIM5_SERVO_HZ SERVO_HZ
Functions
static void actuators_pwm_arch_channel_init (u32 timer_peripheral, enum tim_oc_id oc_id)
Set PWM channel configuration.
static void set_servo_timer (u32 timer, u32 period, u8 channels_mask)
Set GPIO configuration.
void actuators_pwm_arch_init (void)
PWM arch init called by generic pwm driver.
void actuators_pwm_commit (void)
Set pulse widths from actuator values, assumed to be in us.
Variables
int32_t actuators_pwm_values [ACTUATORS_PWM_NB]
Detailed Description
STM32 PWM servos handling.
Definition in file actuators_pwm_arch.c.
Macro Definition Documentation
#define ONE_MHZ_CLK 1000000
Definition at line 43 of file actuators_pwm_arch.c.
Referenced by set_servo_timer().
#define SERVO_HZ 40
Default servo update rate in Hz.
Definition at line 46 of file actuators_pwm_arch.c.
#define TIM1_SERVO_HZ SERVO_HZ
Definition at line 51 of file actuators_pwm_arch.c.
Referenced by actuators_pwm_arch_init().
#define TIM2_SERVO_HZ SERVO_HZ
Definition at line 54 of file actuators_pwm_arch.c.
Referenced by actuators_pwm_arch_init().
#define TIM3_SERVO_HZ SERVO_HZ
Definition at line 57 of file actuators_pwm_arch.c.
Referenced by actuators_pwm_arch_init().
#define TIM4_SERVO_HZ SERVO_HZ
Definition at line 60 of file actuators_pwm_arch.c.
Referenced by actuators_pwm_arch_init().
#define TIM5_SERVO_HZ SERVO_HZ
Definition at line 63 of file actuators_pwm_arch.c.
Referenced by actuators_pwm_arch_init().
Function Documentation
static void actuators_pwm_arch_channel_init (u32 timer_peripheral, enum tim_oc_id oc_id) inline static
Set PWM channel configuration.
Definition at line 68 of file actuators_pwm_arch.c.
Referenced by set_servo_timer().
void actuators_pwm_arch_init (void)
PWM arch init called by generic pwm driver.
Arch dependent init file.
Definition at line 155 of file actuators_pwm_arch.c.
References PWM_SERVO_0_AF, PWM_SERVO_0_GPIO, PWM_SERVO_0_PIN, PWM_SERVO_0_RCC_IOP, PWM_SERVO_1_AF, PWM_SERVO_1_ENA, PWM_SERVO_1_GPIO, PWM_SERVO_1_PIN, PWM_SERVO_1_PINSEL, PWM_SERVO_1_PINSEL_BIT, PWM_SERVO_1_PINSEL_MASK, PWM_SERVO_1_PINSEL_VAL, PWM_SERVO_1_RCC_IOP, PWM_SERVO_2_AF, PWM_SERVO_2_ENA, PWM_SERVO_2_GPIO, PWM_SERVO_2_PIN, PWM_SERVO_2_PINSEL, PWM_SERVO_2_PINSEL_BIT, PWM_SERVO_2_PINSEL_MASK, PWM_SERVO_2_PINSEL_VAL, PWM_SERVO_2_RCC_IOP, PWM_SERVO_3_AF, PWM_SERVO_3_ENA, PWM_SERVO_3_GPIO, PWM_SERVO_3_PIN, PWM_SERVO_3_PINSEL, PWM_SERVO_3_PINSEL_BIT, PWM_SERVO_3_PINSEL_MASK, PWM_SERVO_3_PINSEL_VAL, PWM_SERVO_3_RCC_IOP, PWM_SERVO_4_AF, PWM_SERVO_4_ENA, PWM_SERVO_4_GPIO, PWM_SERVO_4_PIN, PWM_SERVO_4_PINSEL, PWM_SERVO_4_PINSEL_BIT, PWM_SERVO_4_PINSEL_MASK, PWM_SERVO_4_PINSEL_VAL, PWM_SERVO_4_RCC_IOP, PWM_SERVO_5_AF, PWM_SERVO_5_ENA, PWM_SERVO_5_GPIO, PWM_SERVO_5_PIN, PWM_SERVO_5_PINSEL, PWM_SERVO_5_PINSEL_BIT, PWM_SERVO_5_PINSEL_MASK, PWM_SERVO_5_PINSEL_VAL, PWM_SERVO_5_RCC_IOP, PWM_SERVO_6_AF, PWM_SERVO_6_GPIO, PWM_SERVO_6_PIN, PWM_SERVO_6_RCC_IOP, PWM_SERVO_7_AF, PWM_SERVO_7_GPIO, PWM_SERVO_7_PIN, PWM_SERVO_7_RCC_IOP, PWM_SERVO_8_AF, PWM_SERVO_8_GPIO, PWM_SERVO_8_PIN, PWM_SERVO_8_RCC_IOP, PWM_TIM2_CHAN_MASK, PWM_TIM3_CHAN_MASK, PWM_TIM4_CHAN_MASK, PWM_TIM5_CHAN_MASK, PWMLER, PWMLER_LATCH0, PWMMR0, PWMPCR, PWMPR, PWMTCR, PWMTCR_COUNTER_ENABLE, PWMTCR_PWM_ENABLE, SERVOS_PERIOD, set_servo_timer(), TIM1_SERVO_HZ, TIM2_SERVO_HZ, TIM3_SERVO_HZ, TIM4_SERVO_HZ, and TIM5_SERVO_HZ.
void actuators_pwm_commit (void)
Set pulse widths from actuator values, assumed to be in us.
Definition at line 237 of file actuators_pwm_arch.c.
References actuators_pwm_values, PWM_SERVO_0, PWM_SERVO_0_OC, PWM_SERVO_0_TIMER, PWM_SERVO_1, PWM_SERVO_1_OC, PWM_SERVO_1_TIMER, PWM_SERVO_2, PWM_SERVO_2_OC, PWM_SERVO_2_TIMER, PWM_SERVO_3, PWM_SERVO_3_OC, PWM_SERVO_3_TIMER, PWM_SERVO_4, PWM_SERVO_4_OC, PWM_SERVO_4_TIMER, PWM_SERVO_5, PWM_SERVO_5_OC, PWM_SERVO_5_TIMER, PWM_SERVO_6, PWM_SERVO_6_OC, PWM_SERVO_6_TIMER, PWM_SERVO_7, PWM_SERVO_7_OC, PWM_SERVO_7_TIMER, PWM_SERVO_8, PWM_SERVO_8_OC, and PWM_SERVO_8_TIMER.
Referenced by on_overo_link_msg_received(), and test_srvo_periodic().
static void set_servo_timer (u32 timer, u32 period, u8 channels_mask) inline static
Set GPIO configuration.
Set Timer configuration
Definition at line 98 of file actuators_pwm_arch.c.
References actuators_pwm_arch_channel_init(), ONE_MHZ_CLK, and PCLK.
Referenced by actuators_pwm_arch_init().
Variable Documentation
int32_t actuators_pwm_values[ACTUATORS_PWM_NB]
Definition at line 33 of file actuators_pwm_arch.c.
Referenced by actuators_ardrone_commit(), actuators_pwm_commit(), on_overo_link_msg_received(), and test_srvo_periodic().