Paparazzi UAS: sw/airborne/arch/stm32/subsystems/radio_control/spektrum_arch.c File Reference
spektrum_arch.c File Reference
#include <stdint.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/timer.h>
#include <libopencm3/stm32/usart.h>
#include <libopencm3/cm3/nvic.h>
#include "subsystems/radio_control.h"
#include "subsystems/radio_control/spektrum_arch.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/gpio.h"
#include <BOARD_CONFIG>
Data Structures
struct SpektrumStateStruct
Macros
#define SPEKTRUM_CHANNELS_PER_FRAME 7
#define MAX_SPEKTRUM_FRAMES 2
#define MAX_SPEKTRUM_CHANNELS 16
#define MAX_DELAY INT16_MAX
#define DELAY_TIM_FREQUENCY 1000000
#define MASTER_RECEIVER_PULSES 5
#define SLAVE_RECEIVER_PULSES 6
#define TIM_FREQ_1000000 1000000
#define TIM_TICS_FOR_100us 100
#define MIN_FRAME_SPACE 70
#define MAX_BYTE_SPACE 3
#define __PrimaryUart(dev, _x) dev##_x
#define _PrimaryUart(dev, _x) __PrimaryUart(dev, _x)
#define PrimaryUart(_x) _PrimaryUart(RADIO_CONTROL_SPEKTRUM_PRIMARY_PORT, _x)
#define __SecondaryUart(dev, _x) dev##_x
#define _SecondaryUart(dev, _x) __SecondaryUart(dev, _x)
#define SecondaryUart(_x) _SecondaryUart(RADIO_CONTROL_SPEKTRUM_SECONDARY_PORT, _x)
Typedefs
typedef struct SpektrumStateStruct SpektrumStateType
Functions
void SpektrumUartInit (void)
void SpektrumTimerInit (void)
void tim6_irq_handler (void)
static void DelayUs (uint16_t uSecs)
static void DelayMs (uint16_t mSecs)
static void SpektrumDelayInit (void)
void radio_control_impl_init (void)
static void SpektrumParser (uint8_t _c, SpektrumStateType *spektrum_state, bool_t secondary_receiver)
void RadioControlEventImp (void(*frame_handler)(void))
timer_clear_flag (TIM6, TIM_SR_UIF)
if (PrimarySpektrumState.SpektrumTimer)--PrimarySpektrumState.SpektrumTimer
void PrimaryUart() _ISR (void)
void radio_control_spektrum_try_bind (void)
Variables
SpektrumStateType PrimarySpektrumState = {1,0,0,0,0,0,0,0,0,{0}}
int16_t SpektrumBuf [SPEKTRUM_CHANNELS_PER_FRAME *MAX_SPEKTRUM_FRAMES]
int8_t SpektrumSigns [] = RADIO_CONTROL_SPEKTRUM_SIGNS
static uint8_t EncodingType = 0
static uint8_t ExpectedFrames = 0
Macro Definition Documentation
#define __PrimaryUart (dev, _x) dev##_x
Definition at line 59 of file spektrum_arch.c.
#define __SecondaryUart (dev, _x) dev##_x
Definition at line 63 of file spektrum_arch.c.
#define _PrimaryUart (dev, _x) __PrimaryUart(dev, _x)
Definition at line 60 of file spektrum_arch.c.
#define _SecondaryUart (dev, _x) __SecondaryUart(dev, _x)
Definition at line 64 of file spektrum_arch.c.
#define DELAY_TIM_FREQUENCY 1000000
Definition at line 42 of file spektrum_arch.c.
Referenced by DelayMs(), and SpektrumDelayInit().
#define MASTER_RECEIVER_PULSES 5
Definition at line 44 of file spektrum_arch.c.
Referenced by radio_control_spektrum_try_bind().
#define MAX_BYTE_SPACE 3
Definition at line 50 of file spektrum_arch.c.
Referenced by SpektrumParser().
#define MAX_DELAY INT16_MAX
Definition at line 40 of file spektrum_arch.c.
#define MAX_SPEKTRUM_CHANNELS 16
Definition at line 38 of file spektrum_arch.c.
#define MAX_SPEKTRUM_FRAMES 2
Definition at line 37 of file spektrum_arch.c.
#define MIN_FRAME_SPACE 70
Definition at line 49 of file spektrum_arch.c.
Referenced by SpektrumParser().
#define PrimaryUart (_x) _PrimaryUart(RADIO_CONTROL_SPEKTRUM_PRIMARY_PORT, _x)
Definition at line 61 of file spektrum_arch.c.
Referenced by _ISR(), radio_control_spektrum_try_bind(), and SpektrumUartInit().
#define SecondaryUart (_x) _SecondaryUart(RADIO_CONTROL_SPEKTRUM_SECONDARY_PORT, _x)
Definition at line 65 of file spektrum_arch.c.
Referenced by radio_control_spektrum_try_bind(), and SpektrumUartInit().
#define SLAVE_RECEIVER_PULSES 6
Definition at line 45 of file spektrum_arch.c.
Referenced by radio_control_spektrum_try_bind().
#define SPEKTRUM_CHANNELS_PER_FRAME 7
Definition at line 36 of file spektrum_arch.c.
Referenced by RadioControlEventImp(), and SpektrumParser().
#define TIM_FREQ_1000000 1000000
Definition at line 47 of file spektrum_arch.c.
Referenced by SpektrumTimerInit().
#define TIM_TICS_FOR_100us 100
Definition at line 48 of file spektrum_arch.c.
Referenced by SpektrumTimerInit().
Typedef Documentation
typedef struct SpektrumStateStruct SpektrumStateType
Definition at line 80 of file spektrum_arch.c.
Function Documentation
void PrimaryUart() _ISR (void)
Definition at line 589 of file spektrum_arch.c.
References FALSE, PrimaryUart, and SpektrumParser().
static void DelayMs (uint16_t mSecs) static
Definition at line 741 of file spektrum_arch.c.
References DELAY_TIM_FREQUENCY, and DelayUs().
Referenced by radio_control_spektrum_try_bind().
static void DelayUs (uint16_t uSecs) static
Definition at line 733 of file spektrum_arch.c.
Referenced by DelayMs(), and radio_control_spektrum_try_bind().
if (PrimarySpektrumState. SpektrumTimer)
Referenced by alt_filter_periodic(), b2_hff_update_gps(), baro_event(), baro_ms5611_event(), humid_sht_event_i2c(), i2c_idle(), i2c_irq(), i2c_setbitrate(), i2c_smbus_block_process_call(), and mpu60x0_configure_i2c_slaves().
void radio_control_impl_init (void)
Definition at line 136 of file spektrum_arch.c.
References SpektrumStateStruct::ReSync, SpektrumTimerInit(), and SpektrumUartInit().
void radio_control_spektrum_try_bind (void)
Definition at line 643 of file spektrum_arch.c.
References DelayMs(), DelayUs(), gpio_enable_clock(), gpio_set(), gpio_setup_input(), gpio_setup_output(), MASTER_RECEIVER_PULSES, PrimaryUart, SecondaryUart, SLAVE_RECEIVER_PULSES, SPEKTRUM_BIND_PIN, SPEKTRUM_BIND_PIN_PORT, and SpektrumDelayInit().
void RadioControlEventImp (void(*)(void) frame_handler)
Definition at line 372 of file spektrum_arch.c.
References SpektrumStateStruct::ChannelCnt, ExpectedFrames, RadioControl::frame_cpt, SpektrumStateStruct::LostFrameCnt, MAX_PPRZ, radio_control, RADIO_CONTROL_NB_CHANNEL, RADIO_THROTTLE, RC_OK, SpektrumStateStruct::RcAvailable, SPEKTRUM_CHANNELS_PER_FRAME, RadioControl::status, RadioControl::time_since_last_frame, RadioControl::values, and SpektrumStateStruct::values.
static void SpektrumDelayInit (void) static
Definition at line 706 of file spektrum_arch.c.
References AHB_CLK, and DELAY_TIM_FREQUENCY.
Referenced by radio_control_spektrum_try_bind().
static void SpektrumParser (uint8_t _c, SpektrumStateType * spektrum_state, bool_t secondary_receiver) inline static
Todo:
collect more data. I suspect that there is a low res
Definition at line 255 of file spektrum_arch.c.
References SpektrumStateStruct::ChannelCnt, ExpectedFrames, SpektrumStateStruct::FrameCnt, SpektrumStateStruct::HighByte, SpektrumStateStruct::LostFrameCnt, MAX_BYTE_SPACE, MIN_FRAME_SPACE, SpektrumStateStruct::RcAvailable, SpektrumStateStruct::ReSync, SpektrumStateStruct::SecondFrame, SPEKTRUM_CHANNELS_PER_FRAME, SpektrumStateStruct::SpektrumTimer, SpektrumStateStruct::Sync, and SpektrumStateStruct::values.
Referenced by _ISR().
void SpektrumTimerInit (void)
Definition at line 470 of file spektrum_arch.c.
References AHB_CLK, TIM_FREQ_1000000, TIM_TICS_FOR_100us, and timer_clear_flag().
Referenced by radio_control_impl_init().
void SpektrumUartInit (void)
Definition at line 526 of file spektrum_arch.c.
References FALSE, gpio_enable_clock(), gpio_setup_pin_af(), PrimaryUart, and SecondaryUart.
Referenced by radio_control_impl_init().
void tim6_irq_handler (void)
timer_clear_flag (TIM6 , TIM_SR_UIF)
Referenced by SpektrumTimerInit().
Variable Documentation
uint8_t EncodingType = 0 static
Definition at line 115 of file spektrum_arch.c.
uint8_t ExpectedFrames = 0 static
Definition at line 116 of file spektrum_arch.c.
Referenced by RadioControlEventImp(), and SpektrumParser().
SpektrumStateType PrimarySpektrumState = {1,0,0,0,0,0,0,0,0,{0}}
Definition at line 82 of file spektrum_arch.c.
int16_t SpektrumBuf[SPEKTRUM_CHANNELS_PER_FRAME *MAX_SPEKTRUM_FRAMES]
Definition at line 93 of file spektrum_arch.c.
int8_t SpektrumSigns[] = RADIO_CONTROL_SPEKTRUM_SIGNS
Definition at line 112 of file spektrum_arch.c.