Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/gpio_arch.h File Reference
gpio_arch.h File Reference
STM32 architecture
GPIO helper functions for STM32F1 and STM32F4.
#include <libopencm3/stm32/gpio.h>
Functions
static void gpio_output_high (uint32_t port, uint16_t pin)
Set a gpio output to high level.
static void gpio_output_low (uint32_t port, uint16_t pin)
Clear a gpio output to low level.
void gpio_setup_pin_af (uint32_t port, uint16_t pin, uint8_t af, bool_t is_output)
Setup a gpio for input or output with alternate function.
void gpio_enable_clock (uint32_t port)
Detailed Description
GPIO helper functions for STM32F1 and STM32F4.
Definition in file gpio_arch.h.
Function Documentation
void gpio_enable_clock (uint32_t port)
Referenced by ppm_arch_init(), radio_control_spektrum_try_bind(), and SpektrumUartInit().
static void gpio_output_high (uint32_t port, uint16_t pin) inline static
Set a gpio output to high level.
Definition at line 37 of file gpio_arch.h.
References gpio_set().
static void gpio_output_low (uint32_t port, uint16_t pin) inline static
Clear a gpio output to low level.
Definition at line 44 of file gpio_arch.h.
void gpio_setup_pin_af (uint32_t port, uint16_t pin, uint8_t af, bool_t is_output)
Setup a gpio for input or output with alternate function.
Referenced by ppm_arch_init(), and SpektrumUartInit().